### ISSUE TITLE
New note from card does not use the chosen template

### ISSUE THREAD

**Issue by Rhydderch** [mgmeyers/obsidian-kanban#100]
Hello there,

I really love this plugin and love the ability to personalize the settings for each board.
It seems however that the "create new note from card" just generates an empty note even if a template has been specified.

**Comment by mgmeyers** [comment]
Thanks @Rhydderch! Was this when using templeter templates? If so I believe I fixed the issue. If you still have problems with this, feel free to reopen this issue.

**Comment by Rhydderch** [comment]
yes indeed, I was using a templater template @mgmeyers .
It seems the other issue is when the note is opened by default in "preview" mode. When it is opened in preview mode at first, I need to switch to the editor mode for the template to show up. I don't know whether you can force the note to open up in editor mode?
Anyways, thank you for fixing it so quickly and creating this plugin. Kanban boards are now gonna be a key piece in handling my projects :)

**Comment by slowpokefarm** [comment]
The same issue is valid for regular templates, when the default pane mode is set to Preview, the note is created without template.

**Comment by mgmeyers** [comment]
Thanks @slowpokefarm, I didn't realize one could set preview mode as default. I've updated the plugin with a fix for this.
