### ISSUE TITLE
Error: kanban locale not found en-gb

### ISSUE THREAD

**Issue by chhoumann** [mgmeyers/obsidian-kanban#106]
Hey,

I'm getting a lot of these errors: `Error: kanban locale not found en-gb`
The current English translation is just called `en`.
I'm not sure how to select anything else. My Obsidian locale is just `English`.

Usually, there'd be a `en-us` and `en-gb` locale. Personally, I don't mind the difference, so a feature that let me disable the error logs would be great.

![image](https://user-images.githubusercontent.com/29108628/119312548-cad23700-bc72-11eb-8f63-67aec80aa3ac.png)

**Comment by mgmeyers** [comment]
Sorry about that @chhoumann! If you update the plugin, the errors should go away!

**Comment by chhoumann** [comment]
Great! Thank you :)
