### ISSUE TITLE
The search seems too fuzzy

### ISSUE THREAD

**Issue by frvkl** [mgmeyers/obsidian-kanban#107]
> RE: Adds ability to search Kanban boards using the default search hotkey.

The search seems too fuzzy when searching for short words, like for example 'css'.

Would it be possible to set the level of fuzziness for the search?

**Comment by mgmeyers** [comment]
Thanks @frvkl, you're right, it was way too fuzzy. I've set it to only allow exact (case-insensitive) matches for now until I can figure out a better solution
