### ISSUE TITLE
[Feature Request] Add a shortcut to toggle between kanban mode and markdown mode

### ISSUE THREAD

**Issue by YQGong** [mgmeyers/obsidian-kanban#109]
I currently using kanban view as the daily note template. But Slated plugin is not compatible with the kanban view. If I want to move incomplete tasks to today's daily note, I need to switch to the markdown view, run command provided by Slated and switch to the kanban view.
A shortcut to toggle between kanban mode and markdown mode will provide convenience while there's compatibility issues with other plugins.

**Comment by skillhacker-code** [comment]
Yes it would be great . I also need this feature

**Comment by mgmeyers** [comment]
@YQGong & @skillhacker-code I've added a new command that toggles between kanban and markdown modes. Let me know if you run into any issues with it.

**Comment by skillhacker-code** [comment]
Thank you so much , it is working . Thank you so much

**Comment by wagle** [comment]
Its not working for me with
MacOS 12.6
obsidian 0.16.2
kanban 1.3.17

and this setup
https://bagerbach.com/blog/projects-and-goals-obsidian

The three vertical dots are not displayed, and the only kanban command listed by command p is
"Kanban: Create new board"

What information do I need to add to let you home in on this?
