### ISSUE TITLE
Adding aliases to yaml frontmatter section causes the board to throw an error on opening

### ISSUE THREAD

**Issue by slowpokefarm** [mgmeyers/obsidian-kanban#112]
I have just installed the plugin and added the new board with a few empty lists.
Then I have opened the file as markdown and added native aliases to yaml frontmatter section. 
After I've closed the board I couldn't reopen it without removing aliases from yaml.
When trying to open it I get an error:
<img width="331" alt="изображение" src="https://user-images.githubusercontent.com/11663130/119832442-78a54600-befe-11eb-9d4e-7d3810a0ff89.png">

**Comment by mgmeyers** [comment]
Thanks @slowpokefarm! I figured out what was going on here. Try updating the plugin and let me know if you still have issues!

**Comment by slowpokefarm** [comment]
@mgmeyers Works now, thank you!
