### ISSUE TITLE
[Bug] Cannot insert link into card with  obsidian-auto-link-title plugin on 

### ISSUE THREAD

**Issue by danieltomasz** [mgmeyers/obsidian-kanban#118]
I was using autolink plugin happily with kanban plugin  together, since some of the latest updates  of Kanban plugin I cannot insert any link with autolink plugin on  anymore
[GitHub - zolrath/obsidian-auto-link-title: Automatically fetch the titles of pasted links](https://github.com/zolrath/obsidian-auto-link-title)

**Comment by mgmeyers** [comment]
Thanks @danieltomasz this is actually a bug in https://github.com/zolrath/obsidian-auto-link-title. It assumes anything that's being pasted into is the obsidian editor. The Kanban plugin uses a plain textarea, however

**Comment by danieltomasz** [comment]
I might fill a issue there as well

**Comment by zolrath** [comment]
I've hooked into the newish "editor-paste" event and no longer trigger any paste changes in search fields, nor does it have any effect in the Kanban plugin so you should be able to use Kanban normally as if this plugin were not enabled!

I'm not sure if there's a good solution to me integrating with the KanbanView this plugin creates?
