### ISSUE TITLE
Show total number of cards at the top

### ISSUE THREAD

**Issue by timconnorz** [mgmeyers/obsidian-kanban#123]
It would be really great to show the total number of cards at the top of each list!

**Comment by mgmeyers** [comment]
Thanks @timconnorz! This actually exists right now, but I haven't had time to figure out the design for it. If you're handy with CSS you can un-hide and style the element `.kanban-plugin__lane-title-count`. It's on my radar to figure this out, though

**Comment by timconnorz** [comment]
Thanks man! i'll do that

**Comment by frvkl** [comment]
This is how I styled this section:

```
/* lane header */
.kanban-plugin__lane-title{
    display: flex;
    justify-content: center;
    align-items: center;
    text-align: center;
    padding: .5em 0;
    min-height: 5.25em;
    position: relative;
}
.kanban-plugin__lane-title-text{
    width:calc(100% - 5em)!important;
}
.kanban-plugin__lane-title-text > *{
    overflow-x: hidden!important;
}
.kanban-plugin__lane-title-count{
    line-height: 1em;
    text-align: center;
    background-color: var(--background-primary);
    border: 1px solid var(--background-modifier-border);
    color: var(--text-muted);
    border-radius: 2px;
    font-weight: 400;
    padding: .2em .3em;
    position: absolute;
    right: 0;
}
```

**Comment by xypd** [comment]
Thank to both of you @frvkl @mgmeyers for making this easy to drop in.

Here what it looks like for those that are curious.

![numberofcards](https://user-images.githubusercontent.com/23583395/160253884-657bf6ea-5240-458c-9380-0125d2465adf.png)

**Comment by mgmeyers** [comment]
I know it's been a while, but I've finally added a count of the number of cards in a list up at the top. I have plans to expand on this some more, but this is at least a step in that direction.

<img width="282" alt="Screen Shot 2022-04-04 at 8 05 06 PM" src="https://user-images.githubusercontent.com/2694747/161670868-8777447a-0765-433e-816d-dad0fb6a32c5.png">
