### ISSUE TITLE
Search not including metadata values

### ISSUE THREAD

**Issue by frvkl** [mgmeyers/obsidian-kanban#125]
First: I love the new feature where meta data can be shown on the cards. Unfortunately, the board search does not look at the meta data. It would be great if the board search would also look at the meta data values shown on the cards to filter the board when searching.

**Comment by mgmeyers** [comment]
@frvkl I've implemented a basic version of this. I'll be enhancing it in the future with more accurate highlighting of the search string. Right now it'll highlight the whole field.

<img width="272" alt="Screen Shot 2021-06-06 at 10 05 16 AM" src="https://user-images.githubusercontent.com/2694747/120933367-b3517000-c6ae-11eb-9514-43b9867708d0.png">

**Comment by frvkl** [comment]
@mgmeyers This is exactly what I needed. Many thanks and keep up the good work!
