### ISSUE TITLE
Add classes to metadata html for individual css styling options

### ISSUE THREAD

**Issue by frvkl** [mgmeyers/obsidian-kanban#128]
The new meta data addtion is great. Just an idea:

If you could add the key (and perhaps the values) as css classes, like shown below, we could implement individual styling to the individual meta sections:
![shot_210602_101326](https://user-images.githubusercontent.com/19724110/120447755-3317cb80-c38b-11eb-9c72-230ac7a819cd.png)

I could style data like 'High' with a red color, for instance.

**Comment by mgmeyers** [comment]
@frvkl I've added some data attributes that should help out here:

<img width="594" alt="Screen Shot 2021-06-06 at 10 01 54 AM" src="https://user-images.githubusercontent.com/2694747/120933295-4ccc5200-c6ae-11eb-8caf-2a7b7138d088.png">

Let me know if this works for your use case

**Comment by frvkl** [comment]
@mgmeyers This is perfect. Thank you so much for adding this. It really helps to give the cards an extra dimension.
