### ISSUE TITLE
[BUG?]Cannot load metadata after add it by using Superchargelink plugin

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-kanban#129]
After I add metadata to a card note, I should close kanban and then reopen it to make the metadata showing on the card.

**Comment by mgmeyers** [comment]
@Quorafind This should be fixed now! Let me know if you still have issues

**Comment by Quorafind** [comment]
Hmmmm, it still have issues after I update it to 0.4.2, and it even cannot show after I toggle the option twice and reinstall Kanban  plugin.

https://user-images.githubusercontent.com/13215013/120570671-36728c00-c44b-11eb-92ce-785b4b8e4222.mp4
