### ISSUE TITLE
After restart Obsidian, should toggle hide label option again to make the metadata showing

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-kanban#130]
If I have added metadata to the card note, when I restart the Obsidian, I should toggle the hide label option twice to make the metadata showing.
![image](https://user-images.githubusercontent.com/13215013/120452526-d5a07080-c3c4-11eb-9109-0fcaff7e3ca8.png)

**Comment by Quorafind** [comment]
Here is recording video.


https://user-images.githubusercontent.com/13215013/120453776-e9000b80-c3c5-11eb-8e6d-3ee71895e18e.mp4

**Comment by mgmeyers** [comment]
Thanks @Quorafind! I'll see what I can do here. This reason this happens is because Dataview doesn't tell me when its cache updates.

**Comment by mgmeyers** [comment]
Filed an issue with dataview that should help fix this if implemented: https://github.com/blacksmithgu/obsidian-dataview/issues/268

**Comment by mgmeyers** [comment]
@Quorafind This is finally fixed in 1.0.0!
