### ISSUE TITLE
add Supercharged link support (for inline field)

### ISSUE THREAD

**Issue by Mara-Li** [mgmeyers/obsidian-kanban#135]
Hello ! With the new update, I try to add some metadata and inline link field on some cards. But, link doesn't display well : 

- For Wikilinks : 
![image](https://user-images.githubusercontent.com/30244939/120553930-62fdb800-c3f9-11eb-9025-88284711dc2c.png)

- For markdown normal link :
![image](https://user-images.githubusercontent.com/30244939/120554187-bc65e700-c3f9-11eb-9334-7005a7e01493.png)

My settings is to use relative path. But, i don't think it can change anything !

So, if it's possible to add link support + supercharged link rendering, it can be very cool ! 😊

**Comment by mgmeyers** [comment]
@Mara-Li can you confirm if this is still an issue? I believe it is fixed, but not 100% sure.

**Comment by Mara-Li** [comment]
Wow sorry ! I totally forgot about this issue.
Yes, I don't have any problem :), this issue can be closed !
