### ISSUE TITLE
Feature Request: Looking forward to supporting subtasks

### ISSUE THREAD

**Issue by tyf2018** [mgmeyers/obsidian-kanban#137]
The plugin is awesome,  and I Looking forward to supporting subtasks, as shown in the screenshot below
![C_2021 06 03_15 09 15](https://user-images.githubusercontent.com/56342788/120602764-ea8d0a80-c47d-11eb-80af-abe393665159.jpg)

Thank You.

**Comment by chuckthenerd** [comment]
@tyf2018 - as an intermediate solution - take a look at the 'tasks' community plugin.  I started using it today, and it has been extremely helpful in uncovering old tasks with outlying TODO items.

**Comment by kevinawoo** [comment]
FYI, it kinda funkily works right now. It display the an indented checklist as individual cards in preview. Switching between raw markdown and preview is fine, there's no data mutation. 

When the task is moved to another column or reordering, it'll get unindented back to root. At least there's no data loss.

It'll be nice if it were to show as sub tasks though in preview mode.

**Comment by tyf2018** [comment]
> @tyf2018 - as an intermediate solution - take a look at the 'tasks' community plugin. I started using it today, and it has been extremely helpful in uncovering old tasks with outlying TODO items.

Thanks, I will try

**Comment by mgmeyers** [comment]
This can now be accomplished in 1.0.0. shift+enter (this can be changed in settings) will create a new line. You can add tasks to cards using markdown:

<img width="303" alt="Screen Shot 2021-09-11 at 1 12 56 PM" src="https://user-images.githubusercontent.com/2694747/132960486-f9a3b00c-99ee-4efa-b1a4-976536d82fd6.png">

<img width="310" alt="Screen Shot 2021-09-11 at 1 13 03 PM" src="https://user-images.githubusercontent.com/2694747/132960492-11ce323f-caaf-43e5-a2a2-baa9c24ff3a7.png">

I'll be enhancing the support for subtasks in the future, so stay tuned for more.

**Comment by chenyenru** [comment]
Hi any updates on enhancing the support for subtasks?
