### ISSUE TITLE
Feature request: i18n support?

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-kanban#14]
# Why I need this

I don't know if it is doable by using api directly. Or you have to create a module to show i18n text?

**Comment by mgmeyers** [comment]
https://discord.com/channels/686053708261228577/714234422379151400/835031480644010024

> boninall — Yesterday at 7:24 PM
@ Licat A small question, are there any good ways for i18n in plugins? Or should the plugins developer create a i18n module?
Licat — Yesterday at 10:56 PM
Not yet - We might just expose our i18n library and give plugins a way to add their i18n languages directly into it.

**Comment by Quorafind** [comment]
@mgmeyers LOL, Boninall is me😂

**Comment by mgmeyers** [comment]
@Quorafind I've added support for i18n, now I just need some folks to help translate the plugin!

These are the languages supported by obsidian: https://github.com/mgmeyers/obsidian-kanban/tree/main/src/lang/locale
Here are the english strings that would need translating: https://github.com/mgmeyers/obsidian-kanban/blob/main/src/lang/locale/en.ts
