### ISSUE TITLE
Dirty HTML when auto convert html is turned off

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-kanban#142]
@pjeby 

When auto convert HTML is turned off, pasting in HTML from obsidian brings in a ton of extra HTML.

In the image below, I copied the first paragraph on the left. Do you know of anyway we can prevent this or reliably clean it up?

<img width="1064" alt="Screen Shot 2021-06-03 at 9 16 56 PM" src="https://user-images.githubusercontent.com/2694747/120744986-0cec4b80-c4b1-11eb-9d9e-431fa9484b31.png">

**Comment by pjeby** [comment]
Change `const lines: string[] = (text || html || uris || plain || "")` to `const lines: string[] = (text || uris || plain || html || "")` in ItemForm.tsx.
