### ISSUE TITLE
Dragging multiple files into a board adds an index to each link

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-kanban#143]
@pjeby I'm sure this is a quick fix. Any initial thoughts? I won't have time to look into it until next week. 

<img width="292" alt="Screen Shot 2021-06-03 at 9 30 03 PM" src="https://user-images.githubusercontent.com/2694747/120745865-dca5ac80-c4b2-11eb-9c42-11104b5dfc94.png">

**Comment by pjeby** [comment]
Ugh.  `draggable.files.map(linkTo)` should be `draggable.files.map(f => linkTo(f))` in ItemForm.tsx.  Can't believe I missed that.
