### ISSUE TITLE
Failed to install plugin obsidian-kanban

### ISSUE THREAD

**Issue by matthewfduffy** [mgmeyers/obsidian-kanban#154]
**Describe the bug:**
Plugin does not install

**Steps to Reproduce:**
Navigate to Settings > Community plugins > browse > Kanban > Install

**Expected Result:**
Plugin downloads/installs

**Actual Result:**
+ Receives pop-up stating "No appropriate version found"
+ Plugin does not install

**System Information:**
+ OS:  Windows 10 Pro 1809
+ Obsidian Version: v0.11.3
+ Kanban Version: 0.5.0

**Other Information:**
+ No errors are shown in the console when install fails
+ Other community plugins installed successfully before/after this error

![obsidian-kanban-install-fail](https://user-images.githubusercontent.com/10624656/120894605-e1677f00-c5de-11eb-850e-5cff456a3a5f.png)

**Comment by mgmeyers** [comment]
Hmm, strange. So the latest version of the Kanban plugin requires at least obsidian 0.12.3. But it should still fallback to and older version that supports 0.11.3 🤔.

I'll poke around, but if you want the latest features, you'll need to upgrade obsidian.

**Comment by matthewfduffy** [comment]
Thanks for looking into this. I was able to install Kanban v.0.5.2 after upgrading Obsidian to v.012.3.
Closing bug report.
