### ISSUE TITLE
[feature request] Add autocompletion when adding Obsidian link by alias

### ISSUE THREAD

**Issue by danieltomasz** [mgmeyers/obsidian-kanban#156]
Currently When I try to add a link by alias and type  [[ bracket and alias inside the card there is no autocompletion.
The same alias work outside card.

Kanban 0.5.1
Obsidian 0.12.3

**Comment by mgmeyers** [comment]
Thanks @danieltomasz ! This is already on my radar: https://github.com/mgmeyers/obsidian-kanban/issues/149

Going to close out this issue in favor of the one above.

**Comment by danieltomasz** [comment]
Yes! Sorry I didn't notice the previous issue!
