### ISSUE TITLE
UI doesn't load when creating a new board

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-kanban#157]
Both from the command & the folder context menu. 

@pjeby Do you think this may be related to the latest updates?

**Comment by pjeby** [comment]
Looks like a refreshViews() is needed,  That's why in some of my late commits yesterday I was adding ones for when you switch workspaces or Obsidian starts; apparently it's needed some other places.

**Comment by pjeby** [comment]
I think the reason newKanban isn't working right is because it doesn't use the normal setViewState method of loading?  I'm not sure why you're not just doing a setViewState, there.

**Comment by pjeby** [comment]
PR #158 pushed with a fix.
