### ISSUE TITLE
Different link types on new vs. updating drag from File Explorer

### ISSUE THREAD

**Issue by JJSlote** [mgmeyers/obsidian-kanban#173]
Hi - If we add a card, and drag an entry from the File Explorer into the new cell, we get a link in the form
 _`[filename](filename.md)`_ and a clean, plain-text preview.

But if we clear text from an existing card and then drag in a File Explorer entry, our link is in the less readable form
_`obsidian://open?vault=vaultname&file=filename`_ shown the same in preview as in edit. 

Bug? Thanks for taking a look.
Rgds - Jerome
Version 0.5.5.

**Comment by pjeby** [comment]
Currently, there is no support for drag-drop during card editing, only for card adding.  It's something that might be added in the future, but it's awaiting a decision on whether this plugin will be staying with the current drag-drop library it uses, or switching to something else.

**Comment by mgmeyers** [comment]
This should be fixed now @JJSlote
