### ISSUE TITLE
Vertical lane enhancements

### ISSUE THREAD

**Issue by bnonn** [mgmeyers/obsidian-kanban#174]
Connected to [lane settings](https://github.com/mgmeyers/obsidian-kanban/projects/1#card-62538121), I have the following suggestions:

- Make the Add A List button a simple `+` symbol, with a tooltip saying "Add a list" to prevent it taking up a whole lane-worth of real estate. This will solve some UI papercuts, e.g., having a horizontal scrollbar present when all of my columns actually fit the viewport, and triggering horizontal scroll by accident if I drag a card too far (forcing me to scroll back to reset the view).
- You could do the same thing with the Add A Card button, though this seems more a matter of preference for minimalism.
- Create a responsive width setting so that columns can auto-size according to viewport width, rather than being set at a hard pixel value. Something like `clamp(270px, 100vw/column_count, 30vw)` would probably result in ideally-sized columns in the large majority of cases. This would also solve the problem of half of a full-width kanban disappearing behind a horizontal scroll, when opening a note in a second horizontal pane (which is quite a convenient use case).

**Comment by j-u-l-i-u-s** [comment]
Also, it would be great to consistently name them as (vertical) "lists" not (horizontal) "lanes".
