### ISSUE TITLE
Link Dates To Daily Note incompatible with Create Note From Card

### ISSUE THREAD

**Issue by pdxrlk** [mgmeyers/obsidian-kanban#183]
I use the Link Dates To Daily Note feature to link by date (starting by typing "@").  However if I also Create Note From Card, then the generated markdown does not resolve to a valid link.

For example the following task has four closing brackets.  Perhaps you need to remove the date from the name?

```
- [ ] [[Write email transitioning work to James Bond @[[2021-06-09]]]]
```

**Comment by miguelmarcos** [comment]
pdxrlk, what plugin is this feature from? Thanks.

> I use the Link Dates To Daily Note feature to link by date (starting by typing "@").

**Comment by pdxrlk** [comment]
Both of those features are from the Kanban plugin :-). "Link Dates to Daily Notes" is from the Kanban configuration page.

> pdxrlk, what plugin is this feature from? Thanks.

**Comment by miguelmarcos** [comment]
Ah, got it. That would be super across the board in Obsidian. Thanks.

**Comment by mgmeyers** [comment]
Hey @pdxrlk there's a setting that should help you out here:

<img width="624" alt="Screen Shot 2021-06-10 at 9 37 14 AM" src="https://user-images.githubusercontent.com/2694747/121563629-726b9b00-c9cf-11eb-97f6-a4d817847f1f.png">
