### ISSUE TITLE
Pasting multiple lines fails in 0.12.5

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-kanban#192]
Seems `(MarkdownSourceView.prototype as any).handleDataTransfer.call` is erroring out:

<img width="650" alt="Screen Shot 2021-06-11 at 6 09 06 PM" src="https://user-images.githubusercontent.com/2694747/121760519-1f353d80-cae0-11eb-8a81-4568f3cd3fcf.png">

https://github.com/mgmeyers/obsidian-kanban/blob/main/src/components/Item/ItemForm.tsx#L25

cc: @pjeby

**Comment by mgmeyers** [comment]
Ah, right:


> There is now a function available for converting HTML to Markdown called htmlToMarkdown, which is using a pre-configured Turndown Service.
https://forum.obsidian.md/t/obsidian-release-v0-12-5-insider-build/19374

**Comment by pjeby** [comment]
For now I'm going to focus on fixing the UX regression from #190, but I'll swing back around to this after if you haven't got it by then.  Presumably, the fix for this should check if htmlToMarkdown is available and fallback if not.  (At least until 0.12.5 is in wide release.)

**Comment by mgmeyers** [comment]
Implemented a temporary, though easy fix!
