### ISSUE TITLE
[Feature Request] Allow shift+enter to make new line inside edit mode

### ISSUE THREAD

**Issue by Obadiahcruz** [mgmeyers/obsidian-kanban#198]
Allow shift + Enter to create a new line break and have it render as such on the board. Right now enter saves the edit but you cannot create a new line with shift + enter

**Comment by Gentleman03** [comment]
+1 any chances for this?

**Comment by mgmeyers** [comment]
@Gentleman03 Yes, support for this is on the roadmap: https://github.com/mgmeyers/obsidian-kanban/projects/1#card-62537891

**Comment by Gentleman03** [comment]
That is great! Haven't seen this roadmap. Thanks for developing such awesome plugin :)

**Comment by mgmeyers** [comment]
This has been added in 1.0.0
