### ISSUE TITLE
No going back from Markdown view

### ISSUE THREAD

**Issue by bobbleheadjoe** [mgmeyers/obsidian-kanban#2]
The functionality of the plugin is awesome, but I've found that once I view as Markdown I can't get back to the actual board view. Here's my steps:

1. Use Command Palette to create new kanban board
2. Edit the kanban board and name the file
3. Click on "More Options" and select "Open as Markdown"
4. The icon changes from he cube stack to a sheet of paper and can't view as kanban again

**Comment by mgmeyers** [comment]
Thanks @bobbleheadjoe , this was a bug on my end. You should see this now in the "More options" menu when viewing kanbans as markdown:

<img width="209" alt="Screen Shot 2021-04-22 at 10 19 27 AM" src="https://user-images.githubusercontent.com/2694747/115758713-48ddae00-a354-11eb-98e3-c1b9d7dc816f.png">
