### ISSUE TITLE
[Bug] Unable to View Markdown and Kanban Together Unless Unlinked

### ISSUE THREAD

**Issue by SlRvb** [mgmeyers/obsidian-kanban#20]
Kanban only shows either Kanban view or Markdown view for both split and linked panes. Hopefully you can allow for showing both views when the panes are linked.

The only way to avoid this issue currently is to unlink them to show both.

![O15TQ2G1Tm](https://user-images.githubusercontent.com/54087190/115953858-cb748380-a4a2-11eb-9bf6-4b5023aafbf2.gif)

**Comment by mgmeyers** [comment]
Ah good catch. Also your kanban styling is looking 🔥 🔥 🔥

**Comment by mgmeyers** [comment]
@SlRvb This should be fixed now!
