### ISSUE TITLE
Unable to save Board settings

### ISSUE THREAD

**Issue by jeremykao** [mgmeyers/obsidian-kanban#200]
Hi there! 
For some odd reason, I'm unable to save individual Kanban board settings, but able to save global plugin settings.

### Helpful Information:
Obsidian v0.12.4
Kanban Plugin v0.5.10
Windows 10 Desktop app

### Reproduction Steps
1) Create templates in a "Templates" folder
2) Create Kanban board
3) Click "More Options" > "Open Board Settings" to open individual Kanban board settings
4) Click on "Note template" field to open template name dropdown
5) Click on a template name in dropdown to populate field
6) Close options modal
7)  Click "More Options" > "Open Board Settings" to open individual Kanban board settings
8) Observe "Note template" field shows "No template" placeholder

### Here is a video demonstrating the bug
https://user-images.githubusercontent.com/1605835/121787298-2c9f0600-cb7a-11eb-9f72-e13fa7e89059.mp4

I tried looking through the code, but there isn't anything particularly obvious. Unsure how to run locally or look at console logs. 

Thanks!

**Comment by mgmeyers** [comment]
Yikes, thanks for the report. I'll look into it!

**Comment by mgmeyers** [comment]
Also, one less-than-stellar workaround: if you view the board as markdown, you can add / change this frontmatter key to point to the template you want to use:

```
new-note-template: Templates/Annotation Template.md
```

**Comment by jeremykao** [comment]
Ahhh awesome! Thanks for that snippet! Was just clicking "Insert Template" when I create a new note from a card, but this is way easier and works great!
