### ISSUE TITLE
Setting and frontmatter changes do not refresh the board

### ISSUE THREAD

**Issue by mgmeyers** [mgmeyers/obsidian-kanban#202]
@pjeby Just creating a ticket for this to keep track, I know you're deep in the weeds and we'll get this sorted out shortly.

1. Updating settings (eg. Hide tags in card titles) does not refresh the board
2. Updates to frontmatter of linked pages do update the corresponding card

**Comment by mgmeyers** [comment]
# 2 probably has a lot to do with this my hacky approach to forcing a card to refresh: https://github.com/mgmeyers/obsidian-kanban/blob/main/src/components/Item/Item.tsx#L268-L282

**Comment by pjeby** [comment]
Just FYI, a fix for this is already in my branch; I discovered it while verifying the settings updating of the cache in the new incremental parser.

**Comment by pjeby** [comment]
(More precisely, a fix for number 1; number 2 I just put in notes on, since that problem already existed before.)

**Comment by pjeby** [comment]
Number 2 should also be fixed now in the PR.
