### ISSUE TITLE
Formatting is lost when document is re-rendered

### ISSUE THREAD

**Issue by chishaku** [mgmeyers/obsidian-kanban#205]
Formatting lost:
- indent
- line breaks

Given I have an indented outline like this:

```markdown

- item 1

- item 2
    - indented item 1
    - indented item 2

- item 3 
- item 4
```

When I trigger a re-render such as by dragging a card, my outline is flattened like this:

```markdown

- item 1
- item 2
- indented item 1
- indented item 2
- item 3
- item 4
```

**Comment by mgmeyers** [comment]
Thanks @chishaku, this is actually an intentional limitation. The plugin requires a consistent underlying markdown format to work properly. 

Nested list support should be coming in the future, though
