### ISSUE TITLE
Search is no longer working

### ISSUE THREAD

**Issue by frvkl** [mgmeyers/obsidian-kanban#206]
Obsidian v.0.5.12
Kanban plugin v.0.5.12

After updating the plugin this morning, the search on board does not seem to be werking anymore?

**Comment by mgmeyers** [comment]
@frvkl This should be fixed now. Let me know if this is not the case!

**Comment by frvkl** [comment]
@mgmeyers Tested and approved. Thank you for your quick response, as always.
