### ISSUE TITLE
Respect new note folder when clicking on unresolved link

### ISSUE THREAD

**Issue by jowibou** [mgmeyers/obsidian-kanban#207]
On my boards at least this setting is ignored and new cards are being created at the same level as the board (my default setting in "Files and Links").

**Comment by mgmeyers** [comment]
Hmmm, just to double check, are you on the latest version of the plugin?

**Comment by jowibou** [comment]
Yup. I'm on 0.5.12

**Comment by Molin-L** [comment]
v0.5.14. Same problem.

**Comment by jowibou** [comment]
I now realize I was doing this wrong. I thought clicking on an unresolved link should create a note in the folder selected in the preference, which didn't work. What does indeed work correctly is creating a new note from the card's menu. 
So I guess this is more of feature request than a bug report. Sorry for the confusion!

**Comment by mgmeyers** [comment]
Clicking on unresolved daily note links will now place the notes in the correct folder

**Comment by skorper** [comment]
> Clicking on unresolved daily note links will now place the notes in the correct folder

@mgmeyers Which version supports this?
