### ISSUE TITLE
Feature Request: Kanban Transclusion

### ISSUE THREAD

**Issue by brimwats1** [mgmeyers/obsidian-kanban#21]
An idea for how the transclusion might look: 

![image](https://user-images.githubusercontent.com/49103046/115958644-169b9000-a4bd-11eb-9ffc-fe825cfbc054.png)

No idea if this is possible, and it is just a minor request! But thought it would be a neat addition to daily note template.

**Comment by dariuszkowalski-com** [comment]
+1

**Comment by mgmeyers** [comment]
Closing this in favor of #4

**Comment by EditorJack** [comment]
Yes, please! This actually kind-of works now, but it tends to lock things up. Also, sometimes the underlying HTML code is exposed in read, particularly <\b>. Please investigate this and fix it. It would be wonderful to display the kanban as a transcluded Markdown document.

**Comment by Facni** [comment]
+1, Would be nice to be able to use links to headings to show the boars we want, example ![[Kanban#board1]].

**Comment by webenadam** [comment]
> +1, Would be nice to be able to use links to headings to show the boars we want, example ![[Kanban#board1]].

This would be amazing!
