### ISSUE TITLE
Template is not working

### ISSUE THREAD

**Issue by Molin-L** [mgmeyers/obsidian-kanban#214]
I've tried to set `Template/kanban_template` as default template but failed when creating new kanban. The new kanban is still empty. 

Version: 0.5.14

**Comment by mgmeyers** [comment]
Thanks @Molin-L are you using templater templates, or built in?

**Comment by Molin-L** [comment]
> Thanks @Molin-L are you using templater templates, or built in?

I think it's built in. I just create a note as below and refer it from plugin setting. Is that the right way to use Kanban template?

```
---

kanban-plugin: basic

---

## Todo

## In Process

## Done
```

**Comment by csss1234** [comment]
I'm having the same problem

**Comment by csss1234** [comment]
> > Thanks @Molin-L are you using templater templates, or built in?
> 
> I think it's built in. I just create a note as below and refer it from plugin setting. Is that the right way to use Kanban template?
> 
> ```
> ---
> 
> kanban-plugin: basic
> 
> ---
> 
> ## Todo
> 
> ## In Process
> 
> ## Done
> ```

ooohhh i think you and i misunderstood the purpose of the template! the template is for "New NOTE from kanban". not for new kanban.

**Comment by mgmeyers** [comment]
Apologies for the delay on this, but I've create documentation on how to use templates: http://matthewmeye.rs/obsidian-kanban/Settings/Note%20template/

Like csss1234 said, the template is used when creating new notes from cards.
