### ISSUE TITLE
Don't show spaces around tag when using 'hide tags in card title'

### ISSUE THREAD

**Issue by MosheSteinberg** [mgmeyers/obsidian-kanban#215]
I use the 'Hide tags in card title' setting. Often I'll have the text of my card as '#Tag Actual information'.
This renders as ' Actual information'. Could the setting be that little bit more intelligent and not render the space around the tag?

**Comment by mgmeyers** [comment]
@MosheSteinberg This should be fixed in the latest version of the plugin. Let me know if you still have issues!

**Comment by MosheSteinberg** [comment]
Quick look indicates it is fixed. Thank you so much!
