### ISSUE TITLE
Lost switcher between Kanban and Markdown since updating to 0.0.6

### ISSUE THREAD

**Issue by edward-peters** [mgmeyers/obsidian-kanban#22]
I just updated from 0.0.6, and for my existing Kanban board, the switcher in the menu has disappeared. I can use Command+E to switch between edit and preview, but no Kanban.

I created a new Kanban board via the Palette and added some stuff to it, all ok. But can't switch that one at all, no menu item.

**Comment by mgmeyers** [comment]
@edward-peters This may be related to an update I made to the frontmatter key. Does the frontmatter for that file look like:

```
---

kanban: basic

---
```

If so, if you change it to:

```
---

kanban-plugin: basic

---
```

it should fix it. You may need to close and reopen the kanban after making this update.

Let me know if this doesn't work for you.

**Comment by edward-peters** [comment]
@mgmeyers Yes, that was it. Sorry I missed this change... A big thank you for this fabulous plugin and for the latest updates in v.0.0.9.
