### ISSUE TITLE
Write text near the board?

### ISSUE THREAD

**Issue by cristianvasquez** [mgmeyers/obsidian-kanban#223]
Hello, thanks for this useful plugin!

I have a question: How can I write text before or after the kanban? can this be embedded?

Thanks!

**Comment by mgmeyers** [comment]
@cristianvasquez This is not yet possible, but is on my radar. I'm going to close this issue, though since a request for embedded boards already exists: #4 

I also have a ticket for allowing board descriptions: https://github.com/mgmeyers/obsidian-kanban/projects/1#card-68583785
