### ISSUE TITLE
Daily Note not created following Daily Note plugin settings

### ISSUE THREAD

**Issue by edikon** [mgmeyers/obsidian-kanban#225]
Hi there, if I add the daily note link to tasks cards and then click on the daily note link, it create a new note in the default obsidian vault folder and ignore the Daily Note plugin settings.  I would imagine it should generate the Daily Note if it does not exist following the Daily Note default settings.  At least, that would be really cool.  Thanks!

**Comment by mgmeyers** [comment]
This should be fixed now!
