### ISSUE TITLE
Error: I don't know how to interpret this line: kanban-plugin: basic

### ISSUE THREAD

**Issue by autonomygaps** [mgmeyers/obsidian-kanban#226]
I'm now getting suddenly getting this message:

> Something went wrong
> Error: I don't know how to interpret this line: kanban-plugin: basic
> You may wish to open as markdown and inspect or edit the file.
> Error: I don't know how to interpret this line:
> kanban-plugin: basic
> at fs.mdToBoard (eval at ‹anonymous> (app://obsidian.md/app.js:1:1199870), ‹anonymous>:53:2956)
> at qr. getParsedBoard (eval at <anonymous> (app://obsidian.md/app.js: 1:1199870), <anonymous>:121:97384)
> at qr. setViewData (eval at ‹anonymous> (app://obsidian.md/app.js:1:1199870), ‹anonymous>: 121:97541)
> at qr. t. setData (app://obsidian.md/app. js:1:976913)
> at qr.<anonymous> (app://obsidian.md/app. js:1:976821)
> at app://obsidian.md/app. js:1:120085
> at Object. next (app://obsidian.md/app. js:1:120190)
> at s (app: //obsidian.md/app. js:1:118929)

In addition, I'm unable to create a new kanban using the "Create New Kanban" command.  After I type the title, nothing happens when I press "Enter".

**Comment by samleibowitz** [comment]
@autonomygaps, I just had the same error today, and I think I might know the issue. After opening the kanban markdown in regular markdown editing mode, I noticed that  that a big portion of its content looked like it was copy-and-pasted at the end. A couple other documents I've looked at seem to have the same issue. So for example, in my main kanban board page I can see the following:

```
...(stuff deleted)...
- [ ] diagram new appointment workflow ---

kanban-plugin: basic

---

## Backlog
...(etc)...
```

I deleted the duplicated lines, and the page started working again. I'm wondering if this was a weird artifact of syncing my vault between my main laptop and an iPad.

**Comment by chuckthenerd** [comment]
@samleibowitz @autonomygaps  - I just started using Kanban plugin today - so beginner's opinion follows. 

when invoking the "Kanban: Toggle between kanban and markdown mode" to see the plain markdown...

I think the top of your file should (almost exclusively) have the following lines:

```
---

kanban-plugin: basic

---
```

that may be referred to as the YAML frontmatter in other discussion threads, and indicate that the page should be rendered as a kanban board.  The lines following the last set of hyphens would be the actual content that gets rendered.

**Comment by samleibowitz** [comment]
@chuckthenerd - yup, that's exactly what happened. Somehow most of the document got copy and pasted to the bottom, and then the plug in tried to parse the front matter in the middle of the file and threw up. I don't know how it got duplicated, but if I had to guess I'd say it was some kind of bug not related to the kanban plug in.

Or possibly me and @autonomygaps just happen to have fat fingers. :D

**Comment by autonomygaps** [comment]
PROBLEM IDENTIFIED:  The error message is generated whenever I add a three-dash line (`---`) while I'm in Markdown editing mode.  I often use a three-dash line to mark off a section (visible in Preview).

**Comment by chuckthenerd** [comment]
> PROBLEM IDENTIFIED: The error message is generated whenever I add a three-dash line (`---`) while I'm in Markdown editing mode. I often use a three-dash line to mark off a section (visible in Preview).

Seems like the three dashes can be dangerous for the kanban plugin at this point. Try using the HTML horizontal rule tag to separate your sections, <hr>

It works for me.

**Comment by mgmeyers** [comment]
Good detective work. In general, it's not currently a good idea to modify the markdown of the kanban files manually. In the future there will be better support for this, but the plugin currently relies on a a very strict structure.

**Comment by mgmeyers** [comment]
So, you can now add horizontal rules to cards, but it's still unwise to add them directly to the raw markdown. I'm going to close this issue for now, but I'll add this as a limitation in the documentation
