### ISSUE TITLE
Inclusion of hidden comments from markdown (%%)

### ISSUE THREAD

**Issue by chuckthenerd** [mgmeyers/obsidian-kanban#232]
This is probably a feature or enhancement request to allow markdown comments mentioned in 
https://help.obsidian.md/How+to/Format+your+notes#Comments

From the markdown rendered version of the kanban board, I added 

````
## list description

- [ ] card text %% hidden comment %% etc
- [ ] second card text 
%% 
hidden comment 
%% 
- [ ] third card text
````

result - attached screen capture image.
![Untitled](https://user-images.githubusercontent.com/3085716/125689536-b6a5da99-f378-4e67-ac5d-c149000864b6.png)

workaround - I'm not going to add the hidden Comment markdown characters %%

**Comment by mgmeyers** [comment]
You can now add comments to cards, but it'll still break if they're added to the markdown when viewing the board as markdown. That's not something that I'll be able to support when this ticket is complete: https://github.com/mgmeyers/obsidian-kanban/projects/1#card-62537891

Going to close this issue for now so I can keep track of everything in the above ticket!
