### ISSUE TITLE
[Bug] Linking to headers and paragraphs in other files doesn't work

### ISSUE THREAD

**Issue by Gentleman03** [mgmeyers/obsidian-kanban#233]
Hello, i found that linking with [[writing something then pressing # to link to header of some note (or to pparagraph)]] doesn't work. With normal md file you can type # and select header you want like here:
![obraz](https://user-images.githubusercontent.com/60824838/126082899-090d09b2-3d7c-4e8f-ba78-fa7584331480.png)

But in kanban cards you can only link to a file, and not to a header or paragraph in a file because after clicking # in [[ ]] it will automatically display available hashtags.

![obraz](https://user-images.githubusercontent.com/60824838/126082998-c5f9c921-9deb-4c7f-8925-f586fd44fecc.png)
![obraz](https://user-images.githubusercontent.com/60824838/126083025-903ae430-c24d-4a33-995f-cbc7cd5d44e8.png)

Hope that this behaviour could be fixed because its very useful to link cards with certain content inside other files.

**Comment by mgmeyers** [comment]
@Gentleman03 You can now search a file's headings. You can't search all headings across all files, but besides that, it would work similarly to obsidian's built in heading search. Let me know if you run into any issues with it.

<img width="285" alt="Screen Shot 2021-09-19 at 1 38 28 PM" src="https://user-images.githubusercontent.com/2694747/133942294-115788d5-47c8-4d24-8c06-081160cb6780.png">
