### ISSUE TITLE
Archive completed cards in active board command not working

### ISSUE THREAD

**Issue by Lorena1908** [mgmeyers/obsidian-kanban#234]
When I try to archive all completed cards from a board it seems to work properly  at first, but once I leave the board and go back they are back as if they were never archived. I also noticed that if I archive them and after that create a new card on the column the cards were archived, they are actually archived.

**Comment by mgmeyers** [comment]
@Lorena1908 This should be fixed now. Low me know if you still have issues with it!

**Comment by skillhacker-code** [comment]
I have the same issue ,

I am using the latest version of Kanban plugin

**Comment by mgmeyers** [comment]
Ok, I broke it again with another update. Should be fixed for real now.
