### ISSUE TITLE
Full list of #tags

### ISSUE THREAD

**Issue by dariuszkowalski-com** [mgmeyers/obsidian-kanban#236]
I use tags a lot. In tags I am using emoji. I have problem with add tags to kanban cards because I see only a few of them on the autocomplete list. I need to go to *Open as a markdown*  and manualy add each tag 

Example autocomplete:
![image](https://user-images.githubusercontent.com/37656900/126876993-d533a67c-c667-4620-9c85-12815dc66d98.png)

Total list of tags:
![image](https://user-images.githubusercontent.com/37656900/126877021-9fe9d44c-c5be-4428-a5e3-68c94e5766bb.png)

**Comment by mgmeyers** [comment]
@dariuszkowalski-com The issue here is that the maximum tags that were displayed in the dropdown was set to 10. I've bumped this up to 50, but it still won't show all of them. This is intentional, as there can be thousands of tags. The list will offer more targets suggestions as you type, however.
