### ISSUE TITLE
Visual artifacts + CSS oddities introduced with Markdown support

### ISSUE THREAD

**Issue by DaveyUS** [mgmeyers/obsidian-kanban#24]
This is a minor issue and might be unavoidable, but I figured I 'd let you know. When rearranging items there is a somewhat jarring flickering that happens. I don't recall seeing this before markdown was introduced.

![ghosting](https://user-images.githubusercontent.com/53842399/115979459-ded32d80-a53a-11eb-8286-2cd65e2755c3.gif)

Also, since adding markdown, kanban seems to utilize obsidian general css, specifically paragraph css (which makes sense). My margin-block-start and end were too extreme for kanban and it made the blocks way too tall. I manually added this snippet to shorten them:

`.kanban-plugin p{
	margin-block-start: 5px !important;
	margin-block-end: 5px !important;
}`

... which worked like a charm, except now when I drag an item I get strange behavior where the title shifts down. 

![css](https://user-images.githubusercontent.com/53842399/115979669-0c6ca680-a53c-11eb-8ec9-44ed542fb737.gif)

I cannot figure out the problem via inspector and I suspect other people will run into this issue. Am I doing something wrong here, or is a fix needed at the base level to solve for people's paragraph css conflicting with kanban css?

**Comment by mgmeyers** [comment]
Thanks @DaveyUS I think I figured out what was going on for your first issue. Update the plugin and let me know if you still see the flickering.

For you second issue, there's a technical reason for this. When an item or lane is dragged, it becomes a child of the `body` element and is no longer under `.kanban-plugin`. Kinda lame, but a necessary technical limitation.

You should be able to get your css working like so:

```
.kanban-plugin__item-markdown p { margin-block-start: 5px !important; margin-block-end: 5px !important; }
```

Let me know if you still have issues!

**Comment by DaveyUS** [comment]
Fixed and fixed. You rock!
