### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by lucasfilicio** [mgmeyers/obsidian-kanban#245]
Hi, I'm new here and I'm having problems, there's this code for a file converter, but I have no idea how to use it.

**Comment by mgmeyers** [comment]
One option is to right click on a folder and click "New Kanban Board"

<img width="317" alt="Screen Shot 2021-08-03 at 5 55 06 PM" src="https://user-images.githubusercontent.com/2694747/128104830-6542b411-ff47-4fce-b044-6203913f8bcb.png">

Or you can create a new board, or convert an empty note to a kanban board from the command pallet: 

<img width="717" alt="Screen Shot 2021-08-03 at 5 56 19 PM" src="https://user-images.githubusercontent.com/2694747/128104915-b001a5c4-81f0-4085-b453-a9a8ff4e4be6.png">


From there you can add lists and cards to the board.

**Comment by lucasfilicio** [comment]
I'm not able to run the code, use intellij or by command line?
I managed to clone the repository, yarn and npm install, but the error occurred when running ''node main.js'' -> internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'C:\Users\lucas\Desktop\obsidian-kanban-main\src\main.js'
←[90m at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m
←[90m at internal/main/run_main_module.js:17:47←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: []
}

**Comment by mgmeyers** [comment]
Are you trying to modify the code of the plugin, or use the plugin within obsidian? If it's the latter, you can install the plugin from the community plugin marketplace.

<img width="1023" alt="Screen Shot 2021-08-03 at 6 19 19 PM" src="https://user-images.githubusercontent.com/2694747/128106743-5df86b51-c8da-45ad-b4e5-69985d14de59.png">
