### ISSUE TITLE
Optimize for obsidian mobile

### ISSUE THREAD

**Issue by silic0n64** [mgmeyers/obsidian-kanban#249]
The plugin doesn't interact well in obsidian mobile. For example, it's really difficult to move a card from one group to another in mobile. I think it has to do something with the css.

**Comment by OfficerHalf** [comment]
A low effort version would just add "move card left" and "move card right" options in the context menu, but more fully featured mobile support would be great.

**Comment by mgmeyers** [comment]
The kanban plugin should work much better on mobile now. Feel free to open a new issue with any mobile related bugs!
