### ISSUE TITLE
[BUG] If I wanted to input #tag, and I had to input it twice to escape the auto-completion

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-kanban#25]
https://user-images.githubusercontent.com/13215013/115979843-dfaba400-a5ba-11eb-8eeb-1a7fdaced1a7.mp4

Here you are

**Comment by mgmeyers** [comment]
Thanks, @Quorafind , can you update the plugin and see if this is still an issue for you?

**Comment by Quorafind** [comment]
@mgmeyers It has been fixed, thanks.
