### ISSUE TITLE
Idea for improving usability with lots of cards in a column

### ISSUE THREAD

**Issue by erikwestra** [mgmeyers/obsidian-kanban#250]
Hi @mgmeyers,

I've been using your Kanban plugin, but had to move away from it because it was so unwieldy to move items between lists when there were lots of items in a column -- if I had a "To-Do" column with, say, 50 cards in it, and I wanted to drag one of the cards near the bottom to an adjacent column (say, "To-Do Today") with only 2 cards in it, I would have to drag the card to the right, and then drag up to scroll the entire window back to where the "To-Do Today" column was visible so the card can be moved into that column.

I was just playing with Trello for tracking my initiatives at work, and I realised that Trello do something really clever here to make dragging items between lists less painful.  When a column in Trello contains more cards than can be shown on the screen, rather than making the whole Kanbard board scroll up and down, they keep the column at the height of the visible portion of the window, and add a scroller within that column to scroll through the cards.  This means all the columns are always visible, and dragging cards between columns is quick and easy.

Hopefully the above description makes sense -- if not, let me know and I'll record a video showing the difference and share it with you.

It would be *fantastic* if you could do something like this -- at the moment, the Kanban plugin works well if you don't have too many cards, but once you get lots of cards in a column it becomes really slow and klunky to move cards between columns.

 - Erik.

**Comment by mgmeyers** [comment]
@erikwestra Version 1.0.0 of this plugin has been released and adds scrollable columns!
