### ISSUE TITLE
[FR] Put the added card at the top of the list

### ISSUE THREAD

**Issue by Borber** [mgmeyers/obsidian-kanban#254]
Like this, and with the newly added task at the top

![image](https://user-images.githubusercontent.com/30563826/130046652-2340bb6d-1021-4deb-8d23-4a93b5dcecf9.png)

**Comment by DaveyUS** [comment]
This issue has been made more important with the release of the new beta. (flippin' nice job on that by the way @mgmeyers) 

When a lane has an overflow of cards, adding a card will place it hidden at the bottom of the lane without indication. I'd propose a small '+' icon next to the lane settings button on each lane which would add to the very top. Better yet having a "Add Card Below" item in each card options menu would be clutch. 

Thanks for all your hard work!

**Comment by mgmeyers** [comment]
@DaveyUS Check the setting the beta!

<img width="884" alt="Screen Shot 2021-08-28 at 4 46 25 PM" src="https://user-images.githubusercontent.com/2694747/131233679-c156528f-0627-4eba-83d2-a882ed1735c5.png">

This will also change the position of the input.

**Comment by Borber** [comment]
> @DaveyUS Check the settings in the beta!
> 
> <img alt="Screen Shot 2021-08-28 at 4 46 25 PM" width="884" src="https://user-images.githubusercontent.com/2694747/131233679-c156528f-0627-4eba-83d2-a882ed1735c5.png">
> 
> This will also change the position of the input.
> 
> Edit: Although, in theory any newly added cards should be scrolled into view

Thank you so much, kanban is my favourite plugin!

**Comment by DaveyUS** [comment]
> @DaveyUS Check the settings in the beta!

I'm a Derp. That works! I think I'd prefer the "Add a card" button stay out of the way at the bottom no matter what, or make it a small icon next to the lane options, but I understand why you made it the way you did.

**Comment by mgmeyers** [comment]
1.0.0 has been released, and this is now possible!
