### ISSUE TITLE
[Feature]: Insert template when clicking on unresolved links

### ISSUE THREAD

**Issue by cjaguilera** [mgmeyers/obsidian-kanban#257]
when i create a note from a kanban card it pastes the template and erased it immediately.

**Comment by sammy8146** [comment]
I have a similar issue.
Steps to recreate:
1/ define `NewProjectTemplate` using Templater syntax
2/ designate `NewProjectTemplate` as `Note Template` in the config panel
3/ designate `Note Folder` = `!Projects` in config panel
4/ Create new card on kanban board as `[[MyNewProject|My New Project]]` (note the inline naking alias)
5/ CMD-click the note title to create a new note as `MyNewProject`
6/ EXPECT to see `!Projects/MyNewProject.md` with `NewProjectTempalte` content as template AND Templater functions rendered
7/ INSTEAD see new note `MyNewProject.md` obeying the Templater rules - created in `!Inbox/` WITH `NewNoteTemplate` contents rendered properly.

I can't find reference whether Kanban.plugin works with Templater.plugin, so this might be PEBCAK. Sorry if I'm expecting the wrong things here. :-)

**Comment by mgmeyers** [comment]
@cjaguilera Can you test templates again? I fixed a bug, and templates seem to work fine now.

@sammy8146 I believe this is a separate issue. The note template is only used with selecting "New note from card" from a card's menu. The plugin will use the default obsidian behavior when clicking through unresolved links.

**Comment by sammy8146** [comment]
ok, that's sort of what I thought. Thanks for confirming!
