### ISSUE TITLE
Linked Page Metadata is not displayed with Markdown links

### ISSUE THREAD

**Issue by ddeighton** [mgmeyers/obsidian-kanban#259]
In a kanban card, I linked to a note using markdown links and the metadata was not displayed. I changed this to use Wikilinks and the metadata is now displayed. Is it possible to have the metadata displayed regardless of the link type used?

**Comment by sammy8146** [comment]
I _think_ I have the same issue.

Step to recreate:
1/ in config panel, define `metadata key` = `OFLink` WITH `field contains markdown` = ON
2/ create new card in kanban board as `[[!Projects/MyNewProject|My New Project]]` (note the inline display alias)
3/ CMD click the new card title to create the linked note
4/ in YAML frontmatter, create `OFLink: [Tasks](omnifocus:///xxxxx)`
5/ ALL displayed metadata keys in kanban card disappear upon completion of /4/
6/ change /4/ to `OFLink: omnifocus:///xxx`
7/ ALL displayed metadata keys return, with `OFLink` displaying properly as text AND un-clickable
8/ metadata for that card only disappears, not ALL cards on the kanban board
9/ tried with default CSS theme trying to rule out CSS collision

Obsidian v0.12.15, installer v0.12.3
Kanban 0.5.15
uninstalled/reinstalled Kanban plugin as a troubleshooting step

**Comment by mgmeyers** [comment]
The kanban plugin will now respect Obsidian's "Use [[Wikilinks]]" setting. If it's turned off, plain markdown links will be correctly detected.
