### ISSUE TITLE
Click on internal link trigger "app to open link" 

### ISSUE THREAD

**Issue by trungng2006** [mgmeyers/obsidian-kanban#26]
When i click on the internal link, the link does open in new pane, however, it also trigger the "app to open link" in win10:
![image](https://user-images.githubusercontent.com/71961905/115979794-8cd1ec80-a5ba-11eb-9929-db8c605902c4.png)

**Comment by DaveyUS** [comment]
+1 also experiencing this

**Comment by Ravenclawer** [comment]
I have also experienced this issue when I open wikilink in a kanban board and the pop-up window is quite different, but I think it's the same problem.
![image](https://user-images.githubusercontent.com/73892411/115990681-1b645f00-a5f7-11eb-82a0-2eb446c1acf3.png)

**Comment by mgmeyers** [comment]
Thanks for the report. This should hopefully be fixed. Please update and let me know if you still have issues.

**Comment by DaveyUS** [comment]
Fixed it for me!

**Comment by Ravenclawer** [comment]
it fixed for me after the update 0.0.10, thank you very much
