### ISSUE TITLE
Not auto saving board on mobile

### ISSUE THREAD

**Issue by OwnJoke** [mgmeyers/obsidian-kanban#266]
On mobile, when editing a board (ex: adding a card). It does not save the changes unless you manually save the file.

**Comment by OwnJoke** [comment]
Not sure if this is because I sync my files, but the bug only happens when not connected to the internet.

**Comment by saty101** [comment]
The kanban board doesn't show up on my mobile app even when I save the file. I have to manually create another file in mobile app even though I use syncthing.

**Comment by mgmeyers** [comment]
@OwnJoke This should be fixed now. Let me know if you still have trouble on mobile

**Comment by saty101** [comment]
The sync is working properly now. Cheers!
