### ISSUE TITLE
Can someone guide me how to use "Linked Page Metadata", please?

### ISSUE THREAD

**Issue by namnppd01894** [mgmeyers/obsidian-kanban#268]
I'm new, so can someone guide me how to use "Linked Page Metadata", please? And what is it for? Sorry for my bad English

**Comment by mgmeyers** [comment]
@namnppd01894 I've recently added some documentation on this setting: http://matthewmeye.rs/obsidian-kanban/Settings/Linked%20page%20metadata/

Let me know if this helps!
