### ISSUE TITLE
[REQUEST] Full documentation

### ISSUE THREAD

**Issue by firinael** [mgmeyers/obsidian-kanban#271]
Hi! Your plugin is becoming quite feature-rich and complex, it'd be very nice if it had a full documentation page with all the kinds of syntax it accepts, how to handle different purposes, how CSS styling works, etc.

For example, I wanted to know if it was possible to do something with templates for Kanban or if it had something already built-in to handle templates, but I had to scour through the project issues and discussions to find out that there isn't.

**Comment by mgmeyers** [comment]
Thanks for the suggestion @firinael. I've added more complete documentation here: http://matthewmeye.rs/obsidian-kanban/

This is still a WIP, but I'll be fleshing it out over time. Let me know, though, if you see anything missing.
