### ISSUE TITLE
[QoL REQUEST] Automatically open and focus `+ Add a card`  box when creating a new list

### ISSUE THREAD

**Issue by firinael** [mgmeyers/obsidian-kanban#273]
Just for QoL. Seems like pretty default behaviour to save the user some small hassle.

**Comment by mgmeyers** [comment]
@firinael The new version of the kanban plugin changes the add list form so it's now more out of the way. I'm curious what your thoughts are on this feature request considering the new UI.

**Comment by firinael** [comment]
Taking the UI changes into account, this is now obsolete, I believe.

The focus remains on the list box (which remains open now), and that clearly enables you to make more lists in succession. 

The issue was that the box was closed, and the cursor went nowhere, so there's no issue any more!
