### ISSUE TITLE
Bug: Cannot scroll with middle click + drag

### ISSUE THREAD

**Issue by phibr0** [mgmeyers/obsidian-kanban#275]
Normally if you middle click in a scrollable container you can scroll by just moving your mouse up and down. This doesn't work in a Kanban Board unfortunately.

Tested with the latest Release Candiate (3)

**Comment by mgmeyers** [comment]
@phibr0 This should be possible now. I don't have a way to test it out though. Could you let me know if it's not working still?

**Comment by phibr0** [comment]
Its working! Thank you
