### ISSUE TITLE
[Bug]: Autocomplete inserts at the end and not at cursor position

### ISSUE THREAD

**Issue by geoffreysflaminglasersword** [mgmeyers/obsidian-kanban#278]
### Describe the bug

This bug is very minor, but autocompletion in some circumstances will insert text at the end of the content rather than at the cursor

### Expected Behavior

Text should be inserted at the @ symbol

### Steps to reproduce

*When* editing a card that already has a date and time:
- select and delete the date (leaving the time and any other content)
- type @ 
- hit 'enter' to select the first suggestion

*Then* the suggestion is inserted at the end of the card content rather than after the @ symbol

### Operating system

Windows

**Comment by mgmeyers** [comment]
@geoffreysflaminglasersword This should be fixed now!
