### ISSUE TITLE
Edit Button vanishes, when the content is too long

### ISSUE THREAD

**Issue by Braweria** [mgmeyers/obsidian-kanban#28]
What I want:  
To write long content for a task and be able to edit it.

What I got:  
Long content with no edit button.  

Presentation:  
![lmao](https://user-images.githubusercontent.com/62669899/115993976-6b322e80-a5d5-11eb-93f3-1edd48540788.gif)

**Comment by mgmeyers** [comment]
Hey @Braweria I've made some CSS updates that will force the card to scroll horizontally on long words. Not the most elegant solution, but hopefully it'll work for now. Let me know if you still have issues.

**Comment by Braweria** [comment]
Why not wordbreak?

**Comment by Braweria** [comment]
```css
word-break: break-all;
```
Will look like this
![lmao](https://user-images.githubusercontent.com/62669899/116041534-99634d00-a66d-11eb-83f9-51be593cc5f8.gif)

**Comment by mgmeyers** [comment]
@Braweria This should no longer be an issue! long words will wrap as you suggested
