### ISSUE TITLE
[Bug]: The Kanban plugin cannot be activated in the mobile version (Version 1.0)

### ISSUE THREAD

**Issue by vorinstanz** [mgmeyers/obsidian-kanban#281]
### Describe the bug

The installation is carried out successfully, but the plugin cannot be activated. Error message: "Failed to load plugin obsidian-kanban."

### Expected Behavior

Can also be used mobile.

### Steps to reproduce

The error also occurs when reinstalling the Obsidian app.

### Operating system

Android

**Comment by MosheSteinberg** [comment]
For what it is worth, I have the same issue on my android

**Comment by rogercavanagh** [comment]
I have the same issue running iPadOS 14.7.1. Same behaviour plug installs successfully, but fails to load.

**Comment by vorinstanz** [comment]
Also version 1.0.1. does not fix the problem.

**Comment by vorinstanz** [comment]
Thank you for your work. But unfortunately, 1.0.3 doesn't solve the problem for me (Android).

**Comment by mgmeyers** [comment]
So, as of 1.0.4, the plugin should install and enable correctly. There are still a lot of mobile issues (as there was before) but those will take me some time to hammer out.

**Comment by mgmeyers** [comment]
As of 1.0.6, mobile support has been greatly improved. There are still some issues, but it should be much more usable.

**Comment by MosheSteinberg** [comment]
Working for me now, so from the android side, this issue can be closed.
