### ISSUE TITLE
[Bug]: The page does not enter & cards misaligned

### ISSUE THREAD

**Issue by Jacobxz** [mgmeyers/obsidian-kanban#284]
![image](https://user-images.githubusercontent.com/48195963/132976501-07749947-ca32-487d-a28a-4fb950b75f32.png)

**Comment by Jacobxz** [comment]
When the column is full, it will be misaligned
![image](https://user-images.githubusercontent.com/48195963/132978257-58da7db4-e53d-4e81-aa1b-dcc58c6b3c2c.png)

**Comment by mgmeyers** [comment]
@Jacobxz I'm not quite sure what's happening here, but it may be an issue with the theme you're using. Does it do this same thing using the default theme?

**Comment by Jacobxz** [comment]
It's my theme, but under the default theme, if the card is a “[[ ]]”page, it still can't be clicked.



---Original---
From: "Matthew ***@***.***&gt;
Date: Mon, Sep 13, 2021 00:22 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [mgmeyers/obsidian-kanban] [Bug]: The page does not enter &amp; cards misaligned (#284)




 
@Jacobxz I'm not quite sure what's happening here, but it may be an issue with the theme you're using. Does it do this same thing using the default theme?
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
