### ISSUE TITLE
[Bug]: Clicking links on cards does not open the note

### ISSUE THREAD

**Issue by MosheSteinberg** [mgmeyers/obsidian-kanban#285]
### Describe the bug

I have a link in one of my cards and clicking it does not open the note. CTRL - Click doesn't work either

Note that:
1. Right clicking and selecting 'open in new pane' **does** work
2. Clicking links on mobile **does** work

### Expected Behavior

The note should open in the pane where the kanban board is when clicking and in a new pane when doing CTRL-click

### Steps to reproduce

1. Open any kanban board with plugin version 1.0.6
2. Put a wiki link in a new card
3. Click on it
4. Nothing happens

### Operating system

Windows

**Comment by vorinstanz** [comment]
Same problem here

**Comment by MosheSteinberg** [comment]
Presumably connected to this - double clicking on the card does not let me edit the card

**Comment by MosheSteinberg** [comment]
Can confirm this is fixed in 1.0.8
