### ISSUE TITLE
[Bug]: Dates don't work

### ISSUE THREAD

**Issue by ilkerduymaz** [mgmeyers/obsidian-kanban#286]
### Describe the bug

With the new update, I can't seem to add dates to my cards. When I try to add a date, the calendar pops out but the date I select is not displayed in the card. Also, my old kanban boards that had cards with dates throw this error:
![image](https://user-images.githubusercontent.com/82678515/132991184-09f661c3-9ff0-4a7a-8a91-0e8de06c2341.png)

### Steps to reproduce

a) Create a new kanban board and add a date from the right click menu. The date is not displayed on the card even though you can select a date from the calendar.

b) Open an old kanban board that contains dates with the updated version of kanban plugin.

### Operating system

Windows

**Comment by mgmeyers** [comment]
@ilkerduymaz It looks like this is a conflict with the Markdown Attributes plugin. I've submitted an issue with that plugin: https://github.com/valentine195/obsidian-markdown-attributes/issues/3

But for now, you can prevent this error by turning on this setting: 

<img width="678" alt="Screen Shot 2021-09-12 at 9 19 48 AM" src="https://user-images.githubusercontent.com/2694747/132995119-175fad77-9d1b-480a-ba0f-4959f0b545fa.png">

**Comment by ilkerduymaz** [comment]
Thanks!
