### ISSUE TITLE
[Bug]: Mobile/Android: moving cards is almost impossible

### ISSUE THREAD

**Issue by dafqs** [mgmeyers/obsidian-kanban#289]
### Describe the bug

Moving cards is impossible with all variants.

### Expected Behavior

Expected behavior:
Cards can be moved between the columns.

### Steps to reproduce

The error occurs with the different settings.

### Operating system

Android

**Comment by mgmeyers** [comment]
@dafqs Can you supply more detail here? What happens when you try to move a card? What makes it impossible to do so?

**Comment by dafqs** [comment]
Thanks for your reaction. When I touch the card, it is marked, but then cannot be moved (only a few millimeters).

**Comment by dafqs** [comment]
The problematic behavior:

https://user-images.githubusercontent.com/65040381/132997445-0899abb5-bf5e-4565-874f-834592f23664.mp4

**Comment by functionalStoic** [comment]
+1 to this behavior on Android (Google Pixel). In case it is helpful, the pop up menu (with card options) slides up from the bottom as well which seems like that might contribute

**Comment by mgmeyers** [comment]
Ok, I figured out what was going on here and it should be fixed in the latest version. Let me know if you still have issues.

**Comment by functionalStoic** [comment]
Thanks @mgmeyers. That did the trick! D&D works well now.
(Thanks for all your effort! 🙏)

**Comment by dafqs** [comment]
It works very well now. @mgmeyers Thanks for all your effort. Great commitment.
