### ISSUE TITLE
[Feature request] Japanese IME Support

### ISSUE THREAD

**Issue by yo-goto** [mgmeyers/obsidian-kanban#29]
Hi, @mgmeyers. Thank you for developing this kanban plugin. 

I have a feature request.
Typing Japanese sentences requires to convert characters and then confirm the input with IME. So, we have to push the Enter key twice. In the current version, we can't type full sentences and I found characters are duplicated automatically into the next kanban card.
![can't convert](https://user-images.githubusercontent.com/50942816/115994210-00064d80-a611-11eb-81b1-9aeb4ba70c4a.gif)

Reference: previous solved issue about IME. really similar
https://forum.obsidian.md/t/japanese-file-name-title-copied-to-a-note/8720?u=padaone

**Comment by mgmeyers** [comment]
Hey @yo-goto, can you update the plugin and test this out again? I added better IME support, but I'm not 100% sure I'm testing it correctly. Let me know if anything is still amiss.

**Comment by yo-goto** [comment]
I've tested.
It seems perfect! Thank you for making the patch so quickly.
If I find any bugs, I'll let you know.

**Comment by yo-goto** [comment]
Hi, @mgmeyers. [The latest version 0.5.2](https://github.com/mgmeyers/obsidian-kanban/releases/tag/0.5.2) seems to have this bug again. Please fix this issue.

**Comment by yo-goto** [comment]
![IME bug again](https://user-images.githubusercontent.com/50942816/120916890-41e1e380-c6e7-11eb-874d-325a82cc7ef5.gif)

**Comment by mgmeyers** [comment]
Apologies @yo-goto, this should be fixed now. Let me know if you still have issues with it.

**Comment by yo-goto** [comment]
Thanks! I've tested it now. Seems perfect.
