### ISSUE TITLE
[Feature]: Clicking on date creates new daily note using template.

### ISSUE THREAD

**Issue by dcoales** [mgmeyers/obsidian-kanban#291]
### Goal or desired outcome of this feature

I have the "link to daily note" option switched on for dates.  This works great if the daily note already exists but if it doesn't it just creates a new note in the default new note folder.  It would be great if it could create a new daily note in the daily notes folder using the specified template.

### Describe the feature

I add a date to my card and it is added in the following format @[[YYYY-MM-DD]].  If a daily note for this date does not exist then this plugin uses the built-in daily notes plugin to prompt the user to create the note which is then created in the daily notes folder based on the template specified in the daily notes config.

**Comment by mgmeyers** [comment]
@dcoales The default daily notes settings should be respected now. This includes both the "New file location" and "Template file location" settings. Let me know if you still have issues with this

**Comment by dcoales** [comment]
Brilliant thanks.  It works perfectly now.
