### ISSUE TITLE
[Bug]: Tab button is not working ,adding subtask is not working 

### ISSUE THREAD

**Issue by skillhacker-code** [mgmeyers/obsidian-kanban#293]
### Describe the bug

While writing notes inside i would like to add below some task or note . 

But TAB button is not working , intenting to a list is not working 

For eg i would like to write like this 

1.asjdflas
   1.sjlkdflasjkdf
   2.asdfjasldf

Thank you so much for providing markdown support inside kanban 

### Expected Behavior

Can't you TAB inside kanban

### Steps to reproduce

Create a card 
start typing
press tab button in keyboard
tab button will not work 

### Operating system

Windows

**Comment by mgmeyers** [comment]
@skillhacker-code I'm unable to reproduce this on mac. Tab seems to work fine. Let me get a windows virtual machine set up to see if it's a windows thing.

![Sep-15-2021 09-28-17](https://user-images.githubusercontent.com/2694747/133472639-69de59ae-4b14-45f1-b37e-cbc3bde7f07b.gif)

![Sep-15-2021 09-31-11](https://user-images.githubusercontent.com/2694747/133473006-77107269-dc08-4d2a-a333-64bb3c3558ef.gif)

**Comment by functionalStoic** [comment]
Hi @mgmeyers / @skillhacker-code,
I noticed this issue as well (on a Mac). I suspected it might have something to do with the Outliner plugin.
After disabling the Outliner plugin, tab now worked as expected.

Curious if either of you have that plugin @skillhacker-code enabled.

Hope that helps a bit!

**Comment by skillhacker-code** [comment]
@mgmeyers @functionalStoic  , It is now working when outliner plugin is disabled , I think it is the problem with outliner plugin . 

Thank you so much @functionalStoic and @mgmeyers
