### ISSUE TITLE
[Feature]: Quick access to original note from embed via click or menu.

### ISSUE THREAD

**Issue by jowibou** [mgmeyers/obsidian-kanban#294]
### Goal or desired outcome of this feature

A quick way to open an embedded note.

### Describe the feature

Having the option to click either on an embed, on a link icon in the embed or on an "open in new pane" drop down menu to get to the original Note/Section/Block for editing purposes.

### Can you think of any alternatives or work-arounds?

Being able to edit the card and command/control click on the link would be a start.

**Comment by mgmeyers** [comment]
I've added a link icon that allows access to the source of an embed.
