### ISSUE TITLE
[Feature]: css for unresolved links

### ISSUE THREAD

**Issue by jowibou** [mgmeyers/obsidian-kanban#295]
### Goal or desired outcome of this feature

Distinguishing unresolved links via css.

### Describe the feature

It would be great to be able to identify unresolved links in cards. I use a css snippet for this normally, but the style (which prepends "▶︎" to the link) doesn't show up. The css for the plugin has no line breaks and is thus incomprehensible - to me at any rate.)

### Can you think of any alternatives or work-arounds?

Letting us know how to do this with a snippet, or making the plugin css more accessible.

**Comment by mgmeyers** [comment]
@jowibou Unresolved links will now get the `.is-unresolved` class like they do in preview.

**Comment by jowibou** [comment]
Thanks for doing this. Though it's not quite there yet. Now my _resolved_ links to sections show up with unresolved styling, even though the card exists and embeds, links and popups work as expected.
