### ISSUE TITLE
[Bug]: Plugin specific documentation links within Obsidian not resolving to external documentation source

### ISSUE THREAD

**Issue by matthewfduffy** [mgmeyers/obsidian-kanban#298]
### Describe the bug

Attempting to navigate to plugin documentation from within Obsidian Editor and external links are not resolving.

Tech Specs...
Windows 10 Pro
Obsidian v.0.12.15
Kanban v.1.0.15
Firefox v.92.0

### Expected Behavior

User should be redirected to external documentation hosted at http://matthewmeye.rs/obsidian-kanban/<sub-page>

**Actual Result:**
A new link opens in browser with 404 error or skewed layout (see screenshot)

_Note:_
It appears the link is resolving to the correct url but is prepended to '.md' ending in the browser.
(i.e. http://matthewmeye.rs/obsidian-kanban/How%20do%20I/Create%20a%20Kanban%20board**.md**)

Manually, removing '.md' in the url seems to resolve the issue.
It's possible that some browsers are parsing the links and detecting conflicting domains (.rs and .md)

![obsidian-kanban-external-links-2](https://user-images.githubusercontent.com/10624656/133695399-985eecbc-bcca-49ca-a257-0204e72ef00d.png)

### Steps to reproduce

_Within Obsidian:_
1. Open Settings
2. Click on 'Community Plugins' under 'Options'
3. Click on 'Kanban' (redirects to community plugin feature page)

_On Community Plugin feature page:_
1. Click on any external link (e.g. - How Do I > Create a Kanban board)

![obsidian-kanban-external-links-1](https://user-images.githubusercontent.com/10624656/133695459-b6a567f7-d117-45ec-a020-d95a55c5c0c6.png)

### Operating system

Windows

**Comment by mgmeyers** [comment]
Thanks @matthewfduffy, this should be fixed now.
