### ISSUE TITLE
Archive Completed Cards Not Working

### ISSUE THREAD

**Issue by FrocketGaming** [mgmeyers/obsidian-kanban#299]
Good day!

Thank you for a wonderful plugin, I use it daily but it appears the Kanban: Archive completed cards in active board command does not work. I have tried it various times with different items having checkmarks on them and nothing occurs. Am I missing something or is this a bug?

**Comment by mgmeyers** [comment]
@FrocketGaming This should be fixed as of yesterday. Try updating the plugin and see if that fixes the issue.

**Comment by FrocketGaming** [comment]
> @FrocketGaming This should be fixed as of yesterday. Try updating the plugin and see if that fixes the issue.

Ah, that did it. Thanks so much for your work!
