### ISSUE TITLE
Feature Request: Page links in card titles

### ISSUE THREAD

**Issue by bobbleheadjoe** [mgmeyers/obsidian-kanban#3]
Desired workflow: use a kanban board view to manage writing process for articles. Since I do my writing in Obsidian, it would be great to be able to use the [[pagetitle]] formatting when creating cards.

**Comment by DaveyUS** [comment]
@bobbleheadjoe I think this request includes the functionality that I'd love to see implemented, but I just want to clarify in case I need to open another issue. 

When you say "use the [[pagetitle]] formatting when creating cards", do you mean have the ability to link to separate notes as a  kanban card? For example, say you are writing an article about Ethereum's upcoming switch to Proof Of Stake, and you start a note titled "Ethereum PoS". You could then create a kanban card with the title as [[Ethereum PoS]], and the card would now allow you to click it to open that note.

As I'm writing this, I'm realizing it would also be awesome if the Kanban could tell if the [[pagetitle]] hasn't been created yet, and would create and open the note for you upon clicking.

**Comment by bobbleheadjoe** [comment]
@DaveyUS yes, exactly. My use case is that I want to track the status of articles that I'm writing, and I'd like to be able to click on the card titles to go straight to the note. Currently, I'm using boards in Todoist and using the Todoist plugin to display active articles that are in a specific column on my main "Articles" page. I found that by using double brackets in the Todoist titles, the plugin renders that as a Markdown link to the specific page. I'd like the same thing to happen in this kanban plugin (which would eliminate the need for Todoist for me!). But currently, if you use double brackets in a card, it just shows double brackets in the text for the card when in Kanban view.

**Comment by mgmeyers** [comment]
So this is doable now with markdown support and link autocomplete!

![card links](https://user-images.githubusercontent.com/2694747/115974979-bbe25280-a515-11eb-8f33-b4e3eb5b7dc2.gif)

There's more to expand on here, but let me know if there's more to your feature request that is missing.

**Comment by bobbleheadjoe** [comment]
@mgmeyers beautiful! Exactly what I was looking for :)

**Comment by DaveyUS** [comment]
Beautifully implemented!
