### ISSUE TITLE
[Bug]: Adding blank list can cause error in markdown file

### ISSUE THREAD

**Issue by sntrenter** [mgmeyers/obsidian-kanban#300]
### Describe the bug

when you add a list you are not required to ender any text, doing so will cause an error.

### Expected Behavior

You should be required to enter some text or temporary text should be provided for a new list. 

### Steps to reproduce

1. in mobile go to a kanban board 
2. add a list
3. give the list no name
4. close and reopen the file
5. the file should throw an error stating "Error: I don't know how to interpret this line: ##"

### Relevant errors (if available)

```shell
"Error: I don't know how to interpret this line: ##"
```

### Operating system

iOS

**Comment by mgmeyers** [comment]
@sntrenter This should be fixed now!
