### ISSUE TITLE
[Bug]: Cant Embed Kanban in page that  already have some text

### ISSUE THREAD

**Issue by skillhacker-code** [mgmeyers/obsidian-kanban#304]
### Describe the bug

I saw in the backlog that features to embed kanban in a page is already done.

But I can't do that, 

Are there any hidden ways to do that?

### Steps to reproduce

Open a page with some text written 

Then try creating a kanban board inside that 

### Operating system

Windows

**Comment by mgmeyers** [comment]
@skillhacker-code You can't yet embed a board in another page, but you can embed other pages within a kanban card.

There's another feature request for what you're asking here #4 . Going to close this, but feel free to comment on this other issue!
