### ISSUE TITLE
[Bug]: link to heading is rendered as non existed note

### ISSUE THREAD

**Issue by jokysatria** [mgmeyers/obsidian-kanban#305]
### Describe the bug

In version 1.0.16, the link to heading is rendered as non-existed note (while it's exist).

![image](https://user-images.githubusercontent.com/69371378/133928683-a355bfa1-7bdb-470f-8e7f-b4536cf5cd0f.png)
![image](https://user-images.githubusercontent.com/69371378/133928792-e9f07319-84b5-4fc0-92c9-3420baac0520.png)

### Expected Behavior

they should rendered normally as existed note.

### Steps to reproduce

make any link to heading in kanban card.

### Operating system

Windows

**Comment by mgmeyers** [comment]
@jokysatria This should be fixed now. Let me know if you still encounter issues with it!
