### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by ryadaj** [mgmeyers/obsidian-kanban#306]
Thanks for your amazing work on this.

Minor point but "weather" should be "whether"

![Screen Shot 2021-09-19 at 17 29 01](https://user-images.githubusercontent.com/82765301/133943599-763e1d4c-bb3d-4ac7-a61b-de76075d252f.png)

**Comment by mgmeyers** [comment]
Thanks for spotting this @ryadaj. Should be fixed.
