### ISSUE TITLE
Feature Request: drag and drop items between different kanbans

### ISSUE THREAD

**Issue by Shuusei04** [mgmeyers/obsidian-kanban#31]
I think it would be more convenient for users to deal with different projects containing the same task.

**Comment by Quorafind** [comment]
I do need this too, and if this works correctly, it could be a way to achieve CARD WRITHING like image below.

![看板卡片式笔记-1](https://user-images.githubusercontent.com/13215013/119084990-65453700-ba35-11eb-92ab-9d0595d38cf8.png)

**Comment by pjeby** [comment]
Drag between boards has been implemented and is now available in 0.5.0
