### ISSUE TITLE
[Feature]: Option to append completion/archive date instead of prepending the date.

### ISSUE THREAD

**Issue by ddeighton** [mgmeyers/obsidian-kanban#310]
### Goal or desired outcome of this feature

I use the [tasks plugin](https://github.com/schemar/obsidian-tasks).  I would like to be able to mark items as complete in a kanban board and have a "done on <date>" tasks query display what was completed.

### Describe the feature

I would like to have an option to append the date, rather than prepend it, when items are archived (or completed as per #309).

By adding  ✅ as the date/time separator, then appending the date, tasks will show up with a tasks query, such as:

```
    ```tasks
    done on 2021-09-21
    ```   
```

### Can you think of any alternatives or work-arounds?

Nothing that I can find.

### Screenshots, mockups, or videos

_No response_

**Comment by RCheesley** [comment]
+1 from me, I am hacking around this using dataview and setting a completed: date
```
> ```dataview
> TASK FROM "" 
> WHERE created = date(today)
> ```
```
And to show completed that day I use:

```
> ```dataview
> TASK FROM "" 
> WHERE completion = date(today)
> ```
```
I have to manually set those dates on the card when I create / mark done which is a bit of a pain.

**Comment by vcurdia** [comment]
Unfortunately I don't think that this addressed the issue properly. It's only for archived items, not for "done/completed" items.

It's a lot more useful to have a done date, than an archived date. Most of the time I like to still see the most recently completed tasks and know when I completed them. But I don't particularly care to know when I archive them, which simply removes them from the board.

Are there any plans to add completion date to card?

Thanks!
