### ISSUE TITLE
[Bug]: Note folder setting drop down not displaying

### ISSUE THREAD

**Issue by nybbles** [mgmeyers/obsidian-kanban#313]
### Describe the bug

See the right side of the screenshot below. The dropdown search box for setting the note folder looks broken and does nothing when I click on it.

![Screen Shot 2021-09-23 at 4 56 32 PM](https://user-images.githubusercontent.com/421369/134598671-65ae2404-cd12-4cd6-96b4-6247afb19008.png)

### Expected Behavior

It should work as before, i.e. similarly to the Note template dropdown box.

### Steps to reproduce

This problem seems to only happen on board-specific settings (the plugin-level settings panel seems to work fine).

1. Open board-specific settings page (I tried two different ones).
2. Observe that the Note folder setting dropdown box does not work.

I'm running Mac OS.

### Relevant errors (if available)

```shell
VM104:6 Uncaught TypeError: Cannot read property 'placeholder' of undefined
    at eval (eval at <anonymous> (app.js:1), <anonymous>:6:2872)
    at Array.forEach (<anonymous>)
    at e.update (eval at <anonymous> (app.js:1), <anonymous>:6:2701)
    at eval (eval at <anonymous> (app.js:1), <anonymous>:93:12392)
eval @ VM104:6
e.update @ VM104:6
eval @ VM104:93
setTimeout (async)
eval @ VM104:93
window.createEl @ app.js:1
Node.createEl @ app.js:1
eval @ VM104:93
e.then @ app.js:1
constructUI @ VM104:93
onOpen @ VM104:93
e.open @ app.js:1
eval @ VM104:93
e.handleEvent @ app.js:1
```

### Operating system

macOS

**Comment by mgmeyers** [comment]
@nybbles I'm unable to reproduce this error. Could you try updating the plugin and see if this still happens for you?

**Comment by nybbles** [comment]
thanks, I just updated and this error no longer occurs for me. 🙏

**Comment by nybbles** [comment]
hm strange i am getting this error again. I don't think I changed anything after I was unable to reproduce it in my last comment.

**Comment by nybbles** [comment]
Okay I uninstalled, reinstalled and it seems to be displaying fine. 🤷‍♂️
