### ISSUE TITLE
[Feature Request]: Add audio file to a card

### ISSUE THREAD

**Issue by bitzky** [mgmeyers/obsidian-kanban#314]
### Goal or desired outcome of this feature

I would love to add audio files to a card it the same way I can add an image.

### Describe the feature

Adding and audio file to a card with ![[Audio.mp3]] would display a little player in the card, with a play button and a timeline, like in the picture. The volume button would be less important because of the space limitation.

### Screenshots, mockups, or videos

<img width="668" alt="image" src="https://user-images.githubusercontent.com/8150506/134804965-6cd000a8-971b-4f48-b310-254b3196f0d1.png">

**Comment by mgmeyers** [comment]
@bitzky This should already be possible:

<img width="250" alt="Screen Shot 2021-09-26 at 2 59 29 PM" src="https://user-images.githubusercontent.com/2694747/134825581-ce29e9a2-aca6-4a16-a9a2-d7126b4ed13c.png">

Let me know if this is not the case for you.

**Comment by bitzky** [comment]
thank you Matthew! I tried it again and it worked indeed!

But only when the file is already in Obsidian.

It would be really cool if I could drag and drop it directly into the list and it would create a card with the file.

**Comment by mgmeyers** [comment]
@bitzky You can now drag audio files directly into lists!
