### ISSUE TITLE
[Bug]: Not converting list to different cards After update

### ISSUE THREAD

**Issue by skillhacker-code** [mgmeyers/obsidian-kanban#317]
### Describe the bug

Previous when we add a list to kanban is used to create a different card for each item of the list but now it is not supported 

### Steps to reproduce

Previously i would paste a text like this to list in kanban 

- [ ] telj 
- [ ] asdlfk 
- [ ] asdlf 
- [ ] askdlfj 
- [ ] asdfkl 

And it used to be converted to different cards but now it is not possible now I have to create each card manually or go to markdown version and paste it 

### Operating system

Windows

**Comment by mgmeyers** [comment]
@skillhacker-code I've added an option to the card menu to split a multi-line card into multiple cards.

<img width="332" alt="Screen Shot 2021-09-28 at 1 13 53 PM" src="https://user-images.githubusercontent.com/2694747/135158968-89a5d09d-9a2d-4a2a-befc-20ac52afab3e.png">

I know it's not as seamless as it was before, but does this work for you?

**Comment by skillhacker-code** [comment]
Yes, it does work for me.

It would be great if a hotkey can do both the process. like

Ctrl +Alth +V will paste the text and split the text. 

I appreciate your work so much 

Thank  you so much
