### ISSUE TITLE
[Bug]: Kanban not showing all embed links

### ISSUE THREAD

**Issue by rmfkdehd** [mgmeyers/obsidian-kanban#318]
### Describe the bug

Kanban not showing all embed links.
I've seen this happen with other plugins as well. (Enhanced Mind Map Plugin)
![image](https://user-images.githubusercontent.com/25223304/135008321-c08ad2d0-bc08-4da9-bc04-6914b4be98fb.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/25223304/135008349-636dabe5-0cc5-4470-94d3-e101e60aa2c3.png)

### Steps to reproduce

**Merge.md**
![[First]]

**First.md**
![[Second]]

**Second.md**
# This is Second

I did a simple test with the above three files.
Embedding Merge.md in kanban shows a problem...

### Operating system

Windows

**Comment by mgmeyers** [comment]
@rmfkdehd I've added support for nested embeds (down to 5 levels deep). Let me know if you run into any issues.
