### ISSUE TITLE
[Bug]: Yaml meta data not shown anymore on cards when notelink is not in regular markdown format

### ISSUE THREAD

**Issue by frvkl** [mgmeyers/obsidian-kanban#320]
### Describe the bug

When creating notes from cards, a [[]] link is created to the note. When the note contains yaml information with meta data, the meta data fields and values are **no longer shown** on the cards. 

Only when changing the note link to regular markdown format, the meta data from the linked note is shown on the cards again.

### Expected Behavior

Yaml meta data (as set in plugin settings) from the linked note should be rendered on the cards.

### Steps to reproduce

Create a note from card, and add yaml meta data to the note (as per plugin settings), and notice yaml data is not rendered on the card(s).

### Operating system

Windows

**Comment by frvkl** [comment]
It seems like now the new note links are created in regular markdown format. Are [[]] links no longer supported?

**Comment by mgmeyers** [comment]
@frvkl The plugin should be respecting this setting in obsidian:

<img width="1087" alt="Screen Shot 2021-09-28 at 11 08 46 AM" src="https://user-images.githubusercontent.com/2694747/135142453-86396c88-4b1b-41a0-a271-f3b2115013be.png">

Let me know if this is not the case. Also, I'll make a change to support both formats when it comes to pulling in metadata.

**Comment by frvkl** [comment]
Thank you. That solved the issue.

**Comment by mgmeyers** [comment]
@frvkl The plugin will now pull in metadata from both wikilinks and regular markdown links.
