### ISSUE TITLE
[Feature]: Do not crash when encountering unrecognized elements

### ISSUE THREAD

**Issue by tonyxiao** [mgmeyers/obsidian-kanban#322]
### Goal or desired outcome of this feature

Right now if I wanted to make some extra notes not related to the Kanban, it just crashes with

`Error: I don't know how to interpret this line`

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/696842/135252865-e5b53aa4-5684-4ebb-ad1a-f1985e22768d.png">

I want to be about to write freely, even if they aren't shown on the kanban board, without breaking the kanban view. 

### Describe the feature

Instead of crashing, maybe show a warning, which can be turned off via yaml front matter for users who know exactly what they want

### Can you think of any alternatives or work-arounds?

Use a different note that is not kanban...

**Comment by mgmeyers** [comment]
@tonyxiao unfortunately this plugin can't support arbitrary markdown. To be able to correctly parse each kanban file, it has to be in a strict format. In the future I'll support other formats that may work better for you.
