### ISSUE TITLE
[Bug]: Dragging Card to another list makes it disappear.

### ISSUE THREAD

**Issue by jowibou** [mgmeyers/obsidian-kanban#324]
### Describe the bug

When I drag cards between lists, they disappear while dropping them on to the second list. Data is lost, retrivable only from backup.

### Expected Behavior

As was previously the case, we should be able to drag card between lists without loss.

### Steps to reproduce

1. Drag a card from a list in one pane to another in another pane, 
2. position it in the list (thereby shifting other cards out of the way) 
3. and release. 
4. Then Poof! the card disappears from both lists.

### Operating system

macOS  Kanban 1.0.23

**Comment by reecewebb** [comment]
@jowibou Are you using the Slidings Panes plugin? I disabled it and I'm not seeing this bug anymore.

**Comment by mgmeyers** [comment]
@jowibou I introduced a bug yesterday that may have caused this. Can you update the plugin and try again?

**Comment by reecewebb** [comment]
Cards are still disappearing when drag and dropping between lists on the new version.

**Comment by mgmeyers** [comment]
@reecewebb is this in general, or with the sliding panes plugin active?

**Comment by reecewebb** [comment]
I see the behavior when the Sliding Panes plugin is activated, I don't when it's disabled.

When dragging a card, on first clicking on the card (keep holding the button down), the card doesn't appear to actually disappear, but is shifted to the right so far that it is no longer visible in the window. Without releasing the button, if you move the mouse far enough to the left you can drag the card back into the window and place it in a list.

**Comment by reecewebb** [comment]
One other thing, the behavior isn't consistent. After the first time you lose something, it tends to drag and drop normally for a while. I've had luck reproducing it by restarting Obsidian and reloading the workspace.

**Comment by jowibou** [comment]
It seems sorted now, thanks.
