### ISSUE TITLE
[BUG]: Pasting Links not possible when used with Auto-Link-Title-Plugin

### ISSUE THREAD

**Issue by chrisgrieser** [mgmeyers/obsidian-kanban#325]
Not sure which of the two plugins causes this, but as long as I have the Auto-Link-Title-Plugin enabled, I am not able to paste links in a Kanban Card. Disabling the plugin or pasting anything else than an URL seems to work fine.

**Comment by mgmeyers** [comment]
@chrisgrieser This is a bug with obsidian-auto-link-title. The plugin assumes any pasting being done is inside the obsidian editor. You'll notice the same thing happens if you try to paste links into Obsidian's search input.
