### ISSUE TITLE
[Feature]: make the kanban feel like ticktick

### ISSUE THREAD

**Issue by JJger148** [mgmeyers/obsidian-kanban#329]
### Goal or desired outcome of this feature

I'm still using TickTick as my main kanban, because it feels more smooth to work with, in my opinion it is the best kanban tool ever. 
There are many features, I would ask to adapt, but I simply want to suggest to try using ticktick to have some inspiration to make the Obsidian-kanban feel better. 
 

### Describe the feature

make it work like [ticktick](https://ticktick.com/)

**Comment by skillhacker-code** [comment]
I think the kanban plugin is more smooth than tick tick kanban. 

The only thing the kanban plugin lack that tick-tick kanban has is its awesome reminders.

Other than that kanban plugin by Mgmeyers is THE best

**Comment by JJger148** [comment]
I would love to see the priority button and a toggle button to automatically create a checklist and subordinated checklist.
