### ISSUE TITLE
[Bug]: Drag drop image from Browser not working in Firefox

### ISSUE THREAD

**Issue by keenfoong** [mgmeyers/obsidian-kanban#333]
### Describe the bug

Hi, I've been using the Kanban plugin and it has been great so far. I'm currently having an issue where dragging images from certain web pages in Firefox doesn't seem to create a new card. It downloads the image and I can see it download the image but it doesn't appear in the kanban board. 

As a side point, it seems to be working on Chrome, but not Microsoft Edge.

### Expected Behavior

Dragging images into the board from a webpage to create a new item.

### Steps to reproduce

Try dragging any image from: https://www.artstation.com/artwork/28AQXy

https://cdnb.artstation.com/p/assets/images/images/041/861/445/4k/oussama-agazzoum-gitane-portrait.jpg?1632910039

I noticed that if you removed the `?1632910039` at the end, it seems to work. It seems image on Artstation has those at the end of the images which might be preventing it from creating the images.

### Operating system

Windows

**Comment by mgmeyers** [comment]
Hmm, so I tested this out on mac, and it seems to work. I'll have to set up a virtual machine to test on Windows though.

**Comment by keenfoong** [comment]
Hi, this looks like its working now =D Not sure what changed but dragging images in from Firefox seems to be working on my end now. This can probably be closed.
