### ISSUE TITLE
[Bug]: Empty List names errors

### ISSUE THREAD

**Issue by keenfoong** [mgmeyers/obsidian-kanban#335]
### Describe the bug

When an empty list name is given, it errors. I like having the empty list name there, sometimes the title of the note is enough of a description.
![lUTyBjMlMC](https://user-images.githubusercontent.com/31301148/135775849-4b023792-a586-4a54-91a9-f1555172f3ab.gif)

### Expected Behavior

No error on empty names

### Steps to reproduce

Create board with empty names list names.

### Relevant errors (if available)

```shell
Error: I don't know how to interpret this line:
##
    at Yc.mdToBoard (eval at <anonymous> (app.js:1), <anonymous>:98:453)
    at async zc.getParsedBoard (eval at <anonymous> (app.js:1), <anonymous>:99:4714)
    at async zc.newBoard (eval at <anonymous> (app.js:1), <anonymous>:99:1812)
```

### Operating system

Windows

**Comment by mgmeyers** [comment]
@keenfoong This should be fixed in the latest release. Let me know if you still have issues.
