### ISSUE TITLE
[Feature]: Pasting images from clipboard

### ISSUE THREAD

**Issue by keenfoong** [mgmeyers/obsidian-kanban#338]
### Goal or desired outcome of this feature

Would be great if you could paste images from clipboard. 

### Describe the feature

Pasting into the cards from clipboard. Currently you can do it in markdown mode but not in Kanban mode. 

### Can you think of any alternatives or work-arounds?

One workaround is to save the clipped image as a file and drag it in.

### Screenshots, mockups, or videos

https://user-images.githubusercontent.com/31301148/136307390-31105728-e96c-41fa-b2cb-e3c9e4370745.mp4

**Comment by mgmeyers** [comment]
@Quorafind Hmm strange 🤔. I don't think a plugin would cause this error. What is this setting set to in the vault that's causing this error?

<img width="768" alt="Screen Shot 2021-10-08 at 6 22 44 PM" src="https://user-images.githubusercontent.com/2694747/136638950-e84b2024-a47f-4778-a52c-28635761b4d4.png">

**Comment by Quorafind** [comment]
![image](https://user-images.githubusercontent.com/13215013/136639672-b53e36af-b200-4b09-ac4d-a48ecb8f25ab.png)
![image](https://user-images.githubusercontent.com/13215013/136639677-af0fad57-1f47-41d3-8aa5-61c10f09298a.png)

Is it possible that the problem occurs because of chinese?

**Comment by Quorafind** [comment]
When I used vault folder as the attachment folder, it works well.

![image](https://user-images.githubusercontent.com/13215013/136640037-88d3ee50-b888-4c16-945e-586d3aea3633.png)

but it doesn't work with any other config like this:

![image](https://user-images.githubusercontent.com/13215013/136640063-e68a1765-f8b4-48c2-acb9-af418e0633b0.png)

**Comment by Quorafind** [comment]
@mgmeyers yes, it works correctly
