### ISSUE TITLE
[Bug]: Date No Longer Formatted within Board?

### ISSUE THREAD

**Issue by FrocketGaming** [mgmeyers/obsidian-kanban#344]
### Describe the bug

Updated today and now the dates show up like this:
@[October 18, 2021](October 18, 2021.md)

### Expected Behavior

Previously they showed up as a link and didn't show the markdown unless you were editing or outside of kanban view. 

### Steps to reproduce

Just adding the date shows up that way, I haven't changed anything other than updating the plugin today. 

### Operating system

Windows

**Comment by mgmeyers** [comment]
Thanks for the update @FrocketGaming. Yeah, the plugin isn't able to update old date links when the format changes, unfortunately.
