### ISSUE TITLE
[Bug]: Empty Last Column disappears from Kanban Board on editing

### ISSUE THREAD

**Issue by ayapcck** [mgmeyers/obsidian-kanban#346]
### Describe the bug

~~I go clean up the "Archive" list of test tasks and other things without links, and I noticed that the empty columns at the end of my board get removed...~~

An empty column / lane will disappear from the kanban board if it's the last column in the board

### Expected Behavior

I should be able to have empty columns as the last column without them being removed

### Steps to reproduce

1. Create an empty test column / list / lane
2. Don't add any cards
3. Go to the "View as markdown"
4. Notice that the markdown heading for the new list is present
5. Go back to "View as kanban board"
6. Notice the column has now disappeared
7. Add a card to any other existing column
7. Go back to "View as markdown"
8. Notice the header for the new column has now also disappeared

The below steps are outdated, the above steps more accurately uncover the issue

1. Have two test columns on the far right (for me this is directly above the hidden "Archive" list)
2. Create a new basic card (no links) in the second to last column (so the last column is empty)
3. Go to the markdown for the kanban board, and remove the line corresponding to the basic card
4. This removes the empty column when the board reloads (I have it pinned to the sidebar so I can see it immediately be removed)
5. Adding a new card to the remaining column (in the pinned version) then removes the heading corresponding to the deleted column

### Operating system

Windows

**Comment by ayapcck** [comment]
I'm not sure this accurately represents the bug actually.. It seems I can replicate the behavior simply by switching between the kanban board view and the markdown view, while I have an empty column as the final column in the board.

**Comment by richardberube** [comment]
I get the same issue.
 
## Operation System 
Ubuntu 20.04 LTS

## Community Plugins installed
- Advanced Tables
- Calendar
- Dataview
- Periodic Notes
