### ISSUE TITLE
[Bug]:  Cant add card in Mobile edition 

### ISSUE THREAD

**Issue by skillhacker-code** [mgmeyers/obsidian-kanban#352]
### Describe the bug

Previously when enter button is tapped two time , we were able to add card in kanban board in mobile , but now i am not able to do that 

### Steps to reproduce

Try to add card in android kanban

### Operating system

Android

**Comment by mgmeyers** [comment]
@skillhacker-code All inputs on mobile now have a submit button! This should effectively fix this issue. Let me know if you have any issues.

<img width="284" alt="Screen Shot 2022-04-02 at 11 47 55 AM" src="https://user-images.githubusercontent.com/2694747/161397130-35674976-fcae-451a-abf9-db38de2dcfaf.png">
