### ISSUE TITLE
how are checkbox items added to cards?

### ISSUE THREAD

**Issue by ezeeman** [mgmeyers/obsidian-kanban#356]
In the example board shown in the "[how do I](http://matthewmeye.rs/obsidian-kanban/Assets/Screen%20Shot%202021-09-16%20at%2012.58.22%20PM.png)" doc, several cards contain lists with checkboxes. The **Enhanced search/filtering** card in the **Todo** column/list has checkboxes. The first card in the **In progress** column/list with the red header **<span style="color:red">kanban-plugin: detailed</span>** has some too.

What is the markdown to add these checkboxes?

**Comment by Oblique82** [comment]
Im not sure if this is related however on iOS when I try to add subtasks or bullet points to a card, the hyphen keep getting deleted as soon as I type the next character. This does not occur on desktop
