### ISSUE TITLE
[Feature]: "Reveal File in Navigation" on context menu for links

### ISSUE THREAD

**Issue by JJSlote** [mgmeyers/obsidian-kanban#369]
Hi - When we open our kanban board as markdown, we can right click on a link to reveal it in Obsidian's own file explorer. But a right click on a link in the kanban view opens the link while showing a context menu for the card, rather than for the link. 

I have some Windows shortcuts in my vault, linking to Scrivener rtf docs, which are always named _content.rtf_. The .LNK files can take meaningful filenames, and "Reveal in Navigation" would make them easier to find in the vault.

Ideally the context menu when we right-click on a link within a card would match as fully as possible the options available when we right click on a link in an ordinary Obsidian note, and thus would include "Reveal File in Navigation."

Thanks for considering...Jerome

**Comment by mgmeyers** [comment]
@JJSlote You should be able to open the correct context menu for links without opening the link now. Let me know if you still have issues with this after updating.
