### ISSUE TITLE
[Bug]: Inline metadata with multiple links causes metadata settings to erase

### ISSUE THREAD

**Issue by dpmeltz** [mgmeyers/obsidian-kanban#371]
### Describe the bug

Inline fields with 2 linked values (`field:: [[link1]], [[link2]]`) fails on Kanban board. If I turn DataView off none of the inline fields work, 
Sometimes the fail clears out settings for linked metadata, other times it loads nothing for that field/card and prevents the card from being moved.
This was processing as of a few days ago, I'd get 2 columns with both links (not always pretty but functional), but as of a few days ago I started losing all of my metadata fields a few seconds after loading them.

Multiple fields in YAML seems to work, so I think it's about those fields being _links_ for me.

Tested this way on MacOS, Windows, and iOS

### Expected Behavior

I'd understand failing to load the two links on the card (though it was loading them as columns as of a few days ago), but wiping the preferences from the file is definitely undesirable behavior.

### Steps to reproduce

1. Create a Kanban using Kanban plugin & a blank task file
2. Add metadata to test file (something like field:: [[link1]], [[link2]])
3. create Kanban card for test file
4. Add metadata field to Kanban "linked metadata" section

### Operating system

macOS

**Comment by mgmeyers** [comment]
@dpmeltz Dataview's recent update broke some things. This should be fixed now. Let me know if you still run into issues after updating the plugin!
