### ISSUE TITLE
[Feature]: WIP / card limit for lists

### ISSUE THREAD

**Issue by 1npo** [mgmeyers/obsidian-kanban#373]
### Goal or desired outcome of this feature

Implement a card limit for lists, to support Kanban's "WIP limit" feature, as described in the links below:

https://kanbanize.com/kanban-resources/getting-started/what-is-wip

https://www.atlassian.com/agile/kanban/wip-limits

### Describe the feature

Here's how I imagine it would work:

- When you "Edit list", display a field under or beside the list title that allows you to enter an integer, which represents the maximum number of cards allowed in that list
- When you click on the "More options" button of a list, have a "Set card limit" menu item that does the above
- When viewing a list on the board, display a fraction next to the title that shows the number of cards in that list over the card limit
- Don't allow more cards in a list than the limit -- eg, if I try to drag a card into a list with a card limit of 4, and that list already has 4 cards in it, then nothing should happen (or the card should just snap back into place)

**Comment by furlan** [comment]
I think WIP limit is a must for any kanban board, but I prefer more like as an information not limit.
For example, we should be able to add more items than the work limit, but we have a visual indication, like, the number of items become red.

**Comment by phillipjohnston** [comment]
I am also a fan of the "visual signal" approach instead of a hard block.

**Comment by andrewslotin** [comment]
I'd be happy to have this feature supported by the Kanban plugin. WIP limits are one of the cornerstones in Kanban that allow you make sure that only limited number of tasks are in progress at every single point in time. This encourages one of the Kanban principles: "Finish starting things and start finishing them" :)

As an alternative suggestion, I'd be happy with using an optional max cards number for a column following its header, something like `In Progress [3]` and highlighting it whenever this limit is about to be reached. An confirmation popup telling you that you're about to move a card into the column that has already reached its WIP limit would be nice, but not necessary.
