### ISSUE TITLE
[Feature]: Support checking checkboxes in embedded content

### ISSUE THREAD

**Issue by peteger** [mgmeyers/obsidian-kanban#376]
### Goal or desired outcome of this feature

It would be great to have the ability to check off todo lists that are inserted as a link to external block with checkboxes. 

### Describe the feature

When using external link to block as a card content, the checkbox is displayed properly, but it's not clickable. I like the idea to keep checklists stored in other notes, but create a card referencing some of the checklist items.

E.g. this syntax will display block with checkmark from an external note:
`![[External note#^azovu1ass]]`

### Can you think of any alternatives or work-arounds?

Yes, you can click on the link icon to jump to original note and check the checkmark there.

### Screenshots, mockups, or videos

<img width="565" alt="exetrnal reference" src="https://user-images.githubusercontent.com/7255554/140958053-81518db8-018f-4f2d-94a5-ca60e264d391.png">
<img width="566" alt="external linked block" src="https://user-images.githubusercontent.com/7255554/140958059-62638216-3bc8-4e05-a412-6ba429bb8f7e.png">

**Comment by TfTHacker** [comment]
I have wanted the same thing. For now the workaround is that the preview available (via the paperclip icon in upper right hand corner of card)  which supports clicking of a task to finish it.

**Comment by Archie-2021** [comment]
+1 for this feature. every handy for managing multiple Kanbans
