### ISSUE TITLE
[Bug]: Right click on card with internal link file opens the file

### ISSUE THREAD

**Issue by psychsatani** [mgmeyers/obsidian-kanban#381]
### Describe the bug

Left mouse click should open the note and right mouse click should open the menu. But only on the karban board, a right click causes 2 actions simultaneously. 1) note is opened (unexpected) 2) context menu is opened (expected). 

### Expected Behavior

only context menu should open

### Steps to reproduce

Right click on any card that has an internal link. 

https://user-images.githubusercontent.com/78266798/141657067-a26e14fe-e2e6-4d25-9bdd-08a27453922b.mov

### Operating system

macOS

**Comment by mgmeyers** [comment]
@psychsatani This should be fixed now. Let me know if you still have issues with it

**Comment by psychsatani** [comment]
Yes, it is fixed. Thank you!!
