### ISSUE TITLE
[Feature]: Open Kanban Notes In New Pane

### ISSUE THREAD

**Issue by Psypher1** [mgmeyers/obsidian-kanban#387]
### Goal or desired outcome of this feature

A setting that gives the option to always open kanban notes in new pane or not. Whether they are new or old.

### Describe the feature

Right now when you create a note from a card, it is opened in a new pane. That is very useful for working with the board and  note. However, when you reopen that note later - from the board - it replaces the board.

With the setting on, a note made via the kanban board (regardless of time) would open in a new pane. Allowing you to see both the board and pane. 

### Can you think of any alternatives or work-arounds?

A control click of the created note, but that defeats the purpose

**Comment by mgmeyers** [comment]
@Psypher1, I'll think about adding a setting to control this. But at the moment it follow Obsidian's default behavior. You can open linked notes in a new pane by pressing `ctrl` or `command` and clicking on them.

**Comment by Psypher1** [comment]
Thank you. I'm happy that you're thinking about it
