### ISSUE TITLE
[Bug]: Data loss

### ISSUE THREAD

**Issue by JJger148** [mgmeyers/obsidian-kanban#391]
### Describe the bug

When I close a new drawing, the data is lost most of the time. 
It only happens with new files I create. 
I have this issue maybe since a week. 
I already have the most recent update and still it happens. 

### Steps to reproduce

I simply create a new image, draw something, and after closing the pane and reopening, I don't see the data. 

### Operating system

macOS

**Comment by mgmeyers** [comment]
@JJger148 Is this issue filed with the wrong plugin? Not sure what you mean by drawing.

**Comment by JJger148** [comment]
I'm sorry, false plugin.
