### ISSUE TITLE
[Bug]: Link and tags autocomplete list not fully visible

### ISSUE THREAD

**Issue by Pyrodusk** [mgmeyers/obsidian-kanban#392]
### Describe the bug

When adding markdown links or tags to a card or a list in the boards, the autocomplete list mostly displays up which makes it impossible to see the options proposed. It seems to move down after inputing a few words but it is not practical for shorter note name.

https://user-images.githubusercontent.com/80559262/143664815-4ed7ff81-e459-45a2-a2e5-df05bd54e12f.mp4

### Expected Behavior

As the inputs are added at the top of the window, the autocomplete list should display down. The behavior should be the same as within notes : display list down when at the top of the window and display up when at the bottom. 

### Steps to reproduce

Input a markdown link or a tag in the Kanban view. 

Thanks a lot for the plugin ! Aside from this small bug, it is amazing. 

### Operating system

Windows

**Comment by mgmeyers** [comment]
@Pyrodusk This should be fixed now!

**Comment by Pyrodusk** [comment]
Indeed it works great now. Thanks a lot !
