### ISSUE TITLE
Card movement incompatible with Snippets plug-in

### ISSUE THREAD

**Issue by infotropy** [mgmeyers/obsidian-kanban#40]
Moving cards from one list to another is incompatible with the [Snippets](https://github.com/cristianvasquez/obsidian-snippets-plugin) plug-in.￼

When Snippets and Kanban active at the same time, the card dragged from one list to another will disappear when hovering over the second list.￼

**Comment by mgmeyers** [comment]
I've made a pr to the snippets plugin that should fix this: https://github.com/cristianvasquez/obsidian-snippets-plugin/pull/5

Closing this issue out for now, since the bug in on the other end. Thanks @infotropy!
