### ISSUE TITLE
[Bug]: Card labels are displayed in an inconsistent order

### ISSUE THREAD

**Issue by SkepticMystic** [mgmeyers/obsidian-kanban#403]
### Describe the bug

When using custom labels on cards, sometimes they appear in an inconsistent order, even if the metadata fields on the corresponding notes are defined in the same order

### Expected Behavior

It would be nice if the labels appeared in the same order top-to-bottom

### Steps to reproduce

Define multiple labels to look for in a note, and make multiple cards which link to notes with those labels.
The labels might be in different orders

![image](https://user-images.githubusercontent.com/70717676/144864636-bcf337ef-3f53-43b9-9323-1bcd29322b76.png)

### Operating system

Windows

**Comment by mgmeyers** [comment]
@SkepticMystic This should be fixed now. They order should be the same as it's defined in settings. Let me know if you run into any issues.
