### ISSUE TITLE
[Feature]: Div ID, or other attribute, to match "Copy Link to Card"

### ISSUE THREAD

**Issue by JJSlote** [mgmeyers/obsidian-kanban#406]
Hi - I've been formatting cards based on their tags, expanding, collapsing and coloring them through a toggle, via AutoHotkey,  that writes to a CSS snippet file. This is possible because Kanban creates classes `kanban-plugin__item has-tag-(tagname)` based on the tags applied to each card. 

Now I'm looking to do the same with individual cards, but I can't get a similar handle on 'em. 

I'd suggest that the same identifier that is exposed via "Copy Link to Card" become an ID or other attribute in that card's corresponding DIV, as shown in Developer Tools. This would enable the user to obtain any card's handle via a right click, and reformat the card with a CSS statement keyed to the matching attribute.  

API and minimize/maximize are on the Roadmap, so in time it'll be possible to format individual cards by those methods. For now, this suggestion, which requires no changes to the UI, would be a more easily achievable under-the-hood tweak for enthusiasts.

Thanks for considering!! -- Jerome

**Comment by JJSlote** [comment]
All good; no enhancement needed. Finding that I can toggle formatting on a single card adequately via a sibling selector.
Cheers - Jerome

**Comment by monogalactico** [comment]
HI JJSlote, it sounds very interesting. I want to format cards base on tags etc... But I don't understand how you get it. Autohotkey? Could you help me with css example or something to see the code??? Thanks a lot!!!

**Comment by JJSlote** [comment]
Greetings monogalactico -- The AutoHotkey approach I was using back in December is obsolete. These days I toggle folding on individual Kanban cards with the card's checkbox. That checkbox is intended to mark the card's task as complete, so I use the `is_complete` CSS class as a display toggle:

`div.is-complete div[class*='preview'] {max-height: 46px !important; overflow: hidden; background-color: #aa9 !important;}`

To toggle folding by tag, I now create a dedicated snippet file for each tag. For the "media" tag I'm using this code in a `media.css` snippet file:

`div[class*='has-tag-media'] [class*='preview'] {max-height: 22px; overflow: hidden;} 
div[class*='has-tag-media'] > div > div {margin-bottom: -8px;} 
div[class*='has-tag-media'] div {background-color: #8aa;}`

Now to trigger the toggling of the media.css snippet, we want a method more convenient than reaching into the Appearance menu under Settings. So I'm using the community plugins "Snippet Commands" (which turns the toggling of a CSS snippet into a command accessible on the Pallette) and "Obsidian Advanced URI" (which enables us to execute a Command Pallette entry via URI). Then the URI to effect the toggle goes on a header card where a group of cards share the matching tag. 

I like the idea of toggling tags in Kanban cards without the need to open them for editing. The checkbox is a built-in way to toggle one such tag, but it'd be great to have some others that could be triggered on control keys.
Cheers - Jerome

**Comment by monogalactico** [comment]
Thanks for your answer! Im going to try that! Its brilliant ! Certainly it would be nice to trigger on control keys... Do you know if there is in the development backlog???  Thanks!!

**Comment by JJSlote** [comment]
It's not on the roadmap, and, upon further consideration, it's not a good concept anyway. Preview mode doesn't have a natural insert point as edit mode and the checkbox do. So even if we could remember each key combo, a tag on a control key would not reliably reach the intended card. A per-card tag manager on the context menu would be more promising. 

The roadmap does show list and table views that will keep sets of cards out of sight but easy to identify and reach, which is our objective in folding. Meanwhile the folding toggle on the checkbox has been working well as a stopgap, and we can always move the card to another lane to represent completion. 
Rgds - Jerome

**Comment by monogalactico** [comment]
Hi Jerome, Im using your code for change card color in base of tags and its
fantastic!! Id like to decide color in base of 2 tags, I mean , for
example, if you add "urgent" and add "important", you put red card.... Yes,
i can create a tag "urgent and important" but i dont know if it is posible
to choose color in base of "two" tags... Again thanks for your help!

**Comment by JJSlote** [comment]
Hi monogalactico, try this:
`div.has-tag-urgent.has-tag-important div {background-color: #a88;}`
Cheers...Jerome

**Comment by monogalactico** [comment]
That WORKED!!! Thank you so much!!!!

**Comment by monogalactico** [comment]
Hi JJSlote, Im improving my kanbans, thanks for your help. Now Im trying to
work with some kanbans together. For example I have a kanban with card  X
and I put a link in other card in other kanban with ![[Card^axasxsa]]. This
is working  but the appearence of the content of the card in this new
kanban (I mead font, color,etc is not the same that I changed with snippets
in the "main kanban cards".  I want to "indentify" that this card is a link
like you helped me with "is-complete", "has-tag-xxx", etc but I think there
is not a "is-link" or something like that state. In fact I searched in the
code (I dont lbother you again!!) and I found "getItemClassModifiers" but
there are not a is link or similar.  Im trying to see in css how can I
identify or change css related to embedded links but I dont get it (im inot
very good at css actually). How can I do that? If you know a document
please le me know because I dont want to disturb you all the time....

Thanks again!!!
[image: image.png]

**Comment by JJSlote** [comment]
Hi Miguel - I don't believe this would be possible with CSS alone. CSS enables us to target an element in the context of its ancestors, for example nesting DIVs of a particular class. But it can't target based on a descendant such as an `a` tag. Easier to look behind than ahead. We'd need a script that assigns a class to DIVs that include links, or probably to the ancestors of those DIVs. 

Good luck with your board! Jerome

>  Im trying to see in css how can I identify or change css related to embedded links but I dont get it (im inot very good at css actually). How can I do that?
