### ISSUE TITLE
A question about checkbox in a card

### ISSUE THREAD

**Issue by luooofan** [mgmeyers/obsidian-kanban#412]
Just a simple question. Not a bug. Not a feature.

**How to achieve this?**
![image](https://user-images.githubusercontent.com/46896167/146802379-7155c639-24c3-4ebf-ab55-65ba754a97a4.png)

**My situation**
![image](https://user-images.githubusercontent.com/46896167/146802651-3b1b40e2-5e39-4544-bdad-cf6b7f1ca3c4.png)

**Comment by mgmeyers** [comment]
Hi @luooofan it looks like you may be missing the dash before the square brackets. The checkbox markup looks like this:

```
- [ ] Checkbox 1
- [ ] Checkbox 2
```

Let me know if this helps!

**Comment by luooofan** [comment]
Hi @mgmeyers  It works! Thanks a lot!
