### ISSUE TITLE
[Bug]: Front-matter in card item show twice

### ISSUE THREAD

**Issue by Lynx3x** [mgmeyers/obsidian-kanban#413]
### Describe the bug

I updated the plugin to the latest version(1.2.23), and every my front-matter in the card show twice. Weird.

### Steps to reproduce

Add front-matter to show, and happened.

### Operating system

Windows

**Comment by mgmeyers** [comment]
@Lynx3x I wasn't able to reproduce this, but I think I figured out what was going on. Could you update the plugin and test again?

**Comment by Lynx3x** [comment]
@mgmeyers I updated, and solved. Thank you!
