### ISSUE TITLE
[Feature]: Attach existing note to a card

### ISSUE THREAD

**Issue by luckydays** [mgmeyers/obsidian-kanban#416]
Hey Matthew! And the whole Obsidian community.

So happy to have this wonderful plugin. Thank you very much for all the work you put into it!

I wonder (checked the issues/feature requests, but doesn't seem to find) - is there already a way (or is it planned some time soon) - not only to Create a New Note from the Kanban card, but to attach/pick among the list of previously created notes?
That would be so so handy!
Meantime I'm forced to copy/paste the content of a particular note to newly created from the card note 🙂 

@mgmeyers

**Comment by mgmeyers** [comment]
Hi @luckydays, you can link to any note in your vault from a card like you would elsewhere in obsidian:

<img width="425" alt="Screen Shot 2021-12-27 at 10 50 44 AM" src="https://user-images.githubusercontent.com/2694747/147499451-feda8b98-e4ae-40ba-83d3-4e2fe783eb77.png">

Does this accomplish what you're looking to do?

**Comment by luckydays** [comment]
Of course.
The fact we're dealing with markdown in Obsidian wherever we're at, completely got out of my mind 😄 
This makes perfect sense. Thank you @mgmeyers
