### ISSUE TITLE
[Bug]: the list of suggestion of wikilinks goes out of the screen when its location is near the edge of screen

### ISSUE THREAD

**Issue by Archie-2021** [mgmeyers/obsidian-kanban#417]
### Describe the bug

the suggested list goes out of the screen when it is at the edge
not visible and looks like this:
![image](https://user-images.githubusercontent.com/85870778/147561165-26338ec2-7fae-40aa-880b-26b2916e79cb.png)
 

### Steps to reproduce

just put a card near screen edge (in my case top) and try to insert or modify an wikilink in a long list

### Operating system

Windows

**Comment by danebace** [comment]
Same issue in Linux
