### ISSUE TITLE
[Bug]: ios can't move cards

### ISSUE THREAD

**Issue by drozzy** [mgmeyers/obsidian-kanban#419]
### Describe the bug

When moving cards a new card with giberrish text appears in the new column, and the old card stays put.

### Steps to reproduce

Move a card on iOS obsidian.

### Operating system

iOS

**Comment by mgmeyers** [comment]
@drozzy What version of iOS, obsidian mobile, and the kanban plugin are you on?

**Comment by drozzy** [comment]
strange it works now. 

All the latest versions as of today Jan 2.
