### ISSUE TITLE
[Bug]: iOS linked page metadata fields double up

### ISSUE THREAD

**Issue by drozzy** [mgmeyers/obsidian-kanban#420]
### Describe the bug

If I define a linked page metadata field on iOS obsidian, it actually shows up _twice_ on the card view.

### Expected Behavior

Field should appear once.

### Steps to reproduce

1. Add new Linked Page Metadata field called "example"
2. Create a new note with the contents:

```
---
example: This is a field
---

```
3. Go back to card view. Field now appears twice:
```
example: This is a field
example: This is a field
```

### Operating system

iOS

**Comment by mgmeyers** [comment]
@drozzy I wasn't able to reproduce this, but I think I figured out what was going on. Could you update the plugin and test again?

**Comment by drozzy** [comment]
Yes that fixed it. Thanks.
