### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by puptato** [mgmeyers/obsidian-kanban#424]
### Describe the bug

Installing Kanban from Community Plugins results in a 404 error (as logged by the console)

### Expected Behavior

The Kanban community plugin should install automatically.

### Steps to reproduce

Install Obsidian
Turn off Safe Mode
Search for Kanban as a community plugin
Click on Install

### Relevant errors (if available)

```shell
app.js:1 GET https://github.com/mgmeyers/obsidian-kanban/releases/download/1.2.24/manifest.json 404

app.js:1 XMLHttpRequest {onreadystatechange: null, readyState: 4, timeout: 0, withCredentials: false, upload: XMLHttpRequestUpload, …}
```

### Operating system

macOS

**Comment by puptato** [comment]
<img width="1800" alt="Screen Shot 2021-12-30 at 12 03 21" src="https://user-images.githubusercontent.com/93884254/147784872-6d2d5e93-df15-4ac7-ab57-7020f181ffc5.png">

**Comment by mgmeyers** [comment]
Sorry about that @puptato, you should be able to download the plugin now. You may have to restart obsidian for it to pick up the correct version info.
