### ISSUE TITLE
[Question] How to access Liked page metadata from YAML maps

### ISSUE THREAD

**Issue by rishifter** [mgmeyers/obsidian-kanban#434]
I'm trying to fetch metadata from my film notes which have the following sample YAML:

```---
aliases: ["About Time"]
tags: [film]
rating: 8
people:
dateCreated: 2020-11-14T23:47
info: 
  title: About Time
  year: 2013
  rated: R
  released: 2013-11-08
  runtime: 123
```

How do I access the field title or year here in Kanban? In Dataview I access them using `info.title` but that doesn't work here. Thanks.

**Comment by mgmeyers** [comment]
@rishifter This is currently not possible, but I have a ticket to allow for this: #530 Going to close this in favor of that one.
