### ISSUE TITLE
[Bug]:  Several Kanbans

### ISSUE THREAD

**Issue by se6y117** [mgmeyers/obsidian-kanban#437]
### Describe the bug

It is not possible to create several different kanban boards. If I change one note in a board then the others change too. Is this a bug or a feature?

### Expected Behavior

Every kanban board is customizeable

### Steps to reproduce

Create several kanbans an change notes in it.

### Operating system

macOS

**Comment by se6y117** [comment]
It seems that this problem is caused by special charts like ö in the Kansan name. If a rename it without "ö" it works properly.

**Comment by mgmeyers** [comment]
@se6y117 I wasn't able to reproduce this issue. Is it still a problem for you?
