### ISSUE TITLE
[Request] Make a link in a list header clickable on Kanban view

### ISSUE THREAD

**Issue by rodrigo-rufino** [mgmeyers/obsidian-kanban#44]
Would be really nice to have the header of a list clickable like any other link.

![Screenshot from 2021-04-29 20-49-42](https://user-images.githubusercontent.com/18670446/116631976-6f8b7e00-a92c-11eb-96b7-701f92891f08.png)

**Comment by mgmeyers** [comment]
@rodrigo-rufino This has been implemented! Let me know if you run into any issues.
