### ISSUE TITLE
[Bug]: Wrong "Today" date highlighted in Date Selector

### ISSUE THREAD

**Issue by promethean** [mgmeyers/obsidian-kanban#448]
### Describe the bug

- When typing `@` on any card in the kanban, a date selector appears.   
- The date selector highlights **yesterday's date** with a blue border... when it should highlight today.

### Expected Behavior

- The date selected should be today's date

### Steps to reproduce

- Click @ on a kanban card
- View date selector
- View highlighted date
- Should be today's date

I am in GMT timezone.  Obsidian

<img width="1584" alt="Obsidian_-_Obsidian_v0_13_21_and_Fantastical" src="https://user-images.githubusercontent.com/545932/151149061-477441b9-63b0-4f94-92c6-a7ffb96662ad.png">

### Operating system

macOS

**Comment by dninemfive** [comment]
I believe it highlights the date you last opened Obsidian, actually. I had it running for about a week starting the 16th and it still said the 16th by the time I had to restart my computer. When I open Obsidian right now and see the highlighted date, it's today.

**Comment by SuperTempAccount** [comment]
> I believe it highlights the date you last opened Obsidian, actually. I had it running for about a week starting the 16th and it still said the 16th by the time I had to restart my computer. When I open Obsidian right now and see the highlighted date, it's today.

I can confirm this is the case 👍 . 
Restarting Obsidian corrects the date highlighted as "Today". 
Previously it was pointing to over a week in the past for me.

The current workaround is to restart Obsidian daily 😢
