### ISSUE TITLE
Newline trigger (Enter/Shift+Enter) issues on android

### ISSUE THREAD

**Issue by amankapoor** [mgmeyers/obsidian-kanban#459]
I use Obsidian on Android, and recently installed this plugin.

As Gboard doesn't have Shift+Enter feature, so writing paragraphs inside a card is troublesome. If I choose newline trigger as Enter, then card doesn't get saved. And if I choose newline trigger as Shift+Enter, then I can't write more than a paragraph inside a card.

Kindly look into the issue, and if possible, please suggest solutions or resolve this as per your convenience. It is a very good plugin.

Thank you.

**Comment by amankapoor** [comment]
Yes, in addition to current functionality, implementing a escape character would be very helpful for mobile users.

**Comment by red-co** [comment]
> 如果我们也可以提供像“\n”这样的转义字符来创建新行，那会很酷，不需要检测输入并且可以独立于平台

you can use '<br>'，
it can work

**Comment by mgmeyers** [comment]
Hey all, all inputs on mobile now have a submit button! This should effectively fix this issue. Let me know if you have any issues.

<img width="284" alt="Screen Shot 2022-04-02 at 11 47 55 AM" src="https://user-images.githubusercontent.com/2694747/161397130-35674976-fcae-451a-abf9-db38de2dcfaf.png">
