### ISSUE TITLE
[Feature]: Define specific heading for kanban board

### ISSUE THREAD

**Issue by mdbraber** [mgmeyers/obsidian-kanban#461]
### Goal or desired outcome of this feature

I've got project files that include some background as well as task categories (Today, This week etc.). I'd like to be able to define a specific part of the file, e.g. under the heading Tasks as my lanes.

### Describe the feature

Define subheadings under a main heading as focus for the kanban board

### Can you think of any alternatives or work-arounds?

I could separate the kanban board and transclude it in my main file, but that would prevent me from easily editing the main file.

**Comment by zadorski** [comment]
I second the idea. Such enhancement could lay the groundwork even to have several kanban boards within one note (say, for 4 weeks overview). Maybe it's just me, it appears kanban note keeps reformatting my headers to be all H1...

**Comment by mgmeyers** [comment]
So, it'll likely never be possible to add different headings to the kanban files because the plugin relies on a very strict markdown structure. But what you're describing could be achieved with #4 . I'm going to close this issue in favor of that issue.
