### ISSUE TITLE
[Bug]: transcluded checkbox cannot be checked

### ISSUE THREAD

**Issue by evenrue** [mgmeyers/obsidian-kanban#468]
### Describe the bug

Clicking the checkbox (- [ ]) for content that has been transclusioned into a kanban card from another note does not work / does not propagate to the original note. 

### Expected Behavior

Clicking the checkbox should successfully mark the checkbox as complete and, like other situations where you transclude a checklist, you can complete the checklist from any document. 

### Steps to reproduce

1. Create a note and make a task under a heading so that you can easily find it for transclusion.
2. Go to kanban board and Add a card. Transclude the note heading that was added.
3. Click the checkbox!

(optional 4. feel sad when it doesn't complete.)

### Relevant errors (if available)

```shell
Didn't see any developer console errors.
```

### Operating system

Windows

**Comment by dninemfive** [comment]
The checkboxes no longer even appear for me in kanban cards, though manually adding an `x` in edit mode does cross them out. See the following images for an example:
![the checkboxes no longer show up, but they can be manually crossed out](https://user-images.githubusercontent.com/11084010/162262093-bf2e86bc-54f5-41a5-be89-19181c6e656d.png)
![edit mode view of the above](https://user-images.githubusercontent.com/11084010/162262113-3485af10-6cfe-4a76-963e-520c616a8a08.png)

**Comment by mgmeyers** [comment]
@dninemfive This is a separate issue, but are you using the latest version of the plugin? Also, what theme are you using and what obsidian version are you on?

Here's what I see on the most latest version of everything and the default theme:
<img width="262" alt="Screen Shot 2022-04-07 at 10 32 18 AM" src="https://user-images.githubusercontent.com/2694747/162262622-a15fd31e-10b8-4530-bfc4-df4157b9608e.png">

**Comment by dninemfive** [comment]
The theme is the dark version of the default theme. It looks like I'm on 1.2.28, so I'll try updating and see if that fixes this.

**Comment by dninemfive** [comment]
Updating fixed this particular issue. Thanks!

(I'm fairly new to Obsidian and assumed it kept plugins up-to-date automatically. Good to know I need to check from time to time.)

**Comment by evenrue** [comment]
Hi,

I eagerly updated my plugin hoping to try this out, but it doesn't seem like it's actually been fixed?

**Comment by mgmeyers** [comment]
@evenrue Are you using the latest insider build? Unfortunately this fix requires functionality not available in the post recent public release. Once obsidian 0.15 is released to the public you should have access to this.

**Comment by evenrue** [comment]
Ohhh, okay. Thanks, will wait until then.  @mgmeyers  appreciate it!
