### ISSUE TITLE
[Bug] The plugin throws error if there is a series of three or more hyphens

### ISSUE THREAD

**Issue by fathyar** [mgmeyers/obsidian-kanban#48]
**Plugin version**: 0.1.2

Examples of Cases
---

Listed below are examples of cases that causes the plugin throw an error message of `Failed to load "filename.md". bad indentation of a sequence entry ...`:

- Example 1
    ```
    ## List

    - [ ] The following sequence of hyphens---will throw an error message.
    - [ ] The following hyphens ------ also will.
    - [ ] A series of three or more hyphens wrapped in backticks `---` also will.
    - [ ] The following hyphens -- -- will not.
    ```
- Example 2
    ```
    ## List

    - [ ] item
    - [ ] ---
    ```
- Example 3
    ```
    ## List

    - [ ] ----
    ```

Examples of cases that causes the plugin throw an error message of `Failed to load "filename.md". expected a single document in the stream, but found more`:

- Example 1
    ```
    ## List

    - [ ] ---
    ```
- Example 2
    ```
    ## List

    - [ ] ---
    - [ ] item
    ```
- Example 3
    ```
    ## List---wow

    - [ ] item
    ```

Steps to reproduce the bug
---

1. In a kanban board, create task list items or 2nd level headings with content like in the aforementioned examples.
2. Then close the file (the kanban board).
3. Open the file again.

**Comment by mgmeyers** [comment]
Thanks @fathyar! Found what was going on here and made some updates to fix. Let me know if you still have any issues.
