### ISSUE TITLE
[Feature]: hope count the number of cards by column and kanban

### ISSUE THREAD

**Issue by SeyeeL** [mgmeyers/obsidian-kanban#482]
### Goal or desired outcome of this feature

rt

### Describe the feature

rt

**Comment by mgmeyers** [comment]
@SeyeeL I've added a count of the number of cards in a list up at the top. I have plans to expand on this some more, but this is at least a step in that direction.

<img width="282" alt="Screen Shot 2022-04-04 at 8 05 06 PM" src="https://user-images.githubusercontent.com/2694747/161670868-8777447a-0765-433e-816d-dad0fb6a32c5.png">
