### ISSUE TITLE
Preview Mode does not work in Kanban

### ISSUE THREAD

**Issue by Missionary2112** [mgmeyers/obsidian-kanban#488]
### Describe the bug

When I hover on a link in Kansan, most of the card pop up the preview except for particular card; it did not show any content inside. I also tried deleting the card and adding again the same note by dragging the file from File Explorer on to Kanban List. It still does not work.

### Expected Behavior

The Preview window should show the content when hovered. 

### Steps to reproduce

1. Drag a file onto Kanban board
2. Hover cursor over that file
3. See error: Preview Window pop-up show no content

![2022-03-19 at 12 47 43 AM (Obsidian)](https://user-images.githubusercontent.com/98799613/159112623-f8f3fa76-71e7-4430-adf0-909545c6ceee.jpg)

### Operating system

macOS

**Comment by mgmeyers** [comment]
Hmm, I'm unable to reproduce this @Missionary2112. Does it work with the default theme?

**Comment by Missionary2112** [comment]
Hi @mgmeyers, I just check the file this morning. And everything works fine now. That's weird but thank you for your investigation.
