### ISSUE TITLE
[Bug]: checkboxes in cards are not displayed anymore

### ISSUE THREAD

**Issue by jhilti** [mgmeyers/obsidian-kanban#490]
### Describe the bug

With the new Release Obsidian v0.14.2 the checkboxes in the cards are not displayed anymore. The checkboxes are therefore also not clickable anymore.
- Kanban  Version 1.2.29

### Expected Behavior

We should see the checkboxes.

### Steps to reproduce

update to the new Obsidian v0.14.2 and try to include checkboxes (- [ ] make bug report). On my system it appears as normal markdown text.

### Operating system

Windows

**Comment by jhilti** [comment]
The checkboxes that can be used with the setting _Display card checkboxes_ are displayed, but not a list of checkboxes within a card.

**Comment by Criamos** [comment]
Came here to confirm this issue in Obsidian v0.14.2 with Kanban 1.2.29, but with one added observation:
If you embed/transclude paragraphs inside a card that have a task-list, e.g. by using
`![[Link_to_my_file#first_paragraph]]` you'll notice that those checkboxes are displayed, but look cut-off and are only partially visible.

**Comment by PurpleGuitar** [comment]
Confirmed in Obsidian 0.14.2 on with Kanban 1.2.29 on Windows 10 with no themes or snippets activated.  The element classes in the generated HTML appear to be correct (that is, they're being generated with the `task-list-item` class and have a checkbox element).  So maybe it's an issue with the Kanban plugin CSS?

![image](https://user-images.githubusercontent.com/1095575/160002813-14e37d10-0637-4bcb-ab6a-38574e41bfab.png)

![image](https://user-images.githubusercontent.com/1095575/160003290-c3f20196-0034-49ba-b879-d4dd2943ece0.png)

**Comment by jhilti** [comment]
It seems that indented task-lists are partly visible, double indented task-lists are fully visible.
probably a display problem?

![image](https://user-images.githubusercontent.com/102165727/160083270-1750e83f-024d-47f9-86bd-e67f544aca96.png)

**Comment by huehou** [comment]
It seems like a margin issue, since the checkbox becomes visible with the following (at least on my side):

``` 
.kanban-plugin__item-markdown ul > li.task-list-item .task-list-item-checkbox {
    margin-left: 4px;
}

.kanban-plugin__markdown-preview-view ul > li.task-list-item .task-list-item-checkbox {
    margin-left: 4px;
}
```

![image](https://user-images.githubusercontent.com/33952234/160531835-dda8fc55-677c-410b-b634-ba7996d3a4ad.png)

**Comment by cuamckuu** [comment]
So, here is fix based on [huehou](https://github.com/huehou) styles

1. Go to: `Settings > Appearance > CSS Snippets` 
2. Click on `Open snippets folder`
3. Create new file `kanban_checboxes.css` and paste following:
```css
.kanban-plugin__item-markdown ul > li.task-list-item .task-list-item-checkbox {
    margin-left: 4px;
}

.kanban-plugin__markdown-preview-view ul > li.task-list-item .task-list-item-checkbox {
    margin-left: 4px;
}
``` 
4. Return to: `Settings > Appearance > CSS Snippets`
5. Click `Reload Snippets`
6. Enable new `kanban_checboxes` snippet
