### ISSUE TITLE
[Feature]: A way to mark a header that shouldn't be considered a list?

### ISSUE THREAD

**Issue by sable-starflower** [mgmeyers/obsidian-kanban#492]
### Goal or desired outcome of this feature

I like having kanban boards that can also be viewed as markdown files, where I used multiple header levels to structure the contents and have text and other data mixed in with the list of tasks. Is there currently a way to prevent every header in the file from being considered a list?

### Describe the feature

I think the most straightforward ways of implementing this would be one of:

- a tag that could be included in headers that indicates whether a header should be considered a list 
- a tag that indicates it should *not* be a list
- frontmatter that indicates which headers should be lists
- frontmatter that indicates which headers should not be lists

### Can you think of any alternatives or work-arounds?

I could use something other than headers to structure the markdown, but this makes converting existing markdown documents to kanban boards harder.

**Comment by beviz** [comment]
I have the same problem. I have installed a plugin that will automatically sync the file name to an H1 header, but I don't want it to be displayed on the board. 

I think it would be better if there is a dropdown that allows users to set which level of headers should be collected as lists.

**Comment by mgmeyers** [comment]
@sable-starflower There is currently no way to do this. The plugin is very strict about how the markdown is formatted to make sure there's no data corruption. I'll try and think about ways around this in the future, though

**Comment by ferguscollins** [comment]
I feel like this isn't a throwaway request. It is common to have tasks listed in the same note as other project details especially at a high level, and separating out the tasks from the rest of the project note seems arbitrary.

Currently I just collapse the H1 swimlane but I have recently begun tracking larger projects in obsidian with multiple header levels before the tasks begin, and it makes the Kanban view quite messy especially on mobile.

A signal header with a definable name in settings with a sensible default like "Tasks," "Task lists," or "Kanban" could be the starting point with all subheaders being swimlanes. The next header that is at the same level as the signal header would indicate the end of the task swimlanes.

In the below example markdown, the Kanban board would only show three swimlanes for "Ready," "In progress," and "Closed."

```
# Title

## Summary

### Detail 1

### Detail 2

## Kanban

### Ready

### In progress

### Closed

## Other notes
```

Does this sound feasible? Do you see the value added by a feature like this? I am hesistant to reopen this issue before there is recognition of potential benefit here.
