### ISSUE TITLE
[Bug]: "Create new note from card" fails to link if card text contains links

### ISSUE THREAD

**Issue by nickynicolson** [mgmeyers/obsidian-kanban#494]
### Describe the bug

I have a kanban board containing a card which has a link to an existing note in its text, e.g.
"Arrange meeting with [[person_x]]" 
When use the kanban plugin feature to create a new note from the card, the card text on the kanban board is wrapped in double square brackets but fails to link as embedded links are not permitted in note titles:
"[[Arrange meeting with [[person_x]]]]" 

### Expected Behavior

Links should be stripped from the card text when creating the new note and when converting the card text to a link to the new note, i.e.
"Arrange meeting with [[person_x]]" 
Should be replaced with:
"Arrange meeting with person_x"  when creating the new note, allowing the card to link to [[Arrange meeting with person_x]]

If the link syntax includes alternative link text this should be used, i.e.:
"Arrange meeting with [[person_x|X]]" 
should be replaced with:
"Arrange meeting with X" 

### Steps to reproduce

1. Create a note titled dummy note
1. Create new kanban board
1. Create a card on the kanban board containing the text "Do something with [[dummy note]]"
1. Check that the card displays the "dummy note" part of the card text as a clickable link to the "dummy note" page
1. Click the "more options" menu on the card and select "Create new note from card"
1. Observe that:
    i. the new note is created with illegal embedded link syntax 
    ii. that the card text is wrapped in double square brackets, but does not present as a clickable link.

### Operating system

Windows

**Comment by mgmeyers** [comment]
@nickynicolson This should be fixed now. Let me know if you run into any issues with it
