### ISSUE TITLE
Bug: Plugin ID mismatch

### ISSUE THREAD

**Issue by SuperTempAccount** [mgmeyers/obsidian-kanban#496]
Hi,

## Describe the bug
I'm no longer able to update or install the app. I get a "Plugin ID mismatch" error. 

## Relevant errors (if available)
Plugin ID mismatch.
![plugin id mismatch](https://user-images.githubusercontent.com/83566267/160914939-3fded997-0a87-4ce8-a5b7-fa30a0985997.png)

## Operating system
Windows 10
Obsidian 0.14.2

## Steps to recreate:
1. Go to community plugins.
2. Click on update (if already installed) or install
3. Error

## Tried:
1. Installing other plugins successfully
2. Restarting Obsidian

Sweet :)

**Comment by say4n** [comment]
Can reproduce the same behaviour on macOS 12.3 with Obsidian 0.14.2.

**Comment by ahmetasabanci** [comment]
I'm not able to update on iOS too. It just says "failed to install" but probably it's the same error.

**Comment by mgmeyers** [comment]
Apologies all, this should be fixed now. Give it a few minutes and try updating again.

**Comment by SuperTempAccount** [comment]
Cool thank you :) It's working now
