### ISSUE TITLE
[Feature]: Count and display number of cards in a list

### ISSUE THREAD

**Issue by apolaine** [mgmeyers/obsidian-kanban#499]
### Goal or desired outcome of this feature

Personal goal is that I keep track of all my coachees on my kanban, so having a number of how many are active, etc. would be super useful. But I can also imagine people would be find it useful to track any to-do items, etc. in their lists too.

### Describe the feature

Ideally just an option in the settings to turn on the count number either displayed at the top or bottom bar of the list.

**Comment by mgmeyers** [comment]
@apolaine I've added a count of the number of cards in a list up at the top. I have plans to expand on this some more, but this is at least a step in that direction.

<img width="282" alt="Screen Shot 2022-04-04 at 8 05 06 PM" src="https://user-images.githubusercontent.com/2694747/161670868-8777447a-0765-433e-816d-dad0fb6a32c5.png">

**Comment by apolaine** [comment]
Brilliant! Thank you.
