### ISSUE TITLE
[Bug]: Dates and tags are no longer hidden.

### ISSUE THREAD

**Issue by dninemfive** [mgmeyers/obsidian-kanban#505]
### Describe the bug

When adding dates and tags to cards, the internal formatting is visible: 
![image](https://user-images.githubusercontent.com/11084010/162266945-b00115d6-a769-4a03-99e9-0c4fd7bcc595.png)

### Expected Behavior

Before updating, the text
```
@{2022-04-08}
#math23a
``` 
in the above screenshot was hidden, with the date and tag only displayed in the detail text at the bottom, which appears to still be working.

Notably, this card also has an associated time, which is properly hidden:
![image](https://user-images.githubusercontent.com/11084010/162267277-b3de51df-d406-4a5f-8cb0-7b0e3e1402fc.png)

### Steps to reproduce

Add a date using the `@{yyyy-mm-dd}` notation or a tag using the `#tag` notation to any card.

This change occurred after updating from 1.2.28 to 1.2.39. I'm using the default dark theme.

### Relevant errors (if available)

```shell
No errors were visible in the console.
```

### Operating system

Windows

**Comment by dninemfive** [comment]
Skimming the commit history, this may be related to the fixes for #430 and #456.

**Comment by mgmeyers** [comment]
@dninemfive Just to check, how are these settings set in your board settings, or global kanban settings?

<img width="780" alt="Screen Shot 2022-04-07 at 11 18 27 AM" src="https://user-images.githubusercontent.com/2694747/162270247-0e2e3875-4366-4042-b717-af4471402e75.png">


<img width="772" alt="Screen Shot 2022-04-07 at 11 18 45 AM" src="https://user-images.githubusercontent.com/2694747/162270295-8c7f4577-8e2a-4f0c-bd89-9f68db67b8b6.png">

**Comment by dninemfive** [comment]
Both toggles were off. Toggling them on hid tags entirely (i.e. both the text and the summary thing at the bottom) and did not fix the issue with the dates.

**Comment by mgmeyers** [comment]
@dninemfive There are two ways you can set settings for Kanban boards. The first is in the obsidian settings pane, and the other is by clicking on the "open board settings" button when a kanban board is open. The first option will set settings for all kanban boards (global settings) and the second option will overwrite those settings for a particular board (board settings). You may need to check these two levels of settings to get the configuration how you'd like it, as there are several settings for how to display tags and dates.

These settings should produce what you're looking for:

<img width="928" alt="Screen Shot 2022-04-10 at 10 15 11 AM" src="https://user-images.githubusercontent.com/2694747/162631362-63a50f24-d0ff-4f84-ab44-5d2c1d37ee33.png">

<img width="945" alt="Screen Shot 2022-04-10 at 10 16 03 AM" src="https://user-images.githubusercontent.com/2694747/162631393-08bb380d-7cda-4d42-8839-907a59757056.png">

<img width="257" alt="Screen Shot 2022-04-10 at 10 17 42 AM" src="https://user-images.githubusercontent.com/2694747/162631462-cd251f71-a5f6-4445-96e8-543789d53887.png">

<img width="254" alt="Screen Shot 2022-04-10 at 10 17 27 AM" src="https://user-images.githubusercontent.com/2694747/162631449-cfd5e66c-3c41-4722-a2b6-30577d57bf99.png">
