### ISSUE TITLE
[BUG] :  Callout is deleted when  Switch from kanban to Markdown

### ISSUE THREAD

**Issue by Akiyam-hub** [mgmeyers/obsidian-kanban#506]
### [BUG report] 

Thanks for a great plugin!

I have a checklist in one file and a
memos and so on.

I would be very happy if the Heading is still there!

### version
Obisidian version: v0.14.2
OS: macOS MontereyVersion 12.2.1

### Reproduction

ex, this markdown mode file is edited
```markdown
---

kanban-plugin: basic

---

>[!note] # title
>これはテスト.
>


## Tasks

- [ ] task1
- [ ] task2


## Sometimes

- [ ] task3

```

I used「Toggle between Kanban and markdown mode」to  Switch from markdown to kanban,

and Moving Cards in Kanban-mode

when  use「Toggle between Kanban and markdown mode｣ to  Switch from kanban to Markdown.
callout text of no list is deleted.
```markdown

---

kanban-plugin: basic

---

## Tasks

- [ ] task1


## Sometime
- [ ] task2
- [ ] task3

%% kanban:settings
``
{"kanban-plugin":"basic"}
``
%%

```

**Comment by mgmeyers** [comment]
Hi @Akiyam-hub. This is not so much a bug, but the way that the plugin works. It relies on a very specific markdown structure to create the kanban boards and will overwrite any markdown not in the kanban format. In the future, you'll be able to embed kanban boards into other notes and add markdown around them. But at the moment this is not possible.
