### ISSUE TITLE
[Bug]: Cannot create custom internal link for Note in board

### ISSUE THREAD

**Issue by SilkyPantsDan** [mgmeyers/obsidian-kanban#509]
### Describe the bug

First - thanks for the awesome plugin!

I have created a note to add to my board, and want to have a custom link in the card details. Unfortunately, it seems I cannot edit the link as [per the docs](https://help.obsidian.md/How+to/Internal+link) and when I edit the link to `[[Internal Note|Custom Link]]` it will reset this to the plain note link title of `Internal Note`. If I edit the board document outside of Obsidian it will render correctly on the board.

Using version 1.2.39

### Expected Behavior

The board editor should allow me to add custom links to internal notes.

### Steps to reproduce

1. Create Board
2. Create a card, and convert it to note
3. Edit the card to give it a custom link
4. Notice the card defaults back to the original card title

I have tested on both macOS and Windows, and I get the same behaviour

### Operating system

macOS

**Comment by mgmeyers** [comment]
@SilkyPantsDan This is actually related to a different bug. You _can_ add an alias, but you have to press `esc` if the autocomplete dropdown is open, or else it will autocomplete the non-aliased version.

**Comment by SilkyPantsDan** [comment]
Thanks, @mgmeyers  - Happy to close this then in favour of the other one then (assuming this is #388?)
