### ISSUE TITLE
[Feature]: Drag & Drop existing list to another kanban

### ISSUE THREAD

**Issue by graydwarf** [mgmeyers/obsidian-kanban#511]
### Goal or desired outcome of this feature

I want to move an existing list of kanban cards to another kanban instance in another project folder. 

### Describe the feature

User has ability to drag and drop a card or a list to another kanban. You can almost do it. You can drag the column to another kanban in your obsidian file explorer but when you drop it, nothing seems to happen. 

### Can you think of any alternatives or work-arounds?

Alternatively or in addition, maybe a copy/paste option from the list menu, or an export to option (file, kanban, image per other requests).

### Screenshots, mockups, or videos

Example image shows trying to move untitled list with ufo card from asterboids to into-the-dark kanban.
![image](https://user-images.githubusercontent.com/6061635/162968983-c791f09e-f957-4cc8-96e0-74d7d25712c3.png)

**Comment by rrherr** [comment]
@graydwarf When I open two kanbans in two panes, then I can drag & drop lists and cards from one kanban to the other! The UX is a little finnicky, but it's so exciting that it works!

**Comment by graydwarf** [comment]
@rrherr That's a good enough workaround and it seems like that's the preferred way to do it since you can see and choose where it will go. Thanks!
