### ISSUE TITLE
[Bug]: settings dropdown overflows incorrectly

### ISSUE THREAD

**Issue by SoloJessy** [mgmeyers/obsidian-kanban#520]
### Describe the bug

When you click into the dropdowns in the kanban settings page, if the listed options exceed the height of the dropdown, 200px, it does not over flow correctly until 300px. at the same time, you can not see the options inside those 100px.

It should be fairly simple to fix, since the dropdowns are using the default div display setting of block. Setting it to flex and a flex-direction of column should make it work properly. though im not sure if thats the best way to fix it.

### Expected Behavior

You should be able to see all options in the drop down with the scroll.

### Steps to reproduce

Having sufficient options in the drop down should result in this bug.

### Operating system

Linux

**Comment by mgmeyers** [comment]
@SoloJessy can you share a screenshot of what you're seeing?

**Comment by SoloJessy** [comment]
When i run my screenshot program, the dropdown auto closes. so i'll need to find a way to do that first

**Comment by SoloJessy** [comment]
![Screenshot_2022-04-18_21-15-18](https://user-images.githubusercontent.com/89361614/163870988-0a85f7e1-6a87-4c34-8e0b-da8ada2a69ad.png)
![Screenshot_2022-04-18_21-15-13](https://user-images.githubusercontent.com/89361614/163870991-336fe6db-52a9-4592-bc44-8def707a784a.png)

**Comment by SoloJessy** [comment]
Can see the scroll bar extend further than the visible box, cutting content off.

I tested with my custom theme. and adding the display: flex and flex-direction: column fixed it.

**Comment by SoloJessy** [comment]
![Screenshot_2022-04-18_21-18-21](https://user-images.githubusercontent.com/89361614/163871388-cba9ff39-8b05-4e41-815a-9c88dcc749c1.png)
This is the fixed version in my theme.

The messed up scroll is the same on all dropdowns, 
the note template dropdown is off too due to the search bar, and the flex fix works for that as well
