### ISSUE TITLE
[Bug]: Dragging cards with resized image metadata expands image

### ISSUE THREAD

**Issue by GovSat1** [mgmeyers/obsidian-kanban#522]
### Describe the bug

When dragging a card with a linked metadata field containing an image that has been resized, using Obsidian's `|size` format, the image expands to the specified size. IE a linked metadata field containing `![[photo.png|1000]]`. This makes moving the card difficult (especially on mobile).

When the photo has not been resized (`![[photo.png]]`), the image is not expanded. I specify image size within the note for formatting/layout purposes.

Before dragging:
![image](https://user-images.githubusercontent.com/36019883/164111891-cde4b0da-765c-4775-bf1d-824860bd3a97.png)

While dragging:
![image](https://user-images.githubusercontent.com/36019883/164111948-50c94aeb-3eae-453e-b322-1f967187dd3d.png)

Linked field format:
![image](https://user-images.githubusercontent.com/36019883/164112270-66b654ca-d3f5-4c74-bdc3-f809444c7a5a.png)

### Expected Behavior

The image should not expand when dragging a card

### Steps to reproduce

- Create a linked metadata field
- Link card to note and paste a large image into the note field
- Modify the size by using `|1000` after the image
- Attempt to drag the card and the image should expand

### Operating system

macOS

**Comment by mgmeyers** [comment]
Hi @GovSat1 I am unable to reproduce this. Does this happen for you on the default theme?

**Comment by GovSat1** [comment]
> Hi @GovSat1 I am unable to reproduce this. Does this happen for you on the default theme?

Good catch, it appears to be specific to Minimal Theme.
