### ISSUE TITLE
[Bug]: Serif font in Kanban mode since Obsidian v0.14.7

### ISSUE THREAD

**Issue by nununo** [mgmeyers/obsidian-kanban#528]
### Describe the bug

Since Obsidian v0.14.7, the Kanban boards are rendered with a Serif font even though the theme is using a Sans Serif font.

This also happened in Nord Theme and, after [discussing it with Licat](https://discord.com/channels/686053708261228577/716028884885307432/968545402095796285) in Discord, I posted this issue in Nord theme's and it is now solved. I hope these references are helpful.

Thank you. Regards.

### Expected Behavior

The Kanban board should be rendered with a Sans Serif font (when using Nord theme). This is what was happening util v0.14.7.

### Steps to reproduce

Open a Kanban board in V0.14.7 with Kanban v1.2.39.

### Operating system

macOS

**Comment by dafqs** [comment]
A problem for me too. Other settings are also no longer valid.

**Comment by nununo** [comment]
Perfect. Thanks!
