### ISSUE TITLE
[Bug]: Note template dropdown not showing all templates

### ISSUE THREAD

**Issue by bblais** [mgmeyers/obsidian-kanban#535]
### Describe the bug

I'm trying to choose a template for the note template in the board settings, but it is only showing about 1/2 of my templates, so I can't choose the one I want.  I seems to be stopping at some point, not skipping any in the middle, but not showing anything past a certain point.  

### Expected Behavior

I should see all of my templates in my template folder!

### Steps to reproduce

- Board settings
- Click on Note Template

### Operating system

macOS

**Comment by daviehh** [comment]
Add: the same goes for the dropdown ui for choosing the note folder, it does not scroll and only shows some of my folders:

<img width="713" alt="Screen Shot 2022-06-05 at 3 00 30 PM" src="https://user-images.githubusercontent.com/25255906/172066416-a0721180-d292-42cd-b8a1-ed8ea76b9777.png">
