### ISSUE TITLE
[Bug]: Moving Cards is impossible on Windows 11 devices using drag and drop 

### ISSUE THREAD

**Issue by tillfalko** [mgmeyers/obsidian-kanban#537]
### Describe the bug

Rearranging cards in a List using a touchscreen device on Windows is very inconsistent. You can move cards up but not down. Moving Cards between lists is outright impossible. This happens with both pen and finger input.

### Expected Behavior

Cards should be both rearrangeable and movable via drag and drop.

### Steps to reproduce

1. Open a Kanban board on a Windows device with a touchscreen
2. Try to drag Cards between Lists

Here is a video of the bug:
https://youtu.be/RT73soF0K-Y

### Operating system

Windows

**Comment by mgmeyers** [comment]
I don't have a windows device, but this may be fixed now on the latest insider's build (obsidian 0.15.3)

**Comment by TillFalko** [comment]
I do not have access to the Obsidian insider builds and so I cannot test this.

**Comment by tillfalko** [comment]
This issue is fixed in the latest version. Closing.
