### ISSUE TITLE
[Bug]: Issues with DB-folder plugin

### ISSUE THREAD

**Issue by antomonte** [mgmeyers/obsidian-kanban#555]
### Describe the bug

I don't know whether the issue is due to Kanban or DB-folder plugin, but the combination of both arises a problem.

Please take a look at where I described it:
https://github.com/RafaelGB/obsidian-db-folder/issues/141

### Steps to reproduce

https://github.com/RafaelGB/obsidian-db-folder/issues/141

### Operating system

Windows

**Comment by RafaelGB** [comment]
This was solved by dbdoler side. You can close the issue
