### ISSUE TITLE
licenses inconsistency

### ISSUE THREAD

**Issue by SoftwareEthicsResearcher** [mgmeyers/obsidian-kanban#560]
Hello, I am doing research in software engineering ethics. I found different licenses in repo. May I know which license repo follows? I would like to highlight this as a transparency concern.
•  Repo License: GNU General Public License v3.0, 
o  Different license : MIT in package.json.
 
Regards, Software Ethics Researcher.

**Comment by mgmeyers** [comment]
Hi there. main.js is a bundled file that includes the required licenses of node modules used by this project. obsidian-kanban is GPL 3 licensed.
