### ISSUE TITLE
[Bug]: Duplicate lane in 0.15.3.

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-kanban#568]
### Describe the bug

When I used insider verison of Obsidian, and then open kanban in new window. Kanban looks something duplicated. I repro this in sandbox vault.

https://user-images.githubusercontent.com/13215013/176070449-97b53340-f4a1-4c65-90ed-9ae34c8f2634.mp4

![image](https://user-images.githubusercontent.com/13215013/176070697-f3ddc22f-2939-4fa6-84c2-9e2d05b6c627.png)

### Expected Behavior

Lane won't duplicate itself.

### Steps to reproduce

1. Use Obsidian 0.15.3;
2. Open Kanban in new window.
3. Gotcha.

### Operating system

Windows

**Comment by mgmeyers** [comment]
@Quorafind I wasn't able to reproduce this, but I pushed a new version with several fixes related to popout windows. Can you see if this is still an issue for you?

**Comment by pjeby** [comment]
It's still an issue for me with 1.3.4. I don't have to do anything special to reproduce it: all Kanbans show a second, identical lane below the first if I scroll down.

**Comment by mgmeyers** [comment]
Oh, I see it now. Thanks for the clarification @pjeby

**Comment by mgmeyers** [comment]
@Quorafind @pjeby This should be fixed now. Please let me know if you run into any other popout related weirdness
