### ISSUE TITLE
[Bug]: Create New Kanban in file-explorer will cover the file-explorer in 0.15.3.

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-kanban#569]
### Describe the bug

When creating new kanban file in the context menu of folder, the kanban file will cover the file-explorer and need to restart obsidian to make the file-explorer come again.

Here is the video:

https://user-images.githubusercontent.com/13215013/176071989-55e2fb8c-3e12-4fa2-a18a-df46dd9650f7.mp4

### Expected Behavior

The kanban file is opened in the main windows rather than cover the file-explorer

### Steps to reproduce

1. Use the version 1.3.2 of Obsidian kanban.
2. Right click on the folder.
3. Select new kanban in the context menu.
4. See error.

### Operating system

Windows

**Comment by RafaelGB** [comment]
hi @mgmeyers, I have the same problem with https://github.com/RafaelGB/obsidian-db-folder and I want to ask you how you fixed it

**Comment by RafaelGB** [comment]
Okay, fixed modifying deprecated activeLeaf by getMostRecentLeaf of workspace service. Thank for your plugin BTW, was an inspiration for mine
