### ISSUE TITLE
Autocomplete wonkiness in 0.2

### ISSUE THREAD

**Issue by bobbleheadjoe** [mgmeyers/obsidian-kanban#57]
As of version 0.2, double brackets no longer trigger autocomplete in the card title - UNLESS there is an additional character at the front of the line.

For example, this text on a new card will NOT trigger autocomplete:

[[H

But this one will:
_[[H

Suggestions for autocomplete do no filter though - just gives a giant list of titles.

Currently using app version 0.11.13

**Comment by mgmeyers** [comment]
Thanks for the heads up @bobbleheadjoe. This should be fixed now! Let me know if you still have issues with it.

**Comment by bobbleheadjoe** [comment]
Works as intended :) Thanks!
