### ISSUE TITLE
[Bug]: Wikilink completion includes extra `]]` when bracket pairing is off

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#570]
### Describe the bug

When Obsidian's wikilinks setting is on and bracket pairing is off, completing a link in a Kanban to a document named `X` results in the string `[[X]]]]` being inserted.

### Expected Behavior

The extra `]]` should not appear.

### Steps to reproduce

As described above.

The issue is that the extra `output.push(']] ')` at [line 139 of file.picker.ts](https://github.com/mgmeyers/obsidian-kanban/blob/8dff95ae9e34a29f654c55175b0f3b3ca90be3ab/src/components/Editor/filepicker.ts#L139) is never necessary, since a complete link was already inserted in a preceding step.

### Operating system

Windows

**Comment by mgmeyers** [comment]
Ah, you're right. Pushed a new version with a fix

**Comment by pjeby** [comment]
Thanks!
