### ISSUE TITLE
[Feature]: command (and hotkey) for Search function

### ISSUE THREAD

**Issue by dexx086** [mgmeyers/obsidian-kanban#574]
### Goal or desired outcome of this feature

Would be great if a hotkey could be set for the Search functionality.

### Describe the feature

Right now search is only accessible through the **header buttons**, but not through a command (and therefore not through an assignable hotkey).

Would even better if Obsidian't basic "Search current file" command's key could work for kanban's Search functionality as well, but I guess that has some technical difficulties as that command not even pops up in the commands panel when kanban board is visible.

**Comment by mgmeyers** [comment]
@dexx086 Hotkeys broke in a recent version of Obsidian, but should now be fixed in 0.15.3 and the latest version of this plugin. The default "find" command (cmd+f on mac) opens the search input.

**Comment by dexx086** [comment]
@mgmeyers Thanks for the info, then I'll wait for that release, as right now only 0.14.15 is the current publicly available version which I have access for.
