### ISSUE TITLE
[Bug]: Can't get out of error state if Kanban visible in more than one pane

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#578]
### Describe the bug

If a Kanban enters an error state due to a file error, you cannot retry without first navigating away from the file in all open panes/windows/popovers.

### Expected Behavior

Navigating to a Kanban (i.e. setState, switching modes, etc.) whose file is in an error state should probably retry reading the file.

### Steps to reproduce

The specific thing I've been doing is debugging pane relief forward/back navigation, and doing that usually causes the file load to time out, getting the error.

But I was also able to get the error by first corrupting the YAML of a kanban board, then trying to put it back, with two copies open in the same popout.  The result is that I can switch to Kanban mode on the (uncorrupted) file, but it shows blank with no error, and even navigating both panes away and back does not allow the correct board state to load.  An error occurred in the console at some point, which I've supplied below.

Once this error occurred for the file, the only way to get it to show up again as a Kanban board was to restart Obsidian (just switching workspaces didn't help).

### Relevant errors (if available)

```shell
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'cloneNode')
    at eval (plugin:obsidian-kanban:58:7017)
    at Object.Ni [as useMemo] (plugin:obsidian-kanban:19:78414)
    at gt.eval [as constructor] (plugin:obsidian-kanban:58:7003)
    at gt.eE [as render] (plugin:obsidian-kanban:6:8852)
    at nl (plugin:obsidian-kanban:6:6533)
    at tf (plugin:obsidian-kanban:6:2768)
    at nl (plugin:obsidian-kanban:6:6803)
    at tf (plugin:obsidian-kanban:6:2768)
    at Zw (plugin:obsidian-kanban:6:8035)
    at nl (plugin:obsidian-kanban:6:6986)
```

### Operating system

Windows

**Comment by pjeby** [comment]
Oh, and this is on 1.3.5 and Obsidian 0.15.3

**Comment by mgmeyers** [comment]
Thanks @pjeby 1.3.6 should fix this.
