### ISSUE TITLE
Unable to open the vault with Kanban plug-in

### ISSUE THREAD

**Issue by Missionary2112** [mgmeyers/obsidian-kanban#582]
### Describe the bug

I cannot open the vault (only in iOS devices) if I turn on Kanban Plug-in.

### Expected Behavior

The vault should be opened and the Kanban should work on iOS.

### Steps to reproduce

1. Turn on Kanban plug-in
2. Errors: 
- Cannot enter Kanban file.
- Cannot open the vault
![IMG_6827](https://user-images.githubusercontent.com/98799613/177390406-fab4a306-e9cb-48a3-8e0f-ca3f288fad26.PNG)

### Operating system

iOS

**Comment by mgmeyers** [comment]
@Missionary2112 Is your vault synced from desktop? You somehow have the latest version of the plugin on mobile which is only available on the insider desktop release.

**Comment by Missionary2112** [comment]
My vault is synced across multiple devices via iCloud. But if I turned off Kanban plug-in, everything works fine.

**Comment by Oblique82** [comment]
I am in the same situation as well. I do have insider access. I am only on Obsidian 1.2.2 on iOS and there is no testflight update available yet - do I need to wait for the next inside Obsidian app update?

**Comment by mgmeyers** [comment]
@Oblique82 and @Missionary2112 try updating the kanban plugin from your mobile device. That should install the correct version. I would avoid updating the plugin on desktop until the new version of the mobile app is released

**Comment by mgmeyers** [comment]
This should be fixed with the latest version of obsidian mobile and desktop
