### ISSUE TITLE
[Bug]: Auto close feature issue with new move to new window feature of obsidian

### ISSUE THREAD

**Issue by Archie-2021** [mgmeyers/obsidian-kanban#599]
### Describe the bug

I open a Kanban in a new window and have some note obsidian window open. when i insert a "[" what usually happens is that the autopair feature close it. but when i do it in a Kanban card the added "]" appears in the main windows which is not active rather than the Kanban i am editing right now. i am not sure why this happens but it seems to me that it is happening only if i am writing to a Kanabn card 

### Steps to reproduce

explained above

### Operating system

Windows

**Comment by mgmeyers** [comment]
This should be fixed in the latest release. Let me know if you still run into issues with it
