### ISSUE TITLE
[Feature]: Kanban Card Description

### ISSUE THREAD

**Issue by DatsGabs** [mgmeyers/obsidian-kanban#604]
### Goal or desired outcome of this feature

Add description to kanban cards

### Describe the feature

Be able to write some description and to see it in the kanban board

**Comment by AB1908** [comment]
Can you clarify what you're asking for here? I can add descriptions to my card.
![image](https://user-images.githubusercontent.com/14124383/182006325-f3d32715-f69a-49c5-be32-c4606cd885d6.png)
