### ISSUE TITLE
[Bug]: "[[]]" can't insert the link in card after updated v1.3.12

### ISSUE THREAD

**Issue by hanpei** [mgmeyers/obsidian-kanban#606]
### Describe the bug

it can't insert the link in card after updated v1.3.12
it seems like only search the file in assets folder and root folder
<img width="334" alt="image" src="https://user-images.githubusercontent.com/4035340/182084865-bbc1ec21-fe47-4639-a44b-b4209caa79e8.png">

### Steps to reproduce

1. Add a card
2. typing "[[]]" 
3. something wrong with the result

### Operating system

macOS

**Comment by Archie-2021** [comment]
I have the same issue, hope get fixed soon.

thank you for this supper useful plugin

**Comment by mgmeyers** [comment]
@hanpei & @Archie-2021 What version (including installer version) of obsidian are you on? Also, are there any errors in the developer console when you try to add a link?

**Comment by hanpei** [comment]
**version:**
v0.15.9
**installer version**
v0.14.6

**console error:**
<img width="724" alt="image" src="https://user-images.githubusercontent.com/4035340/182513494-f7762120-7ae7-45f3-a72b-8c607910b5bd.png">

```
Uncaught DOMException: Failed to execute 'appendChild' on 'Node': Only one element on document allowed.
    at window.createEl (app://obsidian.md/enhance.js:1:8310)
    at HTMLDocument.Node.createEl (app://obsidian.md/enhance.js:1:7398)
    at HTMLDocument.Node.createDiv (app://obsidian.md/enhance.js:1:7466)
    at QS (plugin:obsidian-kanban:24:85167)
    at Object.template (plugin:obsidian-kanban:24:85714)
    at Pu.renderTemplate (plugin:obsidian-kanban:26:1771)
    at Lu.render (plugin:obsidian-kanban:26:1323)
    at new Pv (plugin:obsidian-kanban:26:7145)
    at eval (plugin:obsidian-kanban:26:3688)
    at Array.map (<anonymous>)
```

**Comment by hanpei** [comment]
more screen shot:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/4035340/182514028-14c67e4b-778a-4572-8631-c838eccd61d8.png">

**Comment by mgmeyers** [comment]
Perfect, thanks @hanpei. Update the plugin and let me know if you still have issues with this.

**Comment by Archie-2021** [comment]
> @hanpei & @Archie-2021 What version (including installer version) of obsidian are you on? Also, are there any errors in the developer console when you try to add a link?

**Comment by Archie-2021** [comment]
> @hanpei & @Archie-2021 What version (including installer version) of obsidian are you on? Also, are there any errors in the developer console when you try to add a link?

now i am trying to install the new version and it fails to install all the time.

**Comment by mgmeyers** [comment]
Ah, something happened to the release. Looks like it installs correctly now

**Comment by Archie-2021** [comment]
> Ah, something happened to the release. Looks like it installs correctly now

Yes, now it both install correctly and the issue with links is solved too, thank you

**Comment by hanpei** [comment]
it's worked now, thanks a lot.
