### ISSUE TITLE
[Bug]: Out-of-order initialization for ScrollManager

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#609]
### Describe the bug

At startup or workspace load, I sometimes get a blank Kanban and an error in the console (see trace below).

The issue is that ScrollManager assumes its parent has initialized before it, but it is apparently possible for this not to be the case.

In my local copy, I've patched its pollForNodes method to also check for the `parent.observerHandlers` property so it won't initialize until after the parent does.  i.e.:

```ts
pollForNodes(getScrollEl: () => HTMLElement | null) {
  if (!getScrollEl() || (this.parent && !this.parent.observerHandlers)) {
```

But since I don't know why this would happen out of order, I'm not sure if this is the right way to fix it.

### Steps to reproduce

I don't know how to reproduce it on purpose, but it has mostly happened at Obsidian start or workspace load.

### Relevant errors (if available)

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at ScrollManager.registerObserverHandler (VM190 plugin:obsidian-kanban:24572:27)
    at EntityManager.initNodes (VM190 plugin:obsidian-kanban:11655:25)
    at EntityManager.pollForNodes (VM190 plugin:obsidian-kanban:11645:12)
    at eval (VM190 plugin:obsidian-kanban:11643:40)
```

### Operating system

Windows

**Comment by mgmeyers** [comment]
Yeah, pretty strange that this would happen. I've noticed there are some quirks in the way preact initializes components vs react, which is why I have to poll for nodes in the first place. I'll go with your fix for now until I can figure out what's going on.

**Comment by pjeby** [comment]
I suspect it has to do with timing -- the version that had the problem is the version with my RAF/timeout scoping fixes, and during workspace load Obsidian does some funky stuff with what window things are in and whether stuff is mounted in the DOM or not.  I believe it's possible for activeWindow to jump around a bit during workspace load with multiple windows, and that could affect the order of callbacks, especially if any of the windows are temporarily obscured during load (as can happen with maximized windows).

Anyway, thanks for all the fixes, I will definitely be testing more as I really like being able to fill most of my monitors with kanbans.  :wink:
