### ISSUE TITLE
[Bug]: User cannot replace/correct misspelled words using the right click Context Menu.

### ISSUE THREAD

**Issue by jdbence** [mgmeyers/obsidian-kanban#610]
### Describe the bug

If you attempt to pick one of the Context Menu options, the word doesn't get replaced in the card.
![image](https://user-images.githubusercontent.com/389775/182473379-5e449c7d-6a82-4ae5-8fde-df5e555bef52.png)

### Expected Behavior

The word should be replaced

### Steps to reproduce

1. Add a new card
2. Spell a word incorrectly
3. Right click the word and a dropdown will appear
4. Pick a word option to replace the misspelled word with
5. BUG: Nothing happens

### Operating system

macOS

**Comment by mgmeyers** [comment]
Thanks @jdbence. This seems to be an issue with Obsidian rather than this plugin. I've let the Obsidian devs know and it sounds like a fix should be released in the next version of Obsidian
