### ISSUE TITLE
[Bug]: why the setting of display tag colors not work

### ISSUE THREAD

**Issue by KyrieLii** [mgmeyers/obsidian-kanban#642]
### Describe the bug

<img width="713" alt="image" src="https://user-images.githubusercontent.com/16858738/191997840-803d0fb5-5111-44d6-a0df-4177e71625aa.png">
i

### Steps to reproduce

i change the colors, but it not work

### Operating system

macOS

**Comment by mgmeyers** [comment]
@KyrieLii This is likely due to the theme you're using overriding the setting. You'll need to submit a bug report to the theme author.

**Comment by KyrieLii** [comment]
> @KyrieLii This is likely due to the theme you're using overriding the setting. Do the colors show with the default theme? You'll need to submit a bug report to the theme author.
 
thanks for your answer!

**Comment by eefan000** [comment]
Is it solved? I also have this problem

**Comment by N0vum** [comment]
I have a default theme that requires you to choose an accent color. This accent color overrides all settings for tags :(
