### ISSUE TITLE
Add date to archived cards

### ISSUE THREAD

**Issue by jorgb** [mgmeyers/obsidian-kanban#65]
Hi,

It would be great to see a log of my completed tasks, but there is no date to relate to. It would be great if a date can be added upon archiving. Something among the lines of;

```
## Archive

### 2021-05-08
- [x] Completed task

### 2021-05-07
- [x] Completed task
- [x] Completed task
``` 

This has the benefit to unarchive tasks when they need to be copied (without altering title)
Another option maybe is prefixing it with a date like;

```
## Archive

- [x] 2021-05-08 Completed task
- [x] 2021-05-07 Completed task
- [x] 2021-05-07 Completed task
``` 

Which makes he list clean and tidy and I can still see what I did on what day.

Thank you for this wonderful plugin!

**Comment by mgmeyers** [comment]
@jorgb There is now a setting to do this! It will prepend the date and time the card was archived. The format of the date/time can be controlled via the settings. Let me know if you  run into any issues with this.
