### ISSUE TITLE
[Bug]: autogenerating lists based on board title

### ISSUE THREAD

**Issue by ToABlu** [mgmeyers/obsidian-kanban#669]
### Describe the bug

board auto-generates a list corresponding to file name; whenever a task is added, a new empty list is auto-generated
![Screen Shot 2022-10-24 at 7 00 13 PM](https://user-images.githubusercontent.com/75450204/197645732-fe00a424-e8a9-4dba-b19f-15ecab133c79.png)

### Expected Behavior

no lists should generate without user input

### Steps to reproduce

from base installation (uninstalled and retried to be sure)
-create any kanboard
-create lists and name
-new list will auto-generate with each refresh as long as there isn't an empty list with file.title

### Operating system

macOS

**Comment by mgmeyers** [comment]
@ToABlu Are you using the filename heading sync plugin or any other plugins that may be causing this?

**Comment by ToABlu** [comment]
thank you for that prompt response! yes! I just realised I have the filename heading sync plugin on;

is there any workaround to keep both functions, or should I disable the other plugin before using Kanban?
