### ISSUE TITLE
Tags Displaying Twice

### ISSUE THREAD

**Issue by tjquinn1** [mgmeyers/obsidian-kanban#683]
Tags are displaying twice on card. 
<img width="274" alt="Screenshot 2022-11-15 at 10 51 50 AM" src="https://user-images.githubusercontent.com/16781171/202028390-a537a7e3-ead9-4263-8957-59d1e9bc2e76.png">
Any ideas?

**Comment by kmatt** [comment]
http://matthewmeye.rs/obsidian-kanban/Settings/Hide%20tags%20in%20card%20titles/ ?

**Comment by tjquinn1** [comment]
@kmatt That works, I thought that hide them all together.
