### ISSUE TITLE
Dragging on iPad in circular motion moves view

### ISSUE THREAD

**Issue by kometenstaub** [mgmeyers/obsidian-kanban#71]
When I drag with a finger in a rotating motion/sometimes when long-holding on cards to move them, the view is moved.

![47A02408-E675-46DA-84D4-0CD06A67B8CE](https://user-images.githubusercontent.com/83140328/117695975-1a1f5e80-b1c1-11eb-97d6-4b6f573e3f6c.jpeg)

(The screenshot was taken with some plugins activated, however also with only the kanban plugin activated and no custom CSS it showed the same behaviour.)

**Comment by mgmeyers** [comment]
This should be fixed now!
