### ISSUE TITLE
Could not link to files like pdf in Kanban board

### ISSUE THREAD

**Issue by Ravenclawer** [mgmeyers/obsidian-kanban#72]
In obsidian when you typing [[]], it will give you some selectable options of both related notes and files in the vaults, but in kanban typing [[]] will only give you related notes, and if you use the "open as markdown" option of kanban, although you can have both files and notes in [[]] and you can select a file in [[]], once you switch back to "open as kanban" the things you typed will just disappear totally.
1. no file in [[]]
![image](https://user-images.githubusercontent.com/73892411/117767006-f7de1d00-b262-11eb-8c9e-70f9032dd464.png)
2. could select a file in "open as markdown" mode 
![image](https://user-images.githubusercontent.com/73892411/117767109-104e3780-b263-11eb-9710-49623dc49508.png)
3. the file selected disappeared in "open as kanban" mode
a.selected file in "open as markdown" mode
![image](https://user-images.githubusercontent.com/73892411/117767210-32e05080-b263-11eb-85c1-e3c98f3340ce.png)
b.selected file disappeared once switched to "open as kanban" mode
![image](https://user-images.githubusercontent.com/73892411/117767335-60c59500-b263-11eb-8b08-22a3023d6e62.png)
c. you cannot find it even when you switch back to "open as markdown“ mode
![image](https://user-images.githubusercontent.com/73892411/117767407-7b980980-b263-11eb-90ad-a200d9ff1970.png)

**Comment by mgmeyers** [comment]
@Ravenclawer Are you on the latest version of the Kanban plugin? It should search non-markdown files now.

<img width="337" alt="Screen Shot 2021-05-11 at 1 54 15 PM" src="https://user-images.githubusercontent.com/2694747/117883560-679ed880-b260-11eb-812b-2bfb0f5128c0.png">

Also, items under the kanban headings must be a list or they won't get picked up by the plugin and will be erased, eg `- [ ] [[my file.pdf]]`

**Comment by Ravenclawer** [comment]
Thank you very much, the problem was solved by reinstall the kanban plugin 0.2.6 in Obsidian.  Although I was on Kanban 0.2.6 before, I have been automatically updating kanban in Obsidian, so there might be a bug caused by Obisidan that it may have the version updated but the content of the kanban might have been interfered with by the previously existing files.

**Comment by Ravenclawer** [comment]
Thank you very much, the problem was solved by reinstall the kanban plugin 0.2.6 in Obsidian.  Although I was on Kanban 0.2.6 before, I have been automatic update kanban in Obsidian, so there might be a bug caused by Obisidan that it may have the version updated but the content of the kanban might have been interfered with by the previously existing files,
