### ISSUE TITLE
[Bug]: Date and tag are duplicated in the card

### ISSUE THREAD

**Issue by N0vum** [mgmeyers/obsidian-kanban#747]
### Describe the bug

![tag](https://user-images.githubusercontent.com/61557802/225228022-07c56ae1-180e-49dd-940e-6e3a17bb1cc1.PNG)

### Expected Behavior

![tag2](https://user-images.githubusercontent.com/61557802/225228575-12284542-102c-4baf-9c59-cb7747105e46.PNG)

### Steps to reproduce

**click:** +Add card  -->  **typing:** title @{date} #tag  --> **press:** Enter

### Operating system

Windows

**Comment by baalej** [comment]
Hi @N0vum ,

I actually found out that if you go to the plugin preferences and toggle on the option: **Hide dates in card titles** the markdown date disappears. You can also toggle **Hide tags in card titles** for example, which in my case was also "duplicated".

**Comment by N0vum** [comment]
Hi @baalej,
You are right! I should have read the manual more closely)) So "Close as not planned"

**Comment by N0vum** [comment]
It's not a bug. The display of the date and tags is configured in the settings.

**Comment by N0vum** [comment]
It's not a bug. The display of the date and tags is configured in the settings.
