### ISSUE TITLE
[Bug]: Primary button is all white in light mode

### ISSUE THREAD

**Issue by cfarvidson** [mgmeyers/obsidian-kanban#760]
### Describe the bug

I switched the theme to light and the Primary button is all white, but works on hover.

<img width="330" alt="Screenshot 2023-04-13 at 07 45 59" src="https://user-images.githubusercontent.com/7823236/231665045-0accb739-c734-4d03-b638-ca485b7390ff.png">

On hover:

<img width="343" alt="Screenshot 2023-04-13 at 07 46 04" src="https://user-images.githubusercontent.com/7823236/231665074-8caea025-3887-4b64-87fa-8eadabd376c3.png">

### Expected Behavior

I should be able to read the text on the primary button.

### Steps to reproduce

Switch to light mode and create a new list.

### Operating system

macOS

**Comment by algabl** [comment]
This actually seems to be a problem with Obsidian's default css theme. If I switch to another theme, I do not have this issue

**Comment by cfarvidson** [comment]
> This actually seems to be a problem with Obsidian's default css theme. If I switch to another theme, I do not have this issue

Ah. Thank you! I’ll file the bug there!
