### ISSUE TITLE
[Bug]: tags appear twice upon adding a todo

### ISSUE THREAD

**Issue by bgmeulem** [mgmeyers/obsidian-kanban#777]
### Describe the bug

Tags appear twice, once with the personalized color, and once with the default color. When I add a tag to a todo note, the preview shows a single tag. When I press enter and add the note to the list, the tag suddenly shows up duplicated (once with the personalized color and one with the default color). Double clicking the tag to edit it reveals the source text again, showing the tag only once.

### Expected Behavior

A single tag should appear with personalized color

### Steps to reproduce

Installed add-ons:
- better word count 0.9.4
- Calendar 1.5.10
- Citations 0.4.5
- Kanban 1.5.1
- LanguageTool Integration 0.3.3
- Obsidian git 2.16.0
- Style settings 0.4.12

### Operating system

Windows

**Comment by firai** [comment]
There's a "hide tags in card titles" setting, which makes the tag next to the card text disappear

**Comment by bgmeulem** [comment]
That fixed it, thanks!
