### ISSUE TITLE
[Bug]: Date is displayed twice

### ISSUE THREAD

**Issue by doliG** [mgmeyers/obsidian-kanban#784]
### Describe the bug

I'm trying to use date with kanban, however the display that should hide it from the card seems to work incorrectly. See screenshot below.

<img width="285" alt="image" src="https://github.com/mgmeyers/obsidian-kanban/assets/24778042/ac019a1c-d172-4b58-9c2a-3d7ed7d3b15b">

### Expected Behavior

Same as in the doc:

<img width="779" alt="image" src="https://github.com/mgmeyers/obsidian-kanban/assets/24778042/e3c08600-d955-4626-a260-b136cdb61aac">

https://publish.obsidian.md/kanban/Settings/Date+display+format

### Steps to reproduce

Not sure how to reproduce since the bug seems very simple. Maybe it's a macos specific bug ? 

### Operating system

macOS

**Comment by firai** [comment]
There's a "hide dates in card titles" setting, which makes the date next to the card text disappear

**Comment by TightEnrique** [comment]
Having the same issue on my Mac, date text is not hidden from the task name making it really ugly
![image](https://github.com/mgmeyers/obsidian-kanban/assets/81262161/4757f1dd-9bea-4b40-811d-775f78b27253)
Time is hidden correctly but date is not.

**Comment by doliG** [comment]
@TightEnrique try changing it in your board settings directly ?

**Comment by TightEnrique** [comment]
Ah! thanks, works now.
![image](https://github.com/mgmeyers/obsidian-kanban/assets/81262161/5e6173a2-4e0c-4db5-b125-82dd90f37340)

**Comment by firai** [comment]
> @firai I already tried but it didn't work. **Changing the board settings directly works.**
> 
> My guess is that changing Kanban plugin settings will only apply to new board, not the existing ones. Am I right ? @firai
> 
> Anyway, thanks for your help 🤗

Changing the plugin settings works for me on Windows and Android

**Comment by doliG** [comment]
Yep I'm on Mac, but I think it's the exact same app cuz it's a webapp... This is indeed really weird. @TightEnrique what is your OS ?
