### ISSUE TITLE
Emit an event on the `workspace` when an item changes lanes

### ISSUE THREAD

**Issue by liamcain** [mgmeyers/obsidian-kanban#79]
I'm currently figuring out how to improve my task management workflow within Obsidian and had this idea. Basically, my goal is to make some of the metadata within my "Task" files stay in sync with the board.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/693981/117917535-4a492900-b2b7-11eb-9bf8-0fc78dd496c0.png">

Since I think this is probably out of scope for the plugin, I think emitting an event for other plugins to listen to could get me most of the way there. Something like:

```ts
app.workspace.trigger("kanban:lanes-changed", boardFile: TFile, item: Item);
```

Then I could listen for the event and update inline metadata within the linked card.

**Comment by mgmeyers** [comment]
@liamcain I added a few events that should hopefully help you out here, let me know if you'd like any modifications or additions:

<img width="472" alt="Screen Shot 2021-05-14 at 1 05 47 PM" src="https://user-images.githubusercontent.com/2694747/118323275-379c4300-b4b5-11eb-96ea-c3b484a1152c.png">

In the future, I would like the kanban board to do some frontmatter manipulation, but it'll be quite a while before I get there.

**Comment by liamcain** [comment]
@mgmeyers Beautiful! I'll try playing around with this over the weekend.

> In the future, I would like the kanban board to do some frontmatter manipulation, but it'll be quite a while before I get there.

Yeah this is tricky since I imagine people will be very particular about what metadata they care about and whether it's inline via dataview or with frontmatter.
