### ISSUE TITLE
[FEATURE REQUEST] Render Code Fence like admonition in Card

### ISSUE THREAD

**Issue by Quorafind** [mgmeyers/obsidian-kanban#81]
It will be wonderful that support render code fence.

like insert admonition code fence into card:

```
​```ad-baseball
Like this
​```
```

**Comment by mgmeyers** [comment]
@Quorafind This should be possible now in 1.0.0. You can create new lines with shift+enter (can be changed in settings). Let me know if admonitions aren't rendering for some reason.
