### ISSUE TITLE
Feature request: store Kanban and card notes in directory of note selected

### ISSUE THREAD

**Issue by pdxrlk** [mgmeyers/obsidian-kanban#84]
First - excellent plugin, thank you so much.

It would be even better :-) if I could place a Kanban (and its dependent card notes) within the directory/context that was active when I issues the Kanban: Create New Board command.   Currently I have to put all Kanbans in one specific directory as set up in settings (unless I'm missing something?)

UPDATE: If I use the context menu from a selected folder in the explorer, then the Kanban's markdown file is placed in that directory. Great - but then any notes I create from cards in that Kanban are placed somewhere else, not in that same directory.

Cheers.

**Comment by mgmeyers** [comment]
Thanks @pdxrlk. The plugin should respect the default setting for where to put new Kanbans and notes, but I see that there's a bug with this.

That being said, there is a setting to specify which folder new notes are created in:

<img width="936" alt="Screen Shot 2021-05-12 at 1 41 31 PM" src="https://user-images.githubusercontent.com/2694747/118041618-d8f58e80-b327-11eb-8bee-3199d3598d66.png">

**Comment by pdxrlk** [comment]
OK I see, it's possible. I would need to set the location in each board individually, and reset if if I rename the folder.

If it helps, here is my use case. Let's say my vault is in ~pdxrlk/Vault.  And I have three project folders:

~pdxrlk/Vault/project_001
~pdxrlk/Vault/project_002
~pdxrlk/Vault/project_003

And 3 main notes:

~pdxrlk/Vault/project_001/project_description_001.md
~pdxrlk/Vault/project_002/project_description_002.md
~pdxrlk/Vault/project_003/project_description_003.md

I want to create a Kanban for each of the project folders:

~pdxrlk/Vault/project_001/project_kanban_001.md
~pdxrlk/Vault/project_001/project_kanban_002.md
~pdxrlk/Vault/project_001/project_kanban_003.md

The vault-wide settings options don't help since they specify a single location.  The per-board settings help, though I would have to change the name each time I move or rename the containing folder. 

Maybe you could add a setting that is something like "Place card notes in same location as Kanban note" ?

Thanks.

**Comment by mgmeyers** [comment]
> Maybe you could add a setting that is something like "Place card notes in same location as Kanban note"?

Yeah, this is actually supposed to be possible, though there seems to be a bug preventing it. Once I fix the bug, it'll work based on this default obsidian setting:

<img width="997" alt="Screen Shot 2021-05-12 at 3 04 04 PM" src="https://user-images.githubusercontent.com/2694747/118049948-5b378000-b333-11eb-8a11-183289454877.png">

Though, now that I think about it, having this as a Kanban setting as you suggest could be useful, so I'll add the option when I'm in there fixing the bug.

**Comment by mgmeyers** [comment]
As of v0.3.0 new kanban files and notes will be created according to the "Default location for new notes" setting
