### ISSUE TITLE
"Same folder as current file" sends new notes to parent folder and new boards to the root

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#86]
If your default folder location is "Same folder as current file", this plugin sends the file to the wrong folder.  This is because in https://github.com/mgmeyers/obsidian-kanban/blob/cf41536cc2912e49f19e210ace6d56cf9d770c63/src/components/Item/ItemMenu.ts#L173 it is using the path of the file's parent, instead of the path.  (i.e. the `.parent` should be deleted from that line)

The "new kanban" command should also be passing the path of the file currently active in the workspace (`this.app.workspace.getActiveFile()?.path`, rather than `""`), so that boards are created in the same folder as what you're working on, instead of the vault root.

**Comment by mgmeyers** [comment]
Thanks @pjeby. You saved me some hunting! I've made these updates.

**Comment by pjeby** [comment]
Thanks!  I did find a minor issue though...  you left out the `?` [here](https://github.com/mgmeyers/obsidian-kanban/commit/07e1510caeb2bfbdf76fa14d1fc996c6938d2931#r50839511), so it can generate an error if you are focused on a non-file view when the command is given.

**Comment by mgmeyers** [comment]
Gah, thanks! Fixed.
