### ISSUE TITLE
[Bug]: High CPU usage due to infinite loop in pollForNodes

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#917]
### Describe the bug

Obsidian shows high CPU usage once a kanban board has been used, so long as any Obsidian window is visible.  Disabling the plugin does not stop it: once it's happening only a restart of Obsidian fixes it.

Pausing execution in the debugger reveals that the CPU is being spent in a tight loop of requestAnimationFrame (in pollForNodes). 

### Expected Behavior

There should be a way for the node-polling to end after a reasonable timeout, or to be interrupted if the view is closed.

### Steps to reproduce

Unfortunately, I have not yet figured out how to reproduce it.  It just happens after some time period, and I don't always notice right away.  My *guess* would be that in certain circumstances, a kanban view might be discarded before being rendered, and thus the polling will never succeed, but the poll loop isn't cancelled in the process.  If that's the case, though, I haven't been able to make it happen on purpose yet.

### Operating system

Windows

**Comment by mgmeyers** [comment]
@pjeby I removed pollForNodes from the beta version. LMK if you still see high CPU usage at any point.
