### ISSUE TITLE
[Bug]: Lazy loading issue in beta v2.0.3

### ISSUE THREAD

**Issue by Tony-zf1** [mgmeyers/obsidian-kanban#919]
### Describe the bug

If there are multiple cards in a column, and the screen can not display them all when the file is first opened, the cards outside of the  screen will not be rendered any more. 
![image](https://github.com/mgmeyers/obsidian-kanban/assets/79450935/45a7a662-44d8-463f-9e78-65ba7ae2a31d)

### Steps to reproduce

A column with enough cards

### Operating system

Windows

**Comment by mgmeyers** [comment]
Thanks @Tony-zf1 

1. Does this happen with the default theme?
2. Does it happen with every kanban board?
3. Do any errors show in the developer console? (can open it with ctrl + shift + i / option + command + i)
<img width="244" alt="Screenshot 2024-04-16 at 7 45 36 AM" src="https://github.com/mgmeyers/obsidian-kanban/assets/2694747/c0d3f9d9-d590-4626-ac7a-6e928b85e831">

**Comment by Tony-zf1** [comment]
@mgmeyers 
1. Yes, same issue with default theme.
2. Yes, it happens with every kanban board using new v2-beta format, the old format files are ok.
3. No errors in dev console.

**Comment by Tony-zf1** [comment]
@mgmeyers 
There still is a little problem. The cards outside of screen can be rendered once when open the file. But if double clicked to editing mode and then exit, the card will not be rendered again.

**Comment by Tony-zf1** [comment]
Also, now the rendering time is longer than before when first open the file.

**Comment by Tony-zf1** [comment]
This issue is fixed and it works great now. Thanks! @mgmeyers
