### ISSUE TITLE
[Bug]: Icon for date and time changes to undefined after setting date.

### ISSUE THREAD

**Issue by DudeThatsErin** [mgmeyers/obsidian-kanban#920]
### Describe the bug

When I attempt to set a date by using an emoji like 📅 the date or ⏰ for the time changes to � and doesn't stay the date unless I right click and add the date manually.

I'm attempting to have tasks and kanban play nice together and I've had it work okay in the past with emojis but it isn't working when I type in the date by using my emoji picker on my keyboard.

If this only happens on mac, I can try to troubleshoot if you don't have a mac and it only happens there. I don't have time at the moment to test on my iPad or iPhone. I can and will test tomorrow and report back.

Just in case, this is my debug info from Obsidian:
```
SYSTEM INFO:
	Obsidian version: v1.5.12
	Installer version: v1.5.12
	Operating system: Darwin Kernel Version 23.4.0: Fri Mar 15 00:12:37 PDT 2024; root:xnu-10063.101.17~1/RELEASE_ARM64_T6031 23.4.0
	Login status: logged in
	Catalyst license: supporter
	Insider build toggle: on
	Live preview: on
	Base theme: adapt to system
	Community theme: AnuPpuccin v1.4.5
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 8
	Plugins enabled: 8
		1: Tasks v7.0.0
		2: Dataview v0.5.66
		3: Calendar v1.5.10
		4: BRAT v1.0.1
		5: Metadata Menu v0.8.7
		6: Link Favicons v1.8.4
		7: Style Settings v1.0.8
		8: Kanban v2.0.11-beta

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
```

Side note: Wasn't there a sidebar icon to create a kanban? Was that removed? I can't remember, been about a month or two since I used kanban.

### Expected Behavior

The emoji should stay put.

### Steps to reproduce

Install Kanban Plugin
Change date picker symbol from @ to 📅 in the settings and time symbol from @@ to ⏰
Create a kanban
Create a list
Create a card
In that card use your emoji picker to pick 📅 and choose a date.
After choosing the date, you will see the emoji change.
Do the same thing for time, choose ⏰ for time and pick any time.
This time the emoji completely disappears.

### Relevant errors (if available)

```shell
N/A
```

### Operating system

macOS

**Comment by mgmeyers** [comment]
Thanks @DudeThatsErin, think I figured this out. If you want the emoji to show up in the date pill you can change your date display / time format

<img width="1040" alt="Screenshot 2024-04-17 at 6 14 13 PM" src="https://github.com/mgmeyers/obsidian-kanban/assets/2694747/52335238-58a8-4b0e-bedf-17951b51ddc2">

<img width="271" alt="Screenshot 2024-04-17 at 6 14 32 PM" src="https://github.com/mgmeyers/obsidian-kanban/assets/2694747/0a7064e6-c426-4be3-8781-869c6c6980dc">

**Comment by DudeThatsErin** [comment]
Alright I can do that. Thank you!

Thanks,
Erin
