### ISSUE TITLE
[Feature]: Better integration with tasks plugin - automatically create new task when card is checked off/completed.

### ISSUE THREAD

**Issue by DudeThatsErin** [mgmeyers/obsidian-kanban#922]
### Goal or desired outcome of this feature

When viewing a task as markdown:
```
- [ ] Task 📅 2024-04-18 🔁 Every day when done
```
If you check off that task another one gets automatically created with the tasks plugin.

```
- [ ] Task 📅 2024-04-18 🔁 Every day when done
- [x] Task 📅 2024-04-18 🔁 Every day when done
```

This however *does not* happen when you mark a card as completed in the kanban plugin.

### Describe the feature

Automatically create cards when previous card is checked off. Tasks does this via markdown but kanban doesn't support it.

### Can you think of any alternatives or work-arounds?

You can view the kanban board as markdown, check off the task/card and then close the window and reopen as kanban (only way to go back currently).

**Comment by mgmeyers** [comment]
This will be complete once this has been merged: https://github.com/obsidian-tasks-group/obsidian-tasks/pull/2781

**Comment by DudeThatsErin** [comment]
Awesome, thanks!

**Comment by DudeThatsErin** [comment]
Looks like this was added, was it not?

I haven't been able to test the latest beta update. If so, WOO HOO! Thanks so much!

**Comment by SrSh-notme** [comment]
looking forward to integrate with the tasks plugin. Kanban cannot set completion date, I normally use archived date for Task or dataview 
to query the complete task.
