### ISSUE TITLE
[Bug]: When editing a card, after you press enter or click elsewhere the contents disappear like there is a display: none

### ISSUE THREAD

**Issue by DudeThatsErin** [mgmeyers/obsidian-kanban#923]
### Describe the bug

Title says it all. Not much else to say.

### Expected Behavior

Contents shouldn't be hidden.

### Steps to reproduce

Create a kanban
Create a board
Create a card
Edit the contents
Press enter
Contents disappear
![Screenshot 2024-04-22 at 1 52 45 PM](https://github.com/mgmeyers/obsidian-kanban/assets/2681022/0665f78a-d03e-4d40-82c3-bb87bc00b698)

### Operating system

macOS

**Comment by mgmeyers** [comment]
@DudeThatsErin I can't seem to reproduce this. Does it happen all the time? Any errors in Obsidian's developer console?
