### ISSUE TITLE
[Feature]: Recognize DataView date format

### ISSUE THREAD

**Issue by Thiago-Morais** [mgmeyers/obsidian-kanban#927]
### Goal or desired outcome of this feature

For the plugin to recognize dataview specifiers like [due:: YYYY-MM-DD] and [time: HH:mm]

### Describe the feature

Currently, the plugin only recognizes date or time if it is between curly brackets `{ }`. 
That means that you could use `[due:: {YYYY-MM-DD}]` but the curly brackets break the Dataview parse.

![image](https://github.com/mgmeyers/obsidian-kanban/assets/21369746/40a35c79-0fcb-4512-b4f1-dbc319ee1aad)

![image](https://github.com/mgmeyers/obsidian-kanban/assets/21369746/e0ae6006-70ae-4cad-a284-4dfafb9e658d)
The first one recognizes the date, parses it as a date, and converts it to the default format.
The second does not recognize the date and uses it as a text.

I can see that this would seem much more of a Dataview issue than a Kanban Plugin one. 

However other plugins also recognize the Dataview format. 
Like the Cardboard plugin here.
![image](https://github.com/mgmeyers/obsidian-kanban/assets/21369746/bdfec6f8-31f0-4f78-b953-3a341f17a8e6)

And the Tasks Plugin here.
![image](https://github.com/mgmeyers/obsidian-kanban/assets/21369746/097118b1-d5e8-48c3-a420-1b7a5fd585c9)

So if we could unify the format, we could share the same task between multiple plugins and use different functionalities across the plugins.

**Comment by HumanError13** [comment]
Sorry, if this is completed, how do I get this working in Kanban? Currently in Kanban 2.0.51 the date is not recognized in the Dataview format. Is there any option I'm missing?

![grafik](https://github.com/user-attachments/assets/19a111f4-c4da-43b6-959c-483468c45035)
