### ISSUE TITLE
[Feature]: (2.0) Allow not including columns in context menu (or make them a submenu)

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#928]
### Goal or desired outcome of this feature

It's cool that we can now send items to specific columns, but I have some boards with LOTS of columns, and the resulting effect is that if I right-click a card in the lower half of the screen, every menu item that *isn't* another column ends up half a screen away.

### Describe the feature

Either put the columns in a submenu ("Move to"?) or have an option to leave them off.  Alternately this could be gated by a column count, perhaps a setting.  I'm not picky just as long as the menu can go back to roughly its old size, even on boards w/lots of columns.  :wink:

### Can you think of any alternatives or work-arounds?

I could hack together a patch for the "always a submenu" version and send a PR?

**Comment by mgmeyers** [comment]
Good idea. I've done as you suggested and added a "Move to" submenu. LMK if you run into any issues with it.

**Comment by pjeby** [comment]
Works great!  Thanks!
