### ISSUE TITLE
Add setting to choose the week starting day in the date picker 

### ISSUE THREAD

**Issue by THeK3nger** [mgmeyers/obsidian-kanban#93]
Right now, I think, the date picker week starting day is derived automatically from Obsidian locale.

However, I use Obsidian in en-us, but I would like to have my weeks starting on Monday (as I did with the Calendar Plugin).

**Comment by mgmeyers** [comment]
@THeK3nger You can now set the start of the week in the settings

<img width="661" alt="Screen Shot 2021-09-25 at 6 10 12 PM" src="https://user-images.githubusercontent.com/2694747/134789727-31d301d3-438c-46d4-9b33-2cf710d5b3f8.png">
