### ISSUE TITLE
[Bug]: (2.0) Formatting commands not available in command palette

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#931]
### Describe the bug

When editing a card, all builtin formatting hotkeys appear to be functional, but if you open the command palette, they don't appear.  The same is true for third-party editing commands.  (I would guess this is due to app.workspace.activeEditor not being set to the active editor.)

### Expected Behavior

Available commands should be visible in the palette. 

### Steps to reproduce

Edit a card, open command palette, search for eg "bold".  But if you use the hotkey directly, it works.  activeEditor is null, compared to e.g. editing canvas cards where it points to the editor in use.

### Operating system

Windows

**Comment by mgmeyers** [comment]
Ah yes. Obsidian was clearing `activeEditor` because it expects the active editor to be in a MarkdownView. Should be fixed in the latest release

**Comment by pjeby** [comment]
It now works in current beta.  Thanks!

I still strongly suggest using the active-leaf-change event, though, or accessing the active view instead of the passed-in leaf, since it is *not* guaranteed that a successful return from setActiveLeaf() actually *sets* the supplied leaf as the active leaf.  (Pane Relief's focus lock function, for example, blocks certain changes to the active leaf, and I'm not even sure that Obsidian's API has any guarantee about that.  It'd also let you drop the code duplication from Obsidian core.)

Using the active view lets you do less fiddling with details of Obsidian internals, too, e.g.:

```ts
    this.register(
      around(this.app.workspace, {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        setActiveLeaf(next) {
          return function (...args) {
            next.apply(this, args);
            const view = this.getActiveViewOfType(KanbanView);
            if (view?.activeEditor) {
              this.activeEditor = view.activeEditor;
            }
          };
```

And the above's even simpler if it's just an active-leaf-change event listener.  But either way, using the active view ensures this won't conflict with anything that blocks or redirects the active leaf assignment.

**Comment by mgmeyers** [comment]
Thanks @pjeby! Forgot to reply to this. It turns out that `active-leaf-change` isn't called every time `setActiveLeaf` is. Specifically, if `setActiveLeaf` is called with the currently active leaf, then `workspace.activeEditor` will be set but `active-leaf-change` will not be triggered. This results in the Kanban plugin's editor from being cleared out of `workspace.activeEditor` every time the leaf is clicked.

Good idea about using `this.getActiveViewOfType`. That does seem like a better approach.

**Comment by pjeby** [comment]
Cool.  Out of curiosity, why is the `@ts-ignore` needed?  Is there some typing I'm missing that should be in monkey-around, or is it just that setActiveLeaf has multiple overloads and TypeScript is kinda dumb about overloads?  :wink:

**Comment by mgmeyers** [comment]
Yeah, that latter. I was too exhausted at the time to figure out why typescript didn't like the overloads 😮‍💨

**Comment by pjeby** [comment]
Yeah, one of the big TS gotchas around function signatures is that there are lots of places where TS silently punts to "use the last overload instead of checking them individually, because that should be general enough for everything, why not!".  (The other fun one is where you want a callback to take specific arguments, and it says, "well, this function doesn't take *any* arguments, so that should be even better, right!")

Anyway, just wanted to be sure it wasn't an issue with monkey-around.  I suspect the reason I haven't run into that on setActiveLeaf yet myself is that I haven't upgraded the Obsidian API version in some of my plugins for a year or two.  :grin:
