### ISSUE TITLE
[Bug]: [v2] Destructive behaviour when checking checkboxes in a card.

### ISSUE THREAD

**Issue by pryley** [mgmeyers/obsidian-kanban#932]
### Describe the bug

![CleanShot 2024-04-30 at 11 52 34](https://github.com/mgmeyers/obsidian-kanban/assets/134939/9ef03b35-95e9-4d99-b72c-7d7ab98f671a)

### Expected Behavior

1. Checking checkboxes should not be destructive.
2. Checkboxes should not be removed from the card when others are ticked.

### Steps to reproduce

1. Create a card with the following content:

```md
Release Checklist:

- [ ] Option 1
- [ ] Option 2
- [ ] Option 3
- [ ] Option 4
- [ ] Option 5
- [ ] Option 6
- [ ] Option 7
```
2. Tick some checkboes.

### Operating system

macOS

**Comment by mgmeyers** [comment]
Thanks @pryley ! I figured out what was going on here and it should be fixed in the latest release
