### ISSUE TITLE
[Bug]: [v2] Tag parsing inconsistancies

### ISSUE THREAD

**Issue by pryley** [mgmeyers/obsidian-kanban#933]
### Describe the bug

![CleanShot 2024-04-30 at 12 04 00](https://github.com/mgmeyers/obsidian-kanban/assets/134939/f6774961-1226-4ee0-8def-ea54e6c5a5c3)

### Expected Behavior

1. Tag parsing should detect period characters
2. Tag parsing should account for empty lines above the tags

### Steps to reproduce

1. Enable the "Move tags to card footer" setting.
2. Add the following cards to your board:

```md
Totam rem aperiam. Architecto beatae vitae dicta sunt explicabo. Et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.
#fr  #new  #v7.1
```

```md
Totam rem aperiam. Architecto beatae vitae dicta sunt explicabo. Et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque.

#fr  #new  #v7.1
```

### Operating system

macOS

**Comment by mgmeyers** [comment]
Thanks @pryley . It turns out Obsidian is a little more strict than I thought about what's allowed in tags. I've updated my code to match Obsidian so they're at least consistent. This means that periods are not allowed in tags, however, as obsidian doesn't support this.
