### ISSUE TITLE
[Bug]: (v2) Multiple boards side by side causes unexpected behaviours (empty views, duplicate views, lane appearing in more than one board, duplicate card titles)

### ISSUE THREAD

**Issue by LiaTheNun** [mgmeyers/obsidian-kanban#943]
### Describe the bug

(My advance apologies if I'm doing this wrong, I'm new here and not a programmer!) 

I downloaded the beta because I use multiple boards extensively and was hoping for the chance to give each board different CSS. 

I'm noticing behaviours that are most likely unintended. For example:
1. After creating some lanes and cards on a second board and setting a custom folder for its new notes, the board view goes blank (cards and lanes disappear). Content shows up again after reopening vault.
2. Dragging lanes from one board to another sometimes causes the board view to duplicate itself: a scrollbar appears in the side and now there's a second row of lanes underneath the actual row. Sometimes lanes become unresponsive to dragging.
3. When I have three different boards open and drag a lane from one to another, sometimes it also appears on the third one. It's not actually there in the markdown view, but I have to close and open vault to get the views to display correctly.
4. Same as item 3 but this time the duplicate lane also appears in markdown and stays there.
5. I've also seen the content of one board become entirely overwritten with another board's content - not just in the view but  actual markdown file too. Unfortunately I don't remember how exactly this happened. At the time I may have had other plugins in use. Everything else I've listed happened on a fresh vault without other plugins.

### Steps to reproduce

My system: 
MacBook Pro M1 Max / macOS Monterey 12.6.8
Obsidian 1.5.12 / Installer 1.5.11

New vault, no themes or snippets. No other plugins besides BRAT and Kanban. No YAML other than what the plugin creates, no dates, default settings.

Created three boards, opened them side by side. Created two folders in the folder where the boards are, assigned them to receive new notes from two of the boards (third board using default folder). Dragged the boards around into different configurations in the workspace (this seems to cause more errors).

### Operating system

macOS

**Comment by mgmeyers** [comment]
@LiaTheNun I think I found the source of the issue. Could you update to `2.0.37-beta` and see if the issues still persist for you?

**Comment by LiaTheNun** [comment]
![Screenshot 2024-05-06 at 8 14 50](https://github.com/mgmeyers/obsidian-kanban/assets/167989153/ffae2d99-f8fb-46a9-83fc-b136cf5d3c57)
