### ISSUE TITLE
[Feature]: Offline Mode

### ISSUE THREAD

**Issue by fcabouat** [mgmeyers/obsidian-kanban#950]
### Goal or desired outcome of this feature

Manual install (downloading main.js, manifest.json, styles.css) seems to work ok, like many plugins.

Still, it seems that the plugin tries to load some distant resource ? In authenticated proxy context, it would be way easier to setup (there are workarounds with local proxies) and work fully offline. Is that doable ?

### Describe the feature

Be able to install and use the plugin with zero network.

### Can you think of any alternatives or work-arounds?

Configure obsidian with a "local proxy => authenticated proxy" setup, but it would be tedious and a poorly configured local proxy can decrease security.

### Screenshots, mockups, or videos

![kanban-not-loading](https://github.com/mgmeyers/obsidian-kanban/assets/17034829/2c533e6c-e93a-43c4-b5f0-e79dc5111e44)

**Comment by mgmeyers** [comment]
@fcabouat This plugin doesn't make any network requests. Your screenshot shows the loading indicator for when Kanban board is being parsed from markdown.

**Comment by mgmeyers** [comment]
@fcabouat I think I figured out what was going on here. This should be fixed in the latest beta

**Comment by fcabouat** [comment]
Could test the fix successfully! That's awesome!
