### ISSUE TITLE
[Bug]: Broken checkboxes inside cards

### ISSUE THREAD

**Issue by anareaty** [mgmeyers/obsidian-kanban#951]
### Describe the bug

When I write some checkboxes inside a card and then try to click them, instead of turning into "- [x]" checkbox turns into "undefined- [x]" text, which leads to it being broken.

### Steps to reproduce

1. Create a card and put this text into it:
```
List
- [ ] one
- [ ] two
- [ ] three
```

2. Try to click a checkbox.
3. Result looks like this:
```
List
- [ ] one
undefined- [x] two
- [ ] three
```

### Operating system

Windows

**Comment by mgmeyers** [comment]
Thanks for reporting this @anareaty. 2.0.41-beta should be available in a few minutes with a fix for this.
