### ISSUE TITLE
[Bug]: [V2.0.41-beta] Does not support Tasks recurring tasks with custom status workflows

### ISSUE THREAD

**Issue by gypsyav** [mgmeyers/obsidian-kanban#952]
### Describe the bug

When using a custom status workflow in Tasks check boxes don't work for recurring tasks on the Kanban board.

In a normal workflow when you check a task box it changes from [ ] to [x] in markdown

Using a custom workflow set up in the Task plugin this can be changed so you can have an intermediate stage showing a task being worked on.  For example: when clicking the box it changes from [ ] to [/] for in progress instead of [x] for done

This custom workflow is not supported on the Kanban card and it prevents the box from being checked at all.

### Expected Behavior

The checkbox is changed to the custom status

### Steps to reproduce

Under Task Statuses in the Tasks plugin change the next status symbol to anything other than an x
Create a recurring task card on a Kanban board with check boxes enabled
Try to check the box

### Operating system

Linux

**Comment by mgmeyers** [comment]
Thanks @gypsyav, I wasn't aware this was a thing! I've updated things on my end to add support for this in 2.0.42-beta
