### ISSUE TITLE
[Bug]: Tag to bottom of card interferes with new Dataview functionality 

### ISSUE THREAD

**Issue by Kribbage** [mgmeyers/obsidian-kanban#953]
## Tag on bottom of card setting interferes with dataview queries
The content of the tag is omitted from the dataview query if the tag-to-bottom setting is enabled 

### Expected Behavior

The query works as expected and parsing of tags should replicate the same behavior as the Obsidian app

### Steps to reproduce

Enable the card to bottom setting 

input a dataview query block that contains a tag as a FROM source

the tag is displayed at the bottom of the card and the dataview query is parsed as if the tag wasn't there. You can see this is happening if you include  `FROM #yourtag AND 'somefolder`  as part of your query and the resulting error should point out that `FROM AND 'somefolder` is improper syntax.

![image](https://github.com/mgmeyers/obsidian-kanban/assets/7074018/2f24fb83-3240-4a5a-9079-bc6889b600a0)

### Operating system

Windows

**Comment by mgmeyers** [comment]
Ok, I think I found the problem. Update the plugin and let me know if you encounter any more issues with this.
