### ISSUE TITLE
[Bug]: Keep getting this error when updating properties that are linked via Linked Page Metadata

### ISSUE THREAD

**Issue by pablostuart** [mgmeyers/obsidian-kanban#956]
### Describe the bug

Just updating various linked page metadata in a tab opened to the right and the kanban board keeps showing this error.

<img width="1512" alt="Screenshot 2024-05-24 at 09 50 06" src="https://github.com/mgmeyers/obsidian-kanban/assets/23527156/ab2f08ef-2fe3-4905-a177-04d8d94fbca8">

### Steps to reproduce

Its very irregular in the way it happens, but has happened more than once and is for sure when I'm adding in linked metadata.

### Operating system

macOS

**Comment by mgmeyers** [comment]
Thanks @pablostuart. I made some changes that should hopefully fix this. Please open a new issue if you run into this again.
