### ISSUE TITLE
[Feature]: Selectable vim mode

### ISSUE THREAD

**Issue by tralce** [mgmeyers/obsidian-kanban#958]
### Goal or desired outcome of this feature

With the release of 2.0.43, as advertised, all text input boxes inherit Obsidian's native Markdown editor. This is great!

However, I am a vim mode user. Now, all Kanban inputs inherit this. The takeaway is that I must now press `i` to enter insert mode in new cards, and even the text input for creating a new List. 

I'm not sure if it's possible, but a toggle for that behavior would be extremely helpful.

### Describe the feature

It is annoying to have to hit `i` to enter insert mode in Obsidian vim mode in Kanban boards as I previously did not need to. I would like a toggle to disable this behavior as it interferes with my workflow.

**Comment by mgmeyers** [comment]
Thanks @tralce! Try the latest version and see if this works for you. I'm not a vim user so can't really verify, but I've forced the editor to go into insert mode when the card editor is activated.

**Comment by tralce** [comment]
> Thanks @tralce! Try the latest version and see if this works for you. I'm not a vim user so can't really verify, but I've forced the editor to go into insert mode when the card editor is activated.

Works perfectly! Thank you so much both for the speedy response and the amazing plugin!
