### ISSUE TITLE
[Bug]: Right click menu doesn't work on a linked note card title.

### ISSUE THREAD

**Issue by pablostuart** [mgmeyers/obsidian-kanban#959]
### Describe the bug

You can't right click open menu on a linked note title. It works on a card title before you link it to a note and it works on a linked note title when it's being edited.

### Expected Behavior

Should be able to right click, to open in new tab, to the right etc.

### Steps to reproduce

Works before you link a note.
<img width="285" alt="Screenshot 2024-05-25 at 13 13 57" src="https://github.com/mgmeyers/obsidian-kanban/assets/23527156/efd81795-f53c-4c7f-9c77-e7b2df7d7e13">

Works when linked to a note and being edited.
<img width="340" alt="Screenshot 2024-05-25 at 13 14 14" src="https://github.com/mgmeyers/obsidian-kanban/assets/23527156/e1a5aaf9-f7d8-4fdc-8b55-245dc654df25">

But not when it's just a standard linked note title. So unable to open a note in new tab, to the right etc. Unless you select to edit the title.

### Operating system

macOS

**Comment by mgmeyers** [comment]
Thanks @pablostuart , should be fixed now. Let me know if you still run into any issues with this.
