### ISSUE TITLE
[Bug]: can not open as kanban after update

### ISSUE THREAD

**Issue by sd0116baka** [mgmeyers/obsidian-kanban#961]
### Describe the bug

My Kanban broke after I updated the plugin. I provide the screenshot for you to help solve the question, hope it is of use.
![image](https://github.com/mgmeyers/obsidian-kanban/assets/157805287/ff812304-ae6d-4d0a-9317-274c86358644)

### Steps to reproduce

if I create a new kanban, it works well.
maybe my note is required.
but I don't want to show them here, if you need it, contact me.

### Operating system

Windows

**Comment by mgmeyers** [comment]
I think I found the issue here. Let me know if this error persists after updating

**Comment by sd0116baka** [comment]
> I think I found the issue here. Let me know if this error persists after updating

![image](https://github.com/mgmeyers/obsidian-kanban/assets/157805287/cecf49ad-21c8-4c0f-9bbc-420dc566e0bf)
now it works after I update the plugin, but the color of the date turns red instead of blue, is that a new feature?
