### ISSUE TITLE
[Bug]: Can no longer sort lists by Tasks dates in update 2.0.47

### ISSUE THREAD

**Issue by gypsyav** [mgmeyers/obsidian-kanban#963]
### Describe the bug

When sorting lists you are no longer given the option to sort by the created, start, scheduled, or due dates created by the Tasks plugin when it was possible to do so before.

### Expected Behavior

Options to sort by dates created with the Tasks plugin should show when you click on sort by for a list.

### Steps to reproduce

Create a card as a task and give it any date in the Tasks format
Click on Sort By for the list
See there is no option to sort by the Tasks date

### Operating system

Linux

**Comment by mgmeyers** [comment]
Thanks @gypsyav. Found the culprit and released a fix. Let me know if you still run into any issues.
