### ISSUE TITLE
[Bug]: When the time is not the default time, a time trigger may be recognized as a date trigger

### ISSUE THREAD

**Issue by ZIYUZHIYAN** [mgmeyers/obsidian-kanban#966]
### Describe the bug

When the time is not the default time, a time trigger is recognized as a date trigger. When tested, this happens when the minutes are less than or equal to 12. At this point it seems that the default @@ is not considered a time trigger, but a separate @ and a date trigger.
For example, `@@{01:09}` is rendered as `@2001-09-01 周六`.

### Expected Behavior

@@ should be rendered correctly.

### Steps to reproduce

Kanban 2.0.48       obsidian 1.5.12

`@@{01:09}` is rendered as `@2001-09-01 周六`
`@@{14:09}` is rendered as `@2014-09-01 周一`
`@@{01:12}` is rendered as `@2001-12-01 周三`
`@@{01:12}` is rendered as `@2001-12-01 周三`
`@@{01:13}` is rendered as `01:13`

Strangely enough, when editing, the rendering is correct, but after pressing Enter to end the editing, the rendering is wrong.

The solution I've found so far is to change the time trigger to a completely different symbol than the date trigger, such as `%`.At this point, everything is normal.

### Operating system

Windows

**Comment by ingensargens** [comment]
I have the same issue. See below image - (one is during editing, other is post editing).
![image](https://github.com/mgmeyers/obsidian-kanban/assets/67170142/19abcc7d-a1c6-4603-b191-15d833350bdf)
![image](https://github.com/mgmeyers/obsidian-kanban/assets/67170142/2dfebcc9-49c8-47e6-804e-1e9b5abb43b1)
