### ISSUE TITLE
[Bug]: Opening the Obsidian application didn't show tag colors.

### ISSUE THREAD

**Issue by dinogen** [mgmeyers/obsidian-kanban#968]
### Describe the bug

Opening Obsidian if the document opened last time is a kanban board, tag colors are not honored.

### Expected Behavior

Tag colors should be correctly displayed.

### Steps to reproduce

1. Open a kanban board
2. set few tag with some colors
3. close obsidian
4. open obsidian

### Operating system

Windows

**Comment by mgmeyers** [comment]
@dinogen What version of the Kanban plugin are you on?
