### ISSUE TITLE
Obsidian file menu not working on card links

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#97]
Normally, right-clicking a link to a file in Obsidian brings up a context menu to perform operations on the file (such as renaming, moving, open in default app, etc.).  It isn't working on Kanban cards, however.

It appears the issue is that the Kanban view is cloning the markdown preview via innerHTML, which ends up stripping the event handlers that would perform this and other preview functions, and so then the card's default context menu takes over.

As a workaround (in the event the markdown preview can't be mounted directly instead), I suppose you could add back in a contextmenu event handler for `a.internal-link` within the card, and trigger the [file-menu event](https://github.com/obsidianmd/obsidian-api/blob/master/obsidian.d.ts#L3352) via something like:

```js
const linkedFile = this.app.metadataCache.getFirstLinkpathDest(obsidian.getLinkpath(link), pathOfKanbanFile);
if (linkedFile) {
    const menu = new Menu(this.app)
    // The following will add items like "rename", "star", "reveal in nav", etc.:
    this.app.workspace.trigger("file-menu", menu, linkedFile, "link-context-menu", view.leaf);
    // ... add kanban-specific items to menu here w/a separator above
    menu.showAtPosition({x: event.pageX, y: event.pageY});
}
```

This would avoid the need to switch to markdown mode in order to access the standard obsidian link menu.

**Comment by mgmeyers** [comment]
Thanks @pjeby! It turns out I had to call `onLinkContextMenu` to get this to work. Triggering `file-menu` wasn't adding the correct menu items.

```
        // @ts-ignore
        view.app.workspace.onLinkContextMenu(
          e,
          getLinkpath(internalLinkPath),
          view.file.path
        );
```
