### ISSUE TITLE
Front matter parsing breaks if a value or comment contains `---`

### ISSUE THREAD

**Issue by pjeby** [mgmeyers/obsidian-kanban#98]
A kanban note's front matter is destroyed if any value or comment in it (such as a template or directory name) contains `---`.  That's because this regex is incorrect: https://github.com/mgmeyers/obsidian-kanban/blob/d8c0b8c6861dd7349c4747d4f2c06303342650ff/src/parser.ts#L17

It should be `/^---$([\w\W]+?)^---$/`, so that the `---` are only recognized if they are on lines by themselves with no indentation, and not in the middle of a value.

**Comment by mgmeyers** [comment]
Thanks @pjeby! This should be fixed now
